pmdapostgresql: test for $osuser, not $user
If $osuser is defined in the config file, then that is
the user the PMDA will be run as, else defaults to the
current user (no set_user() call will be made).

diff --git a/src/pmdas/postgresql/Install b/src/pmdas/postgresql/Install
--- a/src/pmdas/postgresql/Install
+++ b/src/pmdas/postgresql/Install
@@ -31,17 +31,17 @@ if [ ! -f "$conf" ]; then
     exit
 fi
 
-eval `grep "osuser=" $conf`
-if [ -n "$user" ]; then
-    echo "postgres user defined in $conf is \"$user\""
-    if ! id $user >/dev/null 2>&1; then
-        echo "Error: no such user \"$user\" on this system"
+eval `grep "^osuser=" $conf`
+if [ -n "$osuser" ]; then
+    echo "OS user defined in $conf is \"$osuser\""
+    if ! id $osuser >/dev/null 2>&1; then
+        echo "Error: no such user \"$osuser\" on this system"
         status=1
         exit
     fi
 
-    gid=`id $user | sed -e 's/^.*gid=//' -e 's/(.*$//'`
-    echo "group id for user \"$user\" is \"$gid\""
+    gid=`id $osuser | sed -e 's/^.*gid=//' -e 's/(.*$//'`
+    echo "group id for user \"$osuser\" is \"$gid\""
 
     mkdir -p "$PCP_VAR_DIR/config/pmda" 2>/dev/null
     indoms="0 1 2 3 4 5 6 7 8 9 10 11 12"
