build: rpm spec file change to avoid touch on read-only filesystems
Related to https://github.com/performancecopilot/pcp/issues/816

diff --git a/build/rpm/pcp.spec.in b/build/rpm/pcp.spec.in
--- a/build/rpm/pcp.spec.in
+++ b/build/rpm/pcp.spec.in
@@ -169,6 +169,24 @@ then
 fi
 }
 
+%global install_file() %{expand:
+if [ -w "%1" ]
+then
+    (cd "%1" && touch "%2" && chmod 644 "%2")
+else
+    echo "WARNING: Cannot write to %1, skipping %2 creation." >&2
+fi
+}
+
+%global rebuild_pmns() %{expand:
+if [ -w "%1" ]
+then
+    (cd "%1" && ./Rebuild -s && rm -f "%2")
+else
+    echo "WARNING: Cannot write to %1, skipping namespace rebuild." >&2
+fi
+}
+
 %global selinux_handle_policy() %{expand:
 SELINUX_DIR=@pcp_var_dir@/selinux
 PCP_BINADM_DIR=@pcp_binadm_dir@
@@ -2690,7 +2708,7 @@ PCP_PMCDCONF_PATH=@pcp_pmcdconf_path@
 for PMDA in dm nfsclient ; do
     if ! grep -q "$PMDA/pmda$PMDA" "$PCP_PMCDCONF_PATH"
     then
-	touch "$PCP_PMDAS_DIR/$PMDA/.NeedInstall"
+	%{install_file "$PCP_PMDAS_DIR/$PMDA" .NeedInstall}
     fi
 done
 # increase default pmlogger recording frequency
@@ -3026,9 +3044,7 @@ chown -R pcp:pcp "$PCP_LOG_DIR/pmlogger" 2>/dev/null
 chown -R pcp:pcp "$PCP_SA_DIR" 2>/dev/null
 chown -R pcp:pcp "$PCP_LOG_DIR/pmie" 2>/dev/null
 chown -R pcp:pcp "$PCP_LOG_DIR/pmproxy" 2>/dev/null
-touch "$PCP_PMNS_DIR/.NeedRebuild"
-chmod 644 "$PCP_PMNS_DIR/.NeedRebuild"
-
+%{install_file "$PCP_PMNS_DIR" .NeedRebuild}
 %if "@enable_systemd@" == "true"
     %systemd_postun_with_restart pmcd.service
     %systemd_post pmcd.service
@@ -3047,9 +3063,7 @@ chmod 644 "$PCP_PMNS_DIR/.NeedRebuild"
     /sbin/chkconfig --add pmproxy >/dev/null 2>&1
     /sbin/service pmproxy condrestart
 %endif
-
-cd "$PCP_PMNS_DIR" && ./Rebuild -s && rm -f .NeedRebuild
-cd
+%{rebuild_pmns "$PCP_PMNS_DIR" .NeedRebuild}
 
 %post libs -p /sbin/ldconfig
 %postun libs -p /sbin/ldconfig
