libpcp et al: change PCP debugging control infrastructure
We have historically used bit-fields over the int pmDebug and the
DBG_TRACE_xxx macros to support the -D and __pmParseDebug() services
for run-time conditional debugging and tracing in various PCP
libraries and applications.

We've nearly run out of bits in the 31-bit int (pmDebug has to stay
positive) and although pmDebug2 was suggested (to follow the XFS
thinking), there is a better way ... an extensible vector of ints
(one per debug option) that can efficiently be set and tested.

This code has (mostly) been wrapped in #ifdef PCP_DEBUG ... but the last
time this was NOT built into the code was performance tests in early
1994 to convince Akmal Khan that PCP could compete with sar/vmstat in
terms of sysem overhead to collect performance data.  I think that use
case has long since become nothing more than a quaint historical anomaly.

So this reimplementation:
- removes the restriction on at most 31 debug options or classes
- is backwards compatible, so all uses and abuses of pmDebug are
  maintained for the bit-field based debug options
- exposes a sane pmSetDebug/pmClearDebug interface as a full PMAPI
  member
- starts to peel away the #ifdef PCP_DEBUG guards

diff --git a/src/include/pcp/mk_pmdbg b/src/include/pcp/mk_pmdbg
--- a/src/include/pcp/mk_pmdbg
+++ b/src/include/pcp/mk_pmdbg
@@ -1,6 +1,7 @@
 #!/bin/sh
 #
 # Copyright (c) 1997 Silicon Graphics, Inc.  All Rights Reserved.
+# Copyright (c) 2017 Ken McDonell.  All Rights Reserved.
 # 
 # This program is free software; you can redistribute it and/or modify it
 # under the terms of the GNU General Public License as published by the
@@ -29,25 +30,78 @@ then
     exit 1
 fi
 
+sedcmd=`$PCP_AWK_PROG <impl.h '
+BEGIN			{ start=0 }
+/^typedef struct {/	{ start=NR }
+/^} pmdebugoptions_t;/	{ if (start>0) print start "," NR "p"; exit }'`
+if [ -z $sedcmd ]
+then
+    echo "mk_pmdbg: cannot find __pmdebugoptions typedef in impl.h"
+    exit 1
+fi
+
+tmp=/var/tmp/$$
+trap "rm -f $tmp.*; exit 0" 0 1 2 3 15
+
 rm -f pmdbg.h
 cat <<End-of-File >pmdbg.h
 /*
  * Built from impl.h by mk_pmdbg.  Any modifications will be lost.
  */
 
-typedef const struct {
+typedef struct {
     const char	*name;
-    const int	bit;
+    const int	bit;		/* old 32-bit mask value */
+    int	* const options;	/* points to a new pmDebugOptions.xxx */
+    int		state;		/* for internal use */
+    const char	*text;		/* explanation */
 } debug_map_t;
 
-static const debug_map_t debug_map[] = {
+static debug_map_t debug_map[] = {
 End-of-File
 
+# start with the old DBG_TRACE macros ...
+#define DBG_TRACE_PDU		(1<<0)	/* PDU send and receive */
+#
 sed -n <impl.h \
     -e '/#define[ 	]*DBG_TRACE_/{
-s/#define[ 	]*\(DBG_TRACE_\)\([A-Z0-9_]*\).*/    { "\2",	\1\2 },/p
+s/#define[ 	]*DBG_TRACE_\([A-Z0-9_]*\)/\1/
+s/[ 	].*\/\* */ /
+s/ *\*\///
+p
 }' \
-| $PCP_SORT_PROG >>pmdbg.h
+| while read OPTION ignore_text
+do
+    option=`echo "$OPTION" | tr '[A-Z]' '[a-z]'`
+    echo "    { \"$option\", DBG_TRACE_$OPTION, &pmDebugOptions.$option, 0, \"TEXT\" }," >>$tmp.tmp
+done
+
+cat $tmp.tmp >>pmdbg.h
+echo "/* new debug options with no DBG_TRACE_xxx equivalent */" >>pmdbg.h
+
+# New ones ... look like this
+#	int	exec;	 	/* pmExec tracing */
+#
+sed -n -e $sedcmd <impl.h \
+| sed -n \
+    -e '/[ 	]*int[ 	][ 	]*\([a-z][a-z0-9_]*\);/{
+s//\1/
+s/[ 	].*\/\* */ /
+s/ *\*\///
+p
+}' \
+| while read option text
+do
+    if grep "\"$option\"," $tmp.tmp >/dev/null
+    then
+	# matches the old DBG_TRACE macros
+	sed -e "/\"$option\"/s@\"TEXT\"@\"$text\"@" <pmdbg.h >$tmp.fix
+	mv $tmp.fix pmdbg.h
+    else
+	# new one
+	echo "    { \"$option\", 0, &pmDebugOptions.$option, 0, \"$text\" }," >>pmdbg.h
+    fi
+done
 
 cat <<End-of-File >>pmdbg.h
 };
@@ -55,4 +109,4 @@ cat <<End-of-File >>pmdbg.h
 static const int num_debug = sizeof(debug_map) / sizeof(debug_map[0]);
 End-of-File
 
-exit 0
+exit
