Add qualified RHEL6 output to sar2pcp data check test (qa/370)
Extensions to the mksa-sysstat test data generation script to
work with the RHEL/Fedora sadc installation paths.  Also made
that script use -S XALL in place of -S ALL, runs extended-ALL
mode for stats collection.

Added in the binary data for RHEL6 sysstat (9.0.4-based), and
added to test 370 to use the qualified output for this version.
Updated existing qualified output for one existing qualified
sysstat versions as sar2pcp now quietly skips usb-devices (was
verbosely skipped before).

diff --git a/qa/src/mksa-sysstat b/qa/src/mksa-sysstat
--- a/qa/src/mksa-sysstat
+++ b/qa/src/mksa-sysstat
@@ -25,9 +25,19 @@ then
     exit 1
 fi
 
+sadc=""
+[ -x /usr/lib/sa/sadc ] && sadc=/usr/lib/sa/sadc
+[ -x /usr/lib64/sa/sadc ] && sadc=/usr/lib64/sa/sadc
+[ -x /usr/lib/sysstat/sadc ] && sadc=/usr/lib/sysstat/sadc
+if [ "X$sadc" = X ]
+then
+    echo "Error: cannot find sadc in any of the known places"
+    exit 1
+fi
+
 # collect data every 5 secs for 3 mins
 echo -n "Creating sa-sysstat-$version ..."
-/usr/lib/sysstat/sadc -S ALL 5 36 sa-sysstat-$version
+$sadc -S XALL 5 36 sa-sysstat-$version
 echo
 
 exit 0
