qa: reorganize archives - part 9
Move the dynamically created archives out of qa/src and into the
(new) qa/tmparch directory.

This includes the foo, bar, bigbin, interp and gap families of
archives.

A bunch of QA tests needed to be modified to accommodate this
change.

diff --git a/qa/src/mv-me b/qa/src/mv-me
--- a/qa/src/mv-me
+++ b/qa/src/mv-me
@@ -1,9 +1,17 @@
 #!/bin/sh
 #
+# -a [default]
 # relocate archives from here to ../archives
 # - git mv
-# - remove refs in GNUlocaldefs
+# - remove refs in GNUlocaldefs (SRCARCH)
 # - fix all associated QA tests and their output
+#
+# -t
+# relocate archives from here to ../tmparch
+# - remove refs in GNUlocaldefs (MKARCH)
+# - fix all associated QA tests and their output
+# - rules need to be manually cut out of GNUlocaldefs and put
+#   into ../tmparch/GNUlocaldefs
 #
 
 _ans()
@@ -22,13 +30,42 @@ tmp=/var/tmp/mv-me-$$
 rm -rf $tmp $tmp.*
 trap "rm -f $tmp.*; exit 0" 0 1 2 3 15
 
+_usage()
+{
+    echo >&2 "Usage: $0 [-a|-t]"
+    exit 1
+}
+
+macro=SRCARCH
+dst=archives
+while getopts 'at?' p
+do
+    case "$p"
+    in
+	a)
+	    macro=SRCARCH
+	    dst=archives
+	    ;;
+	t)
+	    macro=MKARCH
+	    dst=tmparch
+	    ;;
+	?)
+	    _usage
+	    # NOTREACHED
+	    ;;
+    esac
+done
+
+shift `expr $OPTIND - 1`
+
 # spilt GNUlocaldefs, add spaces at start and end of lines
 sed <GNUlocaldefs \
     -e 's/^/ /' \
     -e 's/$/ /' \
 | awk '
 BEGIN				{ part = "head" }
-part == "head" && /^ SRCARCH[ 	]=/	{ part = "macro" }
+part == "head" && /^ '"$macro"'[ 	]=/	{ part = "macro" }
 part == "macro" && NF == 0	{ part = "tail" }
 				{ print >"'$tmp'.make." part }'
 
@@ -41,13 +78,16 @@ do
 	    ;;
     esac
     echo "${arch}:"
-    git shortlog -1 -- ${arch}.0 >$tmp.out
-    if [ -s $tmp.out ]
+    if [ "$dst" != tmparch ]
     then
-	: ok
-    else
-	echo "Error: apparently not checked into git"
-	exit
+	git shortlog -1 -- ${arch}.0 >$tmp.out
+	if [ -s $tmp.out ]
+	then
+	    : ok
+	else
+	    echo "Error: apparently not checked into git"
+	    exit
+	fi
     fi
 
     if grep "[ 	]${arch}.0 " $tmp.make.macro >/dev/null
@@ -56,7 +96,7 @@ do
 	    -e "s/\\([ 	]\\)${arch}.0 /\\1/"
 	mv $tmp.tmp $tmp.make.macro
     else
-	echo "Error: unable to update SRCARCH macro in GNUlocaldefs"
+	echo "Error: unable to update $macro macro in GNUlocaldefs"
 	echo "Failed for ${arch}.0 in ..."
 	cat $tmp.make.macro
 	exit
@@ -85,7 +125,12 @@ echo "cat $tmp.make.head $tmp.make.macro $tmp.make.tail | sed -e 's/ \$//' -e 's
 cat $tmp.movers \
 | while read file
 do
-    echo "git mv $file ../archives/$file" >>$tmp.sh
+    if [ "$dst" = tmparch ]
+    then
+	echo "rm -f $file" >>$tmp.sh
+    else
+	echo "git mv $file ../$dst/$file" >>$tmp.sh
+    fi
 done
 
 echo
@@ -116,7 +161,7 @@ do
 	    continue
 	fi
 	# real guard now
-	if egrep -l "src/$arch([.'\"\`\$,*{[/ 	]|\$)" $file >/dev/null
+	if egrep -l "src/$arch([.'\"\`\$,:\*{[/ 	]|\$)" $file >/dev/null
 	then
 	    case $file
 	    in
@@ -138,8 +183,8 @@ do
 		    fi
 		    sed \
 			-e '/(pmcd.pmlogger.archive)/n' \
-			-e "s;src/$arch\([.'\"\`\$,*{[/ 	]\);archives/$arch\1;" \
-			-e "s;src/$arch\$;archives/$arch;" \
+			-e "s;src/$arch\([.'\"\`\$,:\*{[/ 	]\);$dst/$arch\1;" \
+			-e "s;src/$arch\$;$dst/$arch;" \
 			<$infile >$file.mv-me
 		    if [ "$infile" = "$file" ]
 		    then
