Mac OS X QA bonanza
With this changes all but a handful of the first 300 QA tests pass on
both Mac OS X and Linux.  Too many changes and too many issues resolved
to spell out the gory details here, but adding cases for $PCP_PLATFORM
being darwin, avoiding the missing proc.* metrics and resolving the .so
vs .dylib $DSO_SUFFIX differences and removing general sloppiness that
GNU's getopt allows were the most common changes.

diff --git a/066 b/066
--- a/066
+++ b/066
@@ -57,7 +57,8 @@ _filter_log()
 	-e 's/00001983  0000ffff/83190000  ffff0000/' \
 	-e "s;$PCP_PMCDCONF_PATH;\$PCP_PMCDCONF_PATH;g" \
 	-e "s;$PCP_VAR_DIR;\$PCP_VAR_DIR;g" \
-	-e 's;$PCP_PMDAS_DIR/pmcd/;;'
+	-e 's;$PCP_PMDAS_DIR/pmcd/;;' \
+	-e "s;\.$DSO_SUFFIX;.\$DSO_SUFFIX;g"
 }
 
 interrupt()
@@ -102,7 +103,9 @@ _myfilter_config()
 	-e "s;$PCP_PMDAS_DIR;\$PCP_PMDAS_DIR;g" \
 	-e "/^irix/s/.*/[platform PMDA]/" \
 	-e "/^linux/s/.*/[platform PMDA]/" \
+	-e "/^darwin/s/.*/[platform PMDA]/" \
 	-e 's;$PCP_PMDAS_DIR/pmcd/;;' \
+	-e "s;\.$DSO_SUFFIX;.\$DSO_SUFFIX;g" \
     | _filter_pmcd_log
 }
 
@@ -125,11 +128,21 @@ then
 linux   60      dso     linux_init      $PCP_PMDAS_DIR/linux/pmda_linux.so
 pmcd	2	dso	pmcd_init	$PCP_PMDAS_DIR/pmcd/pmda_pmcd.so
 End-of-File
-else
+elif [ $PCP_PLATFORM = irix ]
+then
     cat >>$tmp  <<End-of-File
 irix	1	dso	irix_init	libirixpmda.so
 pmcd	2	dso	pmcd_init	pmda_pmcd.so
 End-of-File
+elif [ $PCP_PLATFORM = darwin ]
+then
+    cat >>$tmp  <<End-of-File
+darwin	78	dso	darwin_init	$PCP_PMDAS_DIR/darwin/pmda_darwin.dylib
+pmcd	2	dso	pmcd_init	$PCP_PMDAS_DIR/pmcd/pmda_pmcd.dylib
+End-of-File
+else
+    echo "Error - need pmcd.conf setup for $PCP_PLATFORM"
+    exit 1
 fi
 
 cat >>$tmp  <<End-of-File
diff --git a/067 b/067
--- a/067
+++ b/067
@@ -106,12 +106,23 @@ linux	60	dso	linux_init	$PCP_PMDAS_DIR/linux/pmda_linux.so
 pmcd	2	dso	pmcd_init	$PCP_PMDAS_DIR/pmcd/pmda_pmcd.so
 test	3	socket	inet 2222
 End-of-file
-else
+elif [ $PCP_PLATFORM = linux ]
+then
 cat >$tmp  <<End-of-file
 irix	1	dso	irix_init	libirixpmda.so
 pmcd	2	dso	pmcd_init	pmda_pmcd.so
 test	3	socket	inet 2222
 End-of-file
+elif [ $PCP_PLATFORM = darwin ]
+then
+cat >$tmp  <<End-of-file
+darwin	78	dso	darwin_init	$PCP_PMDAS_DIR/darwin/pmda_darwin.dylib
+pmcd	2	dso	pmcd_init	$PCP_PMDAS_DIR/pmcd/pmda_pmcd.dylib
+test	3	socket	inet 2222
+End-of-file
+else
+    echo "Error - need pmcd.conf setup for $PCP_PLATFORM"
+    exit 1
 fi
 
 # netstat -an formats
@@ -121,6 +132,9 @@ fi
 #
 # Redhat 7.3 and 9
 # tcp        0      0 0.0.0.0:2222            0.0.0.0:*               LISTEN
+#
+# Mac OS X 10.6
+# tcp4       0      0  *.4330                 *.*                    LISTEN
 #
 
 $sudo $signal -a pmgadgets pmchart pmview >/dev/null 2>&1
@@ -137,7 +151,8 @@ netstat -an \
     -e 's/0\.0\.0\.0/*/g' \
     -e 's/  */ /g' \
     -e 's/ *$//' \
-    -e 's/:/./g'
+    -e 's/:/./g' \
+    -e 's/tcp4/tcp/'
 echo
 
 cp $config $oconfig
diff --git a/113 b/113
--- a/113
+++ b/113
@@ -18,8 +18,18 @@ trap "rm -f $tmp.*; exit \$status" 0 1 2 3 15
 rm -f $seq.full
 
 filesystems=`mount \
+	     | sed -e 's/[(,)]//g' \
              | $PCP_AWK_PROG '
-$5 == "efs" || $5 == "xfs" || $5 == "ext2" || $5 == "ext3"	{ print $1 }'`
+$4 == "type" && ($5 == "efs" || $5 == "xfs" || $5 == "ext2" || $5 == "ext3") { print $1 }
+$4 == "hfs" { print $1 }'`
+
+if [ -z "$filesystems" ]
+then
+    echo "Botch: cannot extract filesystems list from mount(1) output ..."
+    mount
+    sts=1
+    exit
+fi
 
 rootdev=`mount | $PCP_AWK_PROG '$3 == "/" { print $1 }'`
 
@@ -95,13 +105,17 @@ pminfo -f \
     filesys.freefiles \
     filesys.mountdir \
     filesys.full \
-| sed -e "s/$free/filesys.free/" -e 's/\[//g' -e 's/\]//g' -e 's/\"//g' \
+| sed \
+    -e '/"devfs"/d' \
+    -e '/"map -hosts"/d' \
+    -e '/"map auto_home"/d' \
+    -e "s/$free/filesys.free/" \
+    -e 's/\[//g' -e 's/\]//g' \
+    -e 's/\"//g' \
 | $PCP_AWK_PROG '
-    /^[ \t]*$/ {next}
-    /^filesys/ {metric=$1}
-    $1 == "inst" {
-	printf "%s_%s %s\n", metric, $4, $6
-    }' \
+/^[ \t]*$/	{next}
+/^filesys/	{metric=$1}
+$1 == "inst" { printf "%s_%s %s\n", metric, $4, $6 }' \
 | LC_COLLATE=POSIX sort > $tmp.1
 
 echo "-- pcp-filtered-1 --" >>$seq.full
@@ -132,13 +146,12 @@ do
 		  printf "%s_%s %d\n", "filesys.freefiles", dev, $8
 		  printf "%s_%s %d\n", "filesys.mountdir", dev, $10
 		}' 
-    elif [ $PCP_PLATFORM = linux ]
+    elif [ $PCP_PLATFORM = linux -o $PCP_PLATFORM = darwin ]
     then
-	$sudo df -lk $f \
+	$sudo df -lk \
+	| grep $f \
 	| $PCP_AWK_PROG '
-/^Filesystem/	{ dev="'$f'"
-		  next
-		}
+BEGIN		{ dev="'$f'" }
 NF == 1		{ next }
 NF == 6		{ printf "%s_%s %d\n", "filesys.capacity",  dev, $2
 		  printf "%s_%s %d\n", "filesys.used", dev, $3
@@ -150,11 +163,10 @@ NF == 5		{ printf "%s_%s %d\n", "filesys.capacity",  dev, $1
 		  printf "%s_%s %d\n", "filesys.free", dev, $3
 		  printf "%s_%s %d\n", "filesys.mountdir", dev, $5
 		}'
-	$sudo df -li $f \
+	$sudo df -li \
+	| grep $f \
 	| $PCP_AWK_PROG '
-/^Filesystem/	{ dev="'$f'"
-		  next
-		}
+BEGIN		{ dev="'$f'" }
 NF == 1		{ next }
 NF == 6		{ printf "%s_%s %d\n", "filesys.maxfiles",  dev, $2
 		  printf "%s_%s %d\n", "filesys.usedfiles", dev, $3
@@ -163,9 +175,13 @@ NF == 6		{ printf "%s_%s %d\n", "filesys.maxfiles",  dev, $2
 NF == 5		{ printf "%s_%s %d\n", "filesys.maxfiles",  dev, $1
 		  printf "%s_%s %d\n", "filesys.usedfiles", dev, $2
 		  printf "%s_%s %d\n", "filesys.freefiles", dev, $3
+		}
+NF == 9		{ printf "%s_%s %d\n", "filesys.maxfiles",  dev, $6+$7
+		  printf "%s_%s %d\n", "filesys.usedfiles", dev, $6
+		  printf "%s_%s %d\n", "filesys.freefiles", dev, $7
 		}'
     else
-	echo "Blah, what sort df magic is needed for a \"$PCP_PLATFORM\" system?"
+	echo "Blah, what sort df magic is needed for a \"$PCP_PLATFORM\" system?" >&2
 	status=1
 	exit
     fi
