assorted changes for Mac OS X
With these changes, PCP 3.5 RC passes the -g sanity group on
Mac OS X (10.6.0 specifically).

diff --git a/1044 b/1044
--- a/1044
+++ b/1044
@@ -75,8 +75,19 @@ head -2 $seq.full			# check the initial lines generated OK
 
 echo
 echo "=== check generated config.pmie is good pmie syntax"
-pmie -C $seq.full
-echo status=$?
+# Mac OS X issue ... swap.pagesout is not supported, so we get
+# pmie: metric swap.pagesout not in namespace for host Colleens-iMac.local
+# pmLookupName failed: Unknown metric name
+#
+pmie -C $seq.full >$tmp.out 2>&1
+sts=$?
+
+$PCP_AWK_PROG <$tmp.out '
+BEGIN						{ skip = 0 }
+/pmie: metric swap.pagesout not in namespace/	{ skip = 2 }
+skip > 0					{ skip--; next }
+						{ print }'
+echo status=$sts
 
 cat > $tmp.input << EOF
 list all
