many - accommodate the death of the binary format PMNS in PCP 4.0
Lots of tests changed here to continue to work in PCP 3.x and
also in PCP 4.0 where the binary format PMNS, root.bin and
pmnscomp are all gone.

diff --git a/199 b/199
--- a/199
+++ b/199
@@ -5,12 +5,22 @@
 # Copyright (c) 1995-2002 Silicon Graphics, Inc.  All Rights Reserved.
 #
 
-seq=`basename $0`
-echo "QA output created by $seq"
-
 # get standard filters
 . ./common.product
+. ./common.filter
 . ./common.check
+
+seq=`basename $0`
+
+rm -f $seq.out
+if [ $PCP_VER -lt 4000 ]
+then
+    ln $seq.out.1 $seq.out || exit 1
+else
+    ln $seq.out.2 $seq.out || exit 1
+fi
+
+echo "QA output created by $seq"
 
 signal=$PCP_BINADM_DIR/pmsignal
 status=1
@@ -18,39 +28,49 @@ install_on_cleanup=true
 
 _cleanup()
 {
-	if diff $tmp.root $PCP_VAR_DIR/pmns/root >/dev/null 2>&1
+
+    if $sudo make >$tmp.out 2>&1
+    then
+	:
+    else
+	cat $tmp.out
+	echo "Arrgh, cleanup make failed"
+	exit
+    fi
+
+    if diff $tmp.root $PCP_VAR_DIR/pmns/root >/dev/null 2>&1
+    then
+	:
+    else
+	[ -f $tmp.root ] && $sudo mv $tmp.root $PCP_VAR_DIR/pmns/root
+    fi
+
+    if diff $tmp.pmcd.conf $PCP_PMCDCONF_PATH > /dev/null 2>&1
+    then
+	:
+    else
+
+# do a default install which ensures the pmns and any views are installed
+
+	if $install_on_cleanup
 	then
-	    :
-	else
-	    [ -f $tmp.root ] && $sudo mv $tmp.root $PCP_VAR_DIR/pmns/root
+	    $sudo ./Install < /dev/null > /dev/null 2>&1
 	fi
+
+# PMDA may have been installed differently to default. As everything is
+# installed we can use the old pmcd.conf file to restore state.
 
 	if diff $tmp.pmcd.conf $PCP_PMCDCONF_PATH > /dev/null 2>&1
 	then
 	    :
 	else
-
-# do a default install which ensures the pmns and any views are installed
-
-	    if $install_on_cleanup
-	    then
-		$sudo ./Install < /dev/null > /dev/null 2>&1
-	    fi
-
-# PMDA may have been installed differently to default. As everything is
-# installed we can use the old pmcd.conf file to restore state.
-
-	    if diff $tmp.pmcd.conf $PCP_PMCDCONF_PATH > /dev/null 2>&1
-	    then
-		:
-	    else
-	    	[ -f $tmp.pmcd.conf ] && $sudo mv $tmp.pmcd.conf $PCP_PMCDCONF_PATH
-		$sudo $signal -a -s HUP pmcd
-	    fi
+	    [ -f $tmp.pmcd.conf ] && $sudo mv $tmp.pmcd.conf $PCP_PMCDCONF_PATH
+	    $sudo $signal -a -s HUP pmcd
 	fi
+    fi
 
-	rm -f $tmp.*
-	exit $status
+    rm -f $tmp.*
+    exit $status
 }
 
 trap "_cleanup" 0 1 2 3 15
@@ -96,6 +116,10 @@ unset ROOT
 cp $PCP_PMCDCONF_PATH $tmp.pmcd.conf
 cp $PCP_VAR_DIR/pmns/root $tmp.root
 
+if [ `pmprobe trivial.time 2>&1 | $PCP_AWK_PROG '{print $2}'` -lt 0 ]
+then
+    install_on_cleanup=false
+fi
 
 if $sudo make clobber >$tmp.out 2>&1
 then
@@ -106,9 +130,13 @@ else
     exit
 fi
 
-if [ `pmprobe trivial.time 2>&1 | $PCP_AWK_PROG '{print $2}'` -lt 0 ]
+if $sudo make >$tmp.out 2>&1
 then
-    install_on_cleanup=false
+    :
+else
+    cat $tmp.out
+    echo "Arrgh, make failed"
+    exit
 fi
 
 # start from a known starting point
