Mark 215 as notrun if appropriate hosts are not found/inaccessible.

diff --git a/215 b/215
--- a/215
+++ b/215
@@ -56,12 +56,17 @@ _filter()
 otherhost=`./getpmcdhosts -L -n 1 2>$tmp.out`
 if [ -z "$otherhost" ]
 then
-    cat $tmp.out
-    echo "Arrgh, cannot find a suitable remote pmcd host"
-    status=1
+    echo "Cannot find a suitable remote pmcd host" >$seq.notrun
+    echo "$seq: [not run] `cat $seq.notrun`"
     exit
 fi
 dname=`pmhostname | sed -e 's/^[a-z0-9]*\.//'`
+if ! grep sgi $dname >/dev/null
+then
+    echo "QA host is not in the SGI domain" >$seq.notrun
+    echo "$seq: [not run] `cat $seq.notrun`"
+    exit
+fi
 
 SOCKS_SERVER=$PCPQA_SOCKS_SERVER
 SOCKS_NS=`_host_to_ipaddr $SOCKS_SERVER`
