Switch all QA tests from using kill/kill to pmsignal.

diff --git a/374 b/374
--- a/374
+++ b/374
@@ -40,11 +40,11 @@ _speak_to_me()
     pid=''
     base=''
     cat <<'End-of-File' | ssh -q pcpqa@$host sh >$tmp.tmp 2>&1
-if [ -r /etc/pcp.env ]
+if [ -r $PCP_DIR/etc/pcp.env ]
 then
-    . /etc/pcp.env
+    . $PCP_DIR/etc/pcp.env
 else
-    echo "Error: unable to read /etc/pcp.env!" >&2
+    echo "Error: unable to read $PCP_DIR/etc/pcp.env!" >&2
     exit 1
 fi
 rm -f /tmp/$$.*
@@ -125,7 +125,7 @@ End-of-File
     #
     if [ ! -z "$host" ]
     then
-	ssh -q pcpqa@$host sh -c "kill -INT $pid; sleep 1; kill -KILL $pid; rm -f /tmp/$base.*" >/dev/null 2>&1
+	ssh -q pcpqa@$host sh -c "pmsignal -s TERM $pid; sleep 1; pmsignal -s KILL $pid; rm -f /tmp/$base.*" >/dev/null 2>&1
 	pid=''
 	base=''
     fi
@@ -138,7 +138,7 @@ _cleanup()
     then
 	if [ ! -z "$pid" -a ! -z "$base" -a ! -z "$host" ]
 	then
-	    ssh -q pcpqa@$host sh -c "kill -INT $pid; sleep 1; kill -KILL $pid; rm -f /tmp/$base.*" >/dev/null 2>&1
+	    ssh -q pcpqa@$host sh -c "pmsignal -s TERM $pid; sleep 1; pmsignal -s KILL $pid; rm -f /tmp/$base.*" >/dev/null 2>&1
 	    pid=''
 	    base=''
 	fi
