Add basic configure checks for verifying that LEX and YACC actually get set to something - if they don't the build is not going anywhere healthy, so bail out at configure time.

diff --git a/configure.in b/configure.in
--- a/configure.in
+++ b/configure.in
@@ -460,13 +460,39 @@ dnl check if user wants their own lex, yacc
 if test -z "$YACC"; then
     AC_PROG_YACC
 fi
-yacc=$YACC
+yacc=`which $YACC`
 AC_SUBST(yacc)
 if test -z "$LEX"; then
     AC_PROG_LEX
 fi
-lex=$LEX
+lex=`which $LEX`
 AC_SUBST(lex)
+
+dnl extra check for lex and yacc as these are often not installed
+AC_MSG_CHECKING([if yacc is executable])
+if test -x "$yacc"
+then
+    AC_MSG_RESULT([ yes])
+else
+    AC_MSG_RESULT([ no])
+    echo
+    echo "FATAL ERROR: did not find a valid yacc executable."
+    echo "You can either set \$YACC as the full path to yacc"
+    echo "in the environment, or install a yacc/bison package."
+    exit 1
+fi
+AC_MSG_CHECKING([if lex is executable])
+if test -x "$lex"
+then
+    AC_MSG_RESULT([ yes])
+else
+    AC_MSG_RESULT([ no])
+    echo
+    echo "FATAL ERROR: did not find a valid lex executable."
+    echo "You can either set \$LEX as the full path to lex"
+    echo "in the environment, or install a lex/flex package."
+    exit 1
+fi
 
 dnl check if user wants their own awk, sed and echo
 if test -z "$AWK"; then
