Merging upstream version 3.12.1.
Signed-off-by: Daniel Baumann <daniel.baumann@progress-linux.org>

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -700,6 +700,8 @@ fmt_uint64
 fmt_int64
 fmt_pid
 rdynamic_flag
+pcp_selinux_tracefs
+pcp_selinux_unreserved_port
 pcp_selinux_systemd_exec
 pcp_selinux_systemd_unit_file
 pcp_selinux_svirt_lxc_net
@@ -734,6 +736,9 @@ IB_LIBS
 PMDA_SYSTEMD
 SYSTEMD_LIBS
 SYSTEMD_CFLAGS
+HAVE_DEVMAPPER
+DEVMAPPER_LIBS
+DEVMAPPER_CFLAGS
 HAVE_NCURSES
 ncurses_LIBS
 ncurses_CFLAGS
@@ -819,6 +824,7 @@ have_python_libvirt
 have_python_requests
 have_python_setuptools
 have_python_jsonpointer
+have_python_OrderedDict
 pcp_python_prog
 have_python
 enable_python3
@@ -929,6 +935,7 @@ infodir
 docdir
 oldincludedir
 includedir
+runstatedir
 localstatedir
 sharedstatedir
 sysconfdir
@@ -1018,6 +1025,8 @@ avahi_LIBS
 SYSTEMD_SYSTEMUNITDIR
 ncurses_CFLAGS
 ncurses_LIBS
+DEVMAPPER_CFLAGS
+DEVMAPPER_LIBS
 SYSTEMD_CFLAGS
 SYSTEMD_LIBS
 papi_CFLAGS
@@ -1067,6 +1076,7 @@ datadir='${datarootdir}'
 sysconfdir='${prefix}/etc'
 sharedstatedir='${prefix}/com'
 localstatedir='${prefix}/var'
+runstatedir='${localstatedir}/run'
 includedir='${prefix}/include'
 oldincludedir='/usr/include'
 docdir='${datarootdir}/doc/${PACKAGE}'
@@ -1319,6 +1329,15 @@ do
   | -silent | --silent | --silen | --sile | --sil)
     silent=yes ;;
 
+  -runstatedir | --runstatedir | --runstatedi | --runstated \
+  | --runstate | --runstat | --runsta | --runst | --runs \
+  | --run | --ru | --r)
+    ac_prev=runstatedir ;;
+  -runstatedir=* | --runstatedir=* | --runstatedi=* | --runstated=* \
+  | --runstate=* | --runstat=* | --runsta=* | --runst=* | --runs=* \
+  | --run=* | --ru=* | --r=*)
+    runstatedir=$ac_optarg ;;
+
   -sbindir | --sbindir | --sbindi | --sbind | --sbin | --sbi | --sb)
     ac_prev=sbindir ;;
   -sbindir=* | --sbindir=* | --sbindi=* | --sbind=* | --sbin=* \
@@ -1456,7 +1475,7 @@ fi
 for ac_var in	exec_prefix prefix bindir sbindir libexecdir datarootdir \
 		datadir sysconfdir sharedstatedir localstatedir includedir \
 		oldincludedir docdir infodir htmldir dvidir pdfdir psdir \
-		libdir localedir mandir
+		libdir localedir mandir runstatedir
 do
   eval ac_val=\$$ac_var
   # Remove trailing slashes.
@@ -1609,6 +1628,7 @@ Fine tuning of the installation directories:
   --sysconfdir=DIR        read-only single-machine data [PREFIX/etc]
   --sharedstatedir=DIR    modifiable architecture-independent data [PREFIX/com]
   --localstatedir=DIR     modifiable single-machine data [PREFIX/var]
+  --runstatedir=DIR       modifiable per-process data [LOCALSTATEDIR/run]
   --libdir=DIR            object code libraries [EPREFIX/lib]
   --includedir=DIR        C header files [PREFIX/include]
   --oldincludedir=DIR     C header files for non-gcc [/usr/include]
@@ -1741,6 +1761,10 @@ Some influential environment variables:
               C compiler flags for ncurses, overriding pkg-config
   ncurses_LIBS
               linker flags for ncurses, overriding pkg-config
+  DEVMAPPER_CFLAGS
+              C compiler flags for DEVMAPPER, overriding pkg-config
+  DEVMAPPER_LIBS
+              linker flags for DEVMAPPER, overriding pkg-config
   SYSTEMD_CFLAGS
               C compiler flags for SYSTEMD, overriding pkg-config
   SYSTEMD_LIBS
@@ -7218,6 +7242,28 @@ fi
 
 
 
+ { $as_echo "$as_me:${as_lineno-$LINENO}: checking for Python module OrderedDict" >&5
+$as_echo_n "checking for Python module OrderedDict... " >&6; }
+    if test -n "from collections import OrderedDict"
+    then
+	txt="from collections import OrderedDict"
+    else
+	txt="import OrderedDict"
+    fi
+    $pcp_python_prog -c 'import sys;
+'"$txt" >>config.log 2>&1
+    if test "$?" = 0
+    then
+	{ $as_echo "$as_me:${as_lineno-$LINENO}: result: yes" >&5
+$as_echo "yes" >&6; }
+	eval have_python_OrderedDict=true
+    else
+	{ $as_echo "$as_me:${as_lineno-$LINENO}: result: no" >&5
+$as_echo "no" >&6; }
+	eval have_python_OrderedDict=false
+    fi
+
+
  { $as_echo "$as_me:${as_lineno-$LINENO}: checking for Python module jsonpointer" >&5
 $as_echo_n "checking for Python module jsonpointer... " >&6; }
     if test -n ""
@@ -7337,7 +7383,8 @@ if test "x$do_pmdajson" = "xyes"; then :
 fi
 if test "x$do_pmdajson" = "xcheck"; then :
 
-        $have_python_jsonpointer && $have_python_six && pmda_json=true
+        $have_python_jsonpointer && $have_python_six && \
+	$have_python_OrderedDict && pmda_json=true
 
 fi
 PMDA_JSON=$pmda_json
@@ -7602,10 +7649,7 @@ $as_echo_n "checking if the Prometheus PMDA should be included... " >&6; }
 pmda_prometheus=false
 if test "$have_python" = true
 then
-    if test "$have_python_requests" = true
-    then
-	pmda_prometheus=true
-    fi
+    $have_python_requests && $have_python_OrderedDict && pmda_prometheus=true
 fi
 PMDA_PROMETHEUS=$pmda_prometheus
 
@@ -7736,7 +7780,7 @@ fi
 enable_qt3d=false
 if test "x$do_qt3d" != "xno"; then :
 
-    if test -f /usr/include/Coin3/Inventor/Qt/SoQt.h
+    if test -f /usr/include/Coin3/Inventor/Qt/SoQt.h -o -f /usr/include/Inventor/Qt/SoQt.h
     then
 	enable_qt3d=$enable_qt
     elif test x"$do_qt3d" = x"yes"
@@ -10125,6 +10169,108 @@ HAVE_NCURSES=$have_ncurses
 
 
 pkg_failed=no
+{ $as_echo "$as_me:${as_lineno-$LINENO}: checking for DEVMAPPER" >&5
+$as_echo_n "checking for DEVMAPPER... " >&6; }
+
+if test -n "$DEVMAPPER_CFLAGS"; then
+    pkg_cv_DEVMAPPER_CFLAGS="$DEVMAPPER_CFLAGS"
+ elif test -n "$PKG_CONFIG"; then
+    if test -n "$PKG_CONFIG" && \
+    { { $as_echo "$as_me:${as_lineno-$LINENO}: \$PKG_CONFIG --exists --print-errors \"devmapper\""; } >&5
+  ($PKG_CONFIG --exists --print-errors "devmapper") 2>&5
+  ac_status=$?
+  $as_echo "$as_me:${as_lineno-$LINENO}: \$? = $ac_status" >&5
+  test $ac_status = 0; }; then
+  pkg_cv_DEVMAPPER_CFLAGS=`$PKG_CONFIG --cflags "devmapper" 2>/dev/null`
+		      test "x$?" != "x0" && pkg_failed=yes
+else
+  pkg_failed=yes
+fi
+ else
+    pkg_failed=untried
+fi
+if test -n "$DEVMAPPER_LIBS"; then
+    pkg_cv_DEVMAPPER_LIBS="$DEVMAPPER_LIBS"
+ elif test -n "$PKG_CONFIG"; then
+    if test -n "$PKG_CONFIG" && \
+    { { $as_echo "$as_me:${as_lineno-$LINENO}: \$PKG_CONFIG --exists --print-errors \"devmapper\""; } >&5
+  ($PKG_CONFIG --exists --print-errors "devmapper") 2>&5
+  ac_status=$?
+  $as_echo "$as_me:${as_lineno-$LINENO}: \$? = $ac_status" >&5
+  test $ac_status = 0; }; then
+  pkg_cv_DEVMAPPER_LIBS=`$PKG_CONFIG --libs "devmapper" 2>/dev/null`
+		      test "x$?" != "x0" && pkg_failed=yes
+else
+  pkg_failed=yes
+fi
+ else
+    pkg_failed=untried
+fi
+
+
+
+if test $pkg_failed = yes; then
+   	{ $as_echo "$as_me:${as_lineno-$LINENO}: result: no" >&5
+$as_echo "no" >&6; }
+
+if $PKG_CONFIG --atleast-pkgconfig-version 0.20; then
+        _pkg_short_errors_supported=yes
+else
+        _pkg_short_errors_supported=no
+fi
+        if test $_pkg_short_errors_supported = yes; then
+	        DEVMAPPER_PKG_ERRORS=`$PKG_CONFIG --short-errors --print-errors --cflags --libs "devmapper" 2>&1`
+        else
+	        DEVMAPPER_PKG_ERRORS=`$PKG_CONFIG --print-errors --cflags --libs "devmapper" 2>&1`
+        fi
+	# Put the nasty error message in config.log where it belongs
+	echo "$DEVMAPPER_PKG_ERRORS" >&5
+
+	have_devmapper=false
+elif test $pkg_failed = untried; then
+     	{ $as_echo "$as_me:${as_lineno-$LINENO}: result: no" >&5
+$as_echo "no" >&6; }
+	have_devmapper=false
+else
+	DEVMAPPER_CFLAGS=$pkg_cv_DEVMAPPER_CFLAGS
+	DEVMAPPER_LIBS=$pkg_cv_DEVMAPPER_LIBS
+        { $as_echo "$as_me:${as_lineno-$LINENO}: result: yes" >&5
+$as_echo "yes" >&6; }
+	have_devmapper=true
+fi
+if $have_devmapper
+then
+    { $as_echo "$as_me:${as_lineno-$LINENO}: checking for dm_stats_counter_t " >&5
+$as_echo_n "checking for dm_stats_counter_t ... " >&6; }
+    cat confdefs.h - <<_ACEOF >conftest.$ac_ext
+/* end confdefs.h.  */
+
+            #include <libdevmapper.h>
+
+int
+main ()
+{
+ dm_stats_counter_t ctr;
+  ;
+  return 0;
+}
+_ACEOF
+if ac_fn_c_try_compile "$LINENO"; then :
+  have_devmapper=true
+	{ $as_echo "$as_me:${as_lineno-$LINENO}: result: yes" >&5
+$as_echo "yes" >&6; }
+else
+  have_devmapper=false
+	{ $as_echo "$as_me:${as_lineno-$LINENO}: result: no" >&5
+$as_echo "no" >&6; }
+fi
+rm -f core conftest.err conftest.$ac_objext conftest.$ac_ext
+fi
+HAVE_DEVMAPPER=$have_devmapper
+
+
+
+pkg_failed=no
 { $as_echo "$as_me:${as_lineno-$LINENO}: checking for SYSTEMD" >&5
 $as_echo_n "checking for SYSTEMD... " >&6; }
 
@@ -11181,6 +11327,8 @@ pcp_selinux_docker_var_lib=false
 pcp_selinux_svirt_lxc_net=false
 pcp_selinux_systemd_unit_file=false
 pcp_selinux_systemd_exec=false
+pcp_selinux_tracefs=false
+pcp_selinux_unreserved_port=false
 if test "x$enable_selinux" != "xfalse"; then :
 
 for policy_file in /etc/selinux/targeted/policy/policy.*
@@ -11227,10 +11375,23 @@ do
 	then
 	    pcp_selinux_cap_userns_ptrace=true
 	fi
+	unreserved_port=`eval seinfo -t $policy_file | grep unreserved_port_t | awk '{ print $1 }'`
+	if test "x$unreserved_port" != "x"
+	then
+	    pcp_selinux_unreserved_port=true
+	fi
+	tracefs=`eval seinfo -t $policy_file | grep tracefs_t | awk '{ print $1 }'`
+	if test "x$tracefs" != "x"
+	then
+	    pcp_selinux_tracefs=true
+	fi
+
     fi
 done
 
 fi
+
+
 
 
 
@@ -12258,16 +12419,12 @@ End-of-File
 #include <string.h>
 int main()
 {
-    char buf[17];
-    int64_t bozo = 0x12345678abcdLL;
-    sprintf(buf, "%lx", bozo);
-    if (strcmp(buf, "12345678abcd") == 0)
-	printf("\"ld\"\n");
-    else {
-	sprintf(buf, "%llx", bozo);
-	if (strcmp(buf, "12345678abcd") == 0)
-	    printf("\"lld\"\n");
-    }
+/* logic copied from <inttypes.h> */
+#if __WORDSIZE == 64
+    printf("\"lld\"\n");
+#else
+    printf("\"ld\"\n");
+#endif
     return(0);
 }
 End-of-File
