configure.ac: rework the printf format for int64_t
Needs more strategies to get past the FreeBSD gcc, and also use
the standard C99 approach (via inttypes.h) in configure.ac, if
that works (it does not always work, so revert to the FreeBSD
large hammer method should that happen).

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -11234,7 +11234,7 @@ if test "$cross_compiling" = "yes"; then
 else
     cat <<End-of-File >conftest.c
 #include <stdio.h>
-main(int argc,  char **argv) { printf("%p", argv); exit(0); }
+int main(int argc,  char **argv) { printf("%p", argv); return(0); }
 End-of-File
     (eval $ac_compile) 2>&5
     (eval $ac_link) 2>&5
@@ -11385,18 +11385,65 @@ $as_echo "$fmt_pid" >&6; }
 
 rm -rf conftest.c conftest.debug
 
-{ $as_echo "$as_me:${as_lineno-$LINENO}: checking printf type for int64_t" >&5
-$as_echo_n "checking printf type for int64_t... " >&6; }
+{ $as_echo "$as_me:${as_lineno-$LINENO}: checking printf type for int64_t " >&5
+$as_echo_n "checking printf type for int64_t ... " >&6; }
 cat <<End-of-File >conftest.c
+#include <stdio.h>
 #include <stdint.h>
-int64_t bozo;
+#include <inttypes.h>
+int main()
+{
+    printf("\"%s\"\n", __PRI64_PREFIX "d");
+    return(0);
+}
 End-of-File
-_do_type
-fmt_int64="$_fmt"
+ans=''
+(eval $ac_link) 2>&5
+if test -x ./conftest
+then
+    ans=`./conftest`
+    echo "./conftest -> \"$ans\"" >&5
+fi
+if test -z "$ans"
+then
+    cat <<End-of-File >conftest.c
+#include <stdio.h>
+#include <stdint.h>
+#include <string.h>
+int main()
+{
+    char buf[17];
+    int64_t bozo = 0x12345678abcdLL;
+    sprintf(buf, "%lx", bozo);
+    if (strcmp(buf, "12345678abcd") == 0)
+	printf("\"ld\"\n");
+    else {
+	sprintf(buf, "%llx", bozo);
+	if (strcmp(buf, "12345678abcd") == 0)
+	    printf("\"lld\"\n");
+    }
+    return(0);
+}
+End-of-File
+    cp conftest.c /tmp/eek.c
+    (eval $ac_link) 2>&5
+    if test -x ./conftest
+    then
+	ans=`./conftest`
+	echo "./conftest -> \"$ans\"" >&5
+    fi
+fi
+if test -z "$ans"
+then
+    echo 'FATAL ERROR: Cannot determine printf format for int64_t type'
+    rm -rf conftest conftest.*
+    exit 1
+fi
+fmt_int64="$ans"
 { $as_echo "$as_me:${as_lineno-$LINENO}: result: $fmt_int64" >&5
 $as_echo "$fmt_int64" >&6; }
 
-rm -rf conftest.c conftest.debug
+rm -rf conftest.* conftest.debug conftest
 
 if test "$do_threads" = "check" -o "$do_threads" = "yes"
 then
