Remake configure script to pick up earlier Mac changes.

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -4714,8 +4714,8 @@ fi
 echo=$ECHO
 
 
-{ echo "$as_me:$LINENO: checking if echo uses -n or backslash-c to supress newlines" >&5
-echo $ECHO_N "checking if echo uses -n or backslash-c to supress newlines... $ECHO_C" >&6; }
+{ echo "$as_me:$LINENO: checking if echo uses -n or backslash-c to suppress newlines" >&5
+echo $ECHO_N "checking if echo uses -n or backslash-c to suppress newlines... $ECHO_C" >&6; }
 if ( $echo "testing\c"; $echo 1,2,3 ) | grep c >/dev/null
 then
   if ( $echo -n testing; $echo 1,2,3 ) | sed s/-n/xn/ | grep xn >/dev/null
@@ -8812,6 +8812,62 @@ eval "echo \"\$as_me:$LINENO: $ac_try_echo\"") >&5
        } && test -s conftest.$ac_objext; then
   cat >>confdefs.h <<\_ACEOF
 #define HAVE___PSINT_T 1
+_ACEOF
+ { echo "$as_me:$LINENO: result: yes" >&5
+echo "${ECHO_T}yes" >&6; }
+else
+  echo "$as_me: failed program was:" >&5
+sed 's/^/| /' conftest.$ac_ext >&5
+
+	{ echo "$as_me:$LINENO: result: no" >&5
+echo "${ECHO_T}no" >&6; }
+fi
+
+rm -f core conftest.err conftest.$ac_objext conftest.$ac_ext
+
+{ echo "$as_me:$LINENO: checking for ptrdiff_t " >&5
+echo $ECHO_N "checking for ptrdiff_t ... $ECHO_C" >&6; }
+cat >conftest.$ac_ext <<_ACEOF
+/* confdefs.h.  */
+_ACEOF
+cat confdefs.h >>conftest.$ac_ext
+cat >>conftest.$ac_ext <<_ACEOF
+/* end confdefs.h.  */
+
+    #include <stddef.h>
+    #ifdef HAVE_MALLOC_H
+    #include <malloc.h>
+    #endif
+
+int
+main ()
+{
+
+    ptrdiff_t  ptrdiff;
+
+  ;
+  return 0;
+}
+_ACEOF
+rm -f conftest.$ac_objext
+if { (ac_try="$ac_compile"
+case "(($ac_try" in
+  *\"* | *\`* | *\\*) ac_try_echo=\$ac_try;;
+  *) ac_try_echo=$ac_try;;
+esac
+eval "echo \"\$as_me:$LINENO: $ac_try_echo\"") >&5
+  (eval "$ac_compile") 2>conftest.er1
+  ac_status=$?
+  grep -v '^ *+' conftest.er1 >conftest.err
+  rm -f conftest.er1
+  cat conftest.err >&5
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); } && {
+	 test -z "$ac_c_werror_flag" ||
+	 test ! -s conftest.err
+       } && test -s conftest.$ac_objext; then
+  cat >>confdefs.h <<\_ACEOF
+#define HAVE_PTRDIFF_T 1
 _ACEOF
  { echo "$as_me:$LINENO: result: yes" >&5
 echo "${ECHO_T}yes" >&6; }
