getpmcdhosts etc rework -v pcp=2 support
Deprecate -v ipc=... and -v libpcp=... as we're not using these and there
is no easy way to determine these versions.

For -v pcp the =1 or =2 support has been changed to be <op><number>,
e.g. -v 'pcp>=2'.

All of this needed for PCP 3.0 where many of the QA tests need to be
run on hosts with PCP 2.x _or_ PCP 3.x

diff --git a/getpmcdhosts b/getpmcdhosts
--- a/getpmcdhosts
+++ b/getpmcdhosts
@@ -14,10 +14,11 @@
 . ./common.rc
 
 tmp=/tmp/$$
+tmp=`pwd`/tmp
+rm -rf $tmp.*
 status=1	# failure is the default!
 trap "rm -f $tmp.*; exit \$status" 0 1 2 3 15
 HOSTS=qa_hosts
-PROBE=pmprobe
 BRAND=pmbrand
 SSH_USER=pcpqa
 
@@ -34,18 +35,20 @@ Options:
 -h hostfile              name of host file, default is qa_hosts
 -l none|full|web         PCP collector license
 -L                       do not consider localhost
--m {metric}=|<|>{value}  satisfies metric value predicate
+-m {metric}<op>{value}   satisfies metric value predicate
 -n num                   match first num hosts
 -P                       return host running a primary pmlogger
 -p multi|single          multi or single processor
 -s system                operating system (uname -s)
--v {item}={ver}          version of item
+-v {item}<op>{ver}       version of item
 -V                       verbose diagnostics (see also -D)
 
 Legal item:
-ipc                 inter-process protocol
-libpcp              shared library
-pcp                 installation
+ipc                 inter-process protocol (deprecated)
+libpcp              shared library (deprecated)
+pcp                 PCP version installed
+
+<op> is one of =, >, >=, <, <= or !=
 
 Most options may be used together but not repeated.
 The environment variable QA_STS overrides the default host
@@ -55,7 +58,7 @@ file and -h
 }
 
 # 
-# _checkpmcdhost moomba _ 64 6.2 _ _ multi _ 2 _ _
+# _checkpmcdhost moomba _ 64 6.2 _ _ multi 2 _ _ _
 #
 # Parameters:
 #	host	name
@@ -65,12 +68,10 @@ file and -h
 #	license	none | full | web | _
 #	primary	true | false
 #	proc	multi | single | _
-#	ipc	1 | 2 | _
-#	libpcp	1 | 2 | _
 #	pcp	1 | 2 | _
-#	msg	true | false
-#	system  irix | linux
-#	endian	big | small
+#	msg	true | false | _
+#	system  irix | linux | _
+#	endian	big | small | _
 #
 
 _checkpmcdhost()
@@ -82,12 +83,10 @@ _checkpmcdhost()
     LICENSE=$5
     PRIMARY=$6
     PROC=$7
-    IPC=$8
-    LIBPCP=$9
-    PCP=${10}
-    MSG=${11}
-    SYSTEM=${12}
-    ENDIAN=${13}
+    PCP=$8
+    MSG=$9
+    SYSTEM=${10}
+    ENDIAN=${11}
     ERROR=0
 
     # check that host has a running pmcd
@@ -104,7 +103,7 @@ _checkpmcdhost()
     #
     if [ "$AGENT" != "_" ]
     then
-	if $PROBE -h $HOST -I pmcd.agent.type 2>/dev/null | grep $AGENT >/dev/null 2>&1
+	if pmprobe -h $HOST -I pmcd.agent.type 2>/dev/null | grep $AGENT >/dev/null 2>&1
 	then
 	    :
         else
@@ -120,7 +119,7 @@ _checkpmcdhost()
     then
         # only want 32 or 64 (not ia32 or n32 etc...)
         # if want to be specific then use "-m pmcd.simabi=ia32"
-	objfmt=`$PROBE -h $HOST -v pmcd.simabi 2>/dev/null \
+	objfmt=`pmprobe -h $HOST -v pmcd.simabi 2>/dev/null \
 		| sed -e 's/\"//g' \
 		| $PCP_AWK_PROG 'NF == 3 { print $3 }' \
 		| sed -e 's/x86-64/64/g' | sed -e 's/[a-zA-Z]//g' `
@@ -224,8 +223,8 @@ _checkpmcdhost()
     #
     if [ "$PROC" != "_" ]
     then
-	$VERBOSE && echo "+ $PROBE -h $HOST -v hinv.ncpu | sed ..."
-	ncpu=`$PROBE -h $HOST -v hinv.ncpu 2>/dev/null \
+	$VERBOSE && echo "+ pmprobe -h $HOST -v hinv.ncpu | sed ..."
+	ncpu=`pmprobe -h $HOST -v hinv.ncpu 2>/dev/null \
 		| sed -e 's/\"//g' \
 		| $PCP_AWK_PROG 'NF == 3 && $3 ~ /^[0-9][0-9]*$/ { print $3 }'`
 	$VERBOSE && echo "-> $ncpu"
@@ -234,7 +233,7 @@ _checkpmcdhost()
 	then
 	    if $MSG
 	    then
-		echo "$HOST: Unknown number of processors, pmprobe -> `$PROBE -h $HOST -v hinv.ncpu 2>&1`" >&2
+		echo "$HOST: Unknown number of processors, pmprobe -> `pmprobe -h $HOST -v hinv.ncpu 2>&1`" >&2
 	    fi
 	    return 1
 	fi
@@ -275,134 +274,167 @@ _checkpmcdhost()
 	esac
     fi
 
-    # The remainding tests are fixed on the PCP version
-    # This information should be updated when required
+    # check the item value pairs
     #
-
-    if [ "$PCP" != "_" -o "$IPC" != "_" -o "$LIBPCP" != "_" ]
+    if [ -s "$tmp.items" ]
     then
-    	probe=`$PROBE -h $HOST -v pmcd.version 2>/dev/null`
-	if echo "$probe" | fgrep -s pmprobe:
-	then
-	    $MSG && echo "$HOST: Unable to pmprobe" >&2
-	    return 1
-	fi
-
-        version=`echo $probe | $PCP_AWK_PROG -F'"' '{ print $2 }' | sed -e 's/\..*//'`
-
-	# check pcp version
-	#
-	if [ "$PCP" != "_" -a "$PCP" != "$version" ]
-	then
-	    $MSG && echo "$HOST: PCP Version $PCP != $version" >&2
-	    return 1
-        fi
-
-    	# check IPC protocol
-    	#
-    	if [ "$IPC" != "_" ]
-    	then
-	    case "$version"
+	cat $tmp.items \
+	| while read item op value
+	do
+	    case "$item"
 	    in
-	    	1)
-		    if [ "$IPC" != 1 ]
+		pcp)
+		    if pmprobe -h $HOST -v pmcd.version >$tmp.probe 2>$tmp.err
 		    then
-		    	$MSG && echo "$HOST: IPC $IPC not supported" >&2
-		    	return 1
+			:
+		    else
+			rm -f $tmp.probe
 		    fi
 		    ;;
-	    	2)
-		    if [ "$IPC" != 1 -a "$IPC" != 2 ]
-		    then
-		     	$MSG && echo "$HOST: IPC $IPC not supported" >&2
-		    	return 1
-		    fi
+		*)
+		    echo "$0: INTERNAL BOTCH item=$item not expected here!"
+		    exit 1
 		    ;;
-		esac
-    	fi
-
-    	# check libpcp version
-    	#
-     	if [ "$LIBPCP" != "_" ]
-    	then
-	    case "$version"
-	    in
-	    	1)
-		    if [ "$LIBPCP" != 1 ]
-		    then
-		    	$MSG && echo "$HOST: libpcp $LIBPCP not supported" >&2
-		    	return 1
-		    fi
-		    ;;
-	    	2)
-		    if [ "$LIBPCP" != 1 -a "$LIBPCP" != 2 ]
-		    then
-		    	$MSG && echo "$HOST: libpcp $LIBPCP not supported" >&2
-		    	return 1
-		    fi
-		    ;;
-		esac
-    	fi
+	    esac
+	    if [ -s $tmp.probe ]
+	    then
+		satisfies=`sed -e 's/"//g' $tmp.probe \
+			   | $PCP_AWK_PROG '
+BEGIN	{ op = "'"$op"'"; value="'"$value"'" }
+NF >=3	{ if ( $2 < 0 ) {
+		print "0";
+		exit;
+	    }
+	    # got a value
+	    if (op == "=") {
+		if ($3 == value)
+		    print "1";
+		else
+		    print "0";
+	    } 
+	    else if (op == "<") {
+		if ($3 < value)
+		    print "1";
+		else
+		    print "0";
+	    }
+	    else if (op == "<=") {
+		if ($3 <= value)
+		    print "1";
+		else
+		    print "0";
+	    }
+	    else if (op == ">") {
+		if ($3 > value)
+		    print "1";
+		else
+		    print "0";
+	    }
+	    else if (op == ">=") {
+		if ($3 >= value)
+		    print "1";
+		else
+		    print "0";
+	    }
+	    else if (op == "!=") {
+		if ($3 != value)
+		    print "1";
+		else
+		    print "0";
+	    }
+	    else {
+		    print "2";
+	    }
+	    exit;
+	}
+	{ print "0" }'`
+		if [ $satisfies -ne 1 ]
+		then
+		    $MSG && echo "$HOST: does not satisfy predicate $metric $op $value" >&2
+		    return 1
+		fi
+	    else
+		$MSG && echo "$HOST: pmprobe failed `cat $tmp.errs`" >&2
+		return 1
+	    fi
+	done
+	[ $? -eq 1 ] && return 1
     fi
 
     # check the metric value pairs
+    #
     if [ -s "$tmp.metrics" ]
     then
-    cat $tmp.metrics \
-    | while read metric op value
-    do
-        if pmprobe -h $HOST -v $metric >$tmp.probe 2>&1
-        then
-	    satisfies=`sed -e 's/"//g' $tmp.probe \
-		        | $PCP_AWK_PROG '
-BEGIN			{ op = "'"$op"'"; value="'"$value"'" }
-
-                NF >=3 {
-		    if ( $2 < 0 ) {
-			print "0";
-			exit;
-		    }
-		    # got a value
-		    if (op == "=") {
-			if ($3 == value)
-			    print "1";
-			else
-			    print "0";
-		    } 
-		    else if (op == "<") {
-			if ($3 < value)
-			    print "1";
-			else
-			    print "0";
-		    }
-		    else if (op == ">") {
-			if ($3 > value)
-			    print "1";
-			else
-			    print "0";
-		    }
-		    else {
-			    print "2";
-		    }
-		    exit;
-		}
-		{ print "0" }'`
-	    if [ $satisfies -ne 1 ]
+	cat $tmp.metrics \
+	| while read metric op value
+	do
+	    if pmprobe -h $HOST -v $metric >$tmp.probe 2>$tmp.errs
 	    then
-		$MSG && echo "$HOST: does not satisfy predicate $metric $op $value" >&2
+		satisfies=`sed -e 's/"//g' $tmp.probe \
+			   | $PCP_AWK_PROG '
+BEGIN	{ op = "'"$op"'"; value="'"$value"'" }
+NF >=3	{ if ( $2 < 0 ) {
+		print "0";
+		exit;
+	    }
+	    # got a value
+	    if (op == "=") {
+		if ($3 == value)
+		    print "1";
+		else
+		    print "0";
+	    } 
+	    else if (op == "<") {
+		if ($3 < value)
+		    print "1";
+		else
+		    print "0";
+	    }
+	    else if (op == "<=") {
+		if ($3 <= value)
+		    print "1";
+		else
+		    print "0";
+	    }
+	    else if (op == ">") {
+		if ($3 > value)
+		    print "1";
+		else
+		    print "0";
+	    }
+	    else if (op == ">=") {
+		if ($3 >= value)
+		    print "1";
+		else
+		    print "0";
+	    }
+	    else if (op == "!=") {
+		if ($3 != value)
+		    print "1";
+		else
+		    print "0";
+	    }
+	    else {
+		    print "2";
+	    }
+	    exit;
+	}
+	{ print "0" }'`
+		if [ $satisfies -ne 1 ]
+		then
+		    $MSG && echo "$HOST: does not satisfy predicate $metric $op $value" >&2
+		    return 1
+		fi
+	    else
+		$MSG && echo "$HOST: pmprobe failed `cat $tmp.errs`" >&2
 		return 1
 	    fi
-	else
-	    $MSG && echo "$HOST: does not satisfy predicate $metric $op $value" >&2
-	    return 1
-        fi
-    done
-    [ $? -eq 1 ] && return 1
+	done
+	[ $? -eq 1 ] && return 1
     fi
 
     return 0
 }
-
 
 # Go thru table of hosts and see which meet the
 # given criteria and return either the first one
@@ -415,8 +447,6 @@ BINFMT="_"
 IRIX="_"
 LICENSE="_"
 PROC="_"
-IPC="_"
-LIBPCP="_"
 PCP="_"
 SYSTEM="_"
 ENDIAN="_"
@@ -453,6 +483,7 @@ do
 		*)
 		    echo "$0: Illegal endianess $ENDIAN" >&2
 		    _usage
+		    #NOTREACHED
 		    ;;
 	    esac
 	    ;;
@@ -460,8 +491,9 @@ do
 	    HOSTS=$OPTARG
 	    if [ ! -f $OPTARG ]
 	    then
-	        echo "$0: Cannot open $OPTARG" >&2
+	        echo "$0: Cannot open hostfile $OPTARG" >&2
 		_usage
+		#NOTREACHED
 	    fi
 	    ;;
 	i)
@@ -474,14 +506,19 @@ do
 	    LOCAL=true
 	    ;;
 	m)
-	    metric=`echo $OPTARG | sed -e 's/[ 	]*//' -e 's/[=<>].*//'`
-	    value=`echo $OPTARG | sed -e 's/[ 	]*//' -e 's/.*[=<>]//'`
+	    metric=`echo $OPTARG | sed -e 's/[ 	]*//' -e 's/[=<>!].*//'`
+	    value=`echo $OPTARG | sed -e 's/[ 	]*//' -e 's/.*[=<>!]//'`
 	    op=`echo $OPTARG | sed -e 's/[ 	]*//' -e "s/$metric//" -e "s/$value//"`
-	    if [ "X$op" != "X<" -a "X$op" != "X>" -a "X$op" != "X=" ]
-	    then 
-		echo "$0: Illegal metric argument: $OPTARG" >&2
-		_usage
-	    fi
+	    case "$op"
+	    in
+		'='|'<'|'<='|'>'|'>='|'!=')
+		    ;;
+		*)
+		    echo "$0: Illegal metric argument: $OPTARG" >&2
+		    _usage
+		    #NOTREACHED
+		    ;;
+	    esac
 	    echo "$metric $op $value" >> $tmp.metrics
 	    $MSG && echo "---tmp.metrics---" >&2
 	    $MSG && cat $tmp.metrics >&2
@@ -504,28 +541,39 @@ do
 	    SYSTEM=$OPTARG
 	    ;;
 	v)
-	    ITEM=`echo $OPTARG | sed -e 's/[ 	]*//' -e 's/=.*//'`
-	    VERS=`echo $OPTARG | sed -e 's/[ 	]*//' -e 's/.*=//'`
-	    case "$ITEM"
+	    item=`echo $OPTARG | sed -e 's/[ 	]*//' -e 's/[=<>!].*//'`
+	    value=`echo $OPTARG | sed -e 's/[ 	]*//' -e 's/.*[=<>!]//'`
+	    op=`echo $OPTARG | sed -e 's/[ 	]*//' -e "s/$item//" -e "s/$value//"`
+	    case "$item"
 	    in
-		"ipc"|"IPC")
-		    IPC=$VERS
+		"ipc"|"libpcp")
+		    echo "$0: Deprecated item \"$item\", ignored" >&2
+		    continue
 		    ;;
-		"libpcp"|"LIBPCP")
-		    LIBPCP=$VERS
-		    ;;
-		"pcp"|"PCP")
-		    PCP=$VERS
+		"pcp")
+		    value=`echo "$value" | sed -e 's/\./ /g' | $PCP_AWK_PROG '
+NF==1	{ print $0 ".0.0" }
+NF==2	{ print $0 ".0" }
+NF>2	{ print $0 }' | sed -e 's/ /./g'`
 		    ;;
 		*)
-		    echo "$0: Illegal item $ITEM" >&2
+		    echo "$0: Illegal item $item" >&2
 		    _usage
+		    #NOTREACHED
 	    esac
-	    if [ "$VERS" -ne 1 -a "$VERS" -ne 2 ]
-	    then
-	        echo "$0: Illegal value $VERS for item $ITEM, expected 1 or 2" >&2
-		_usage
-	    fi
+	    case "$op"
+	    in
+		'='|'<'|'<='|'>'|'>='|'!=')
+		    ;;
+		*)
+		    echo "$0: Illegal metric argument: $OPTARG" >&2
+		    _usage
+		    #NOTREACHED
+		    ;;
+	    esac
+	    echo "$item $op $value" >> $tmp.items
+	    $MSG && echo "---tmp.items---" >&2
+	    $MSG && cat $tmp.items >&2
 	    ;;
 
 	V)
@@ -534,9 +582,15 @@ do
 
 	*)
 	    _usage
+	    #NOTREACHED
 	    ;;
     esac
 done
+if [ $# -ne `expr $OPTIND - 1` ]
+then
+    _usage
+    #NOTREACHED
+fi
 	
 # Verify the options
 #
@@ -612,7 +666,7 @@ $MSG && ( echo "Checking hosts:"; echo "$QA_HOSTS"; echo ) >&2
 i=0
 for HOST in $QA_HOSTS
 do
-    if _checkpmcdhost $HOST $AGENT $BINFMT $IRIX $LICENSE $PRIMARY $PROC $IPC $LIBPCP $PCP $MSG $SYSTEM $ENDIAN
+    if _checkpmcdhost $HOST $AGENT $BINFMT $IRIX $LICENSE $PRIMARY $PROC $PCP $MSG $SYSTEM $ENDIAN
     then
 	if $LIST
 	then
