First part of the changes to replace rsh/rcp with ssh/scp.

diff --git a/getpmcdhosts b/getpmcdhosts
--- a/getpmcdhosts
+++ b/getpmcdhosts
@@ -21,7 +21,7 @@ trap "rm -f $tmp.*; exit \$status" 0 1 2 3 15
 HOSTS=qa_hosts
 PROBE=pmprobe
 BRAND=pmbrand
-RSH_USER=pcpqa
+SSH_USER=pcpqa
 
 _usage()
 {
@@ -134,17 +134,17 @@ _checkpmcdhost()
 	fi
     fi
 
-    # check that rsh works for host -l user
+    # check that ssh works for user@host
     #
     if [ "$LICENSE" != "_" -o "$IRIX" != "_" ]
     then
-	if rsh $HOST -l $RSH_USER date 1>/dev/null 2>&1
+	if ssh $SSH_USER@$HOST date 1>/dev/null 2>&1
 	then
 	    :
 	else
 	    if $MSG
 	    then
-		echo "$0: WARNING: \"rsh $HOST\" -l $RSH_USER failed" >&2
+		echo "$0: WARNING: \"ssh $SSH_USER@$HOST\" failed" >&2
 		return 1
 	    fi
 	fi
@@ -154,7 +154,7 @@ _checkpmcdhost()
     #
     if [ "$SYSTEM" != "_" ]
     then
-	osname=`rsh $HOST -l $RSH_USER uname -s`
+	osname=`ssh $SSH_USER@$HOST uname -s`
         if echo $osname | grep -i $SYSTEM >/dev/null 2>&1 
         then
 	    :
@@ -169,7 +169,7 @@ _checkpmcdhost()
     #
     if [ "$IRIX" != "_" ]
     then
-	irixrev=`rsh $HOST -l $RSH_USER uname -r | sed -e 's/-ALPHA.*//' -e 's/ .*//'`
+	irixrev=`ssh $SSH_USER@$HOST uname -r | sed -e 's/-ALPHA.*//' -e 's/ .*//'`
 	if [ "$irixrev" != $IRIX ]
 	then
 	    $MSG && echo "$HOST: IRIX $IRIX != $irixrev" >&2
@@ -181,8 +181,8 @@ _checkpmcdhost()
     #
     if [ "$LICENSE" != "_" ]
     then
-	$VERBOSE && echo "+ rsh $HOST -l $RSH_USER $BRAND -l"
-	license=`rsh $HOST -l $RSH_USER "$BRAND -l" 2>&1`
+	$VERBOSE && echo "+ ssh $SSH_USER@$HOST $BRAND -l"
+	license=`ssh $SSH_USER@$HOST "$BRAND -l" 2>&1`
 	$VERBOSE && echo "-> $license"
 	if [ "$LICENSE" = "full" ]
 	then
@@ -255,8 +255,8 @@ _checkpmcdhost()
     #
     if [ "$ENDIAN" != "_" ]
     then
-	$VERBOSE && echo "+ echo a | rsh $HOST -l $RSH_USER od -x"
-	check=`echo a | rsh $HOST -l $RSH_USER "od -x" 2>&1 | sed -e 's/^0[^ ]* *//' -e '/^$/d'`
+	$VERBOSE && echo "+ echo a | ssh $SSH_USER@$HOST od -x"
+	check=`echo a | ssh $SSH_USER@$HOST "od -x" 2>&1 | sed -e 's/^0[^ ]* *//' -e '/^$/d'`
 	$VERBOSE && echo "-> $check"
 	case "$check"
 	in
diff --git a/src-oss/grind-tools b/src-oss/grind-tools
--- a/src-oss/grind-tools
+++ b/src-oss/grind-tools
@@ -4,12 +4,12 @@
 
 _usage()
 {
-    echo "Usage: $0 [-v] [-a archive] [-h host] metricspec [...]"
-    echo
-    echo "metricspec one of the forms:"
-    echo "    metric-name"
-    echo "    metric-name[instance]"
-    exit 1
+echo "Usage: $0 [-v] [-a archive] [-h host] metricspec [...]"
+echo
+echo "metricspec one of the forms:"
+echo "    metric-name"
+echo "    metric-name[instance]"
+exit 1
 }
 
 # Get standard environment
@@ -26,58 +26,58 @@ host=localhost
 archive=""
 while getopts "a:h:v" c
 do
-    case "$c"
-    in
-	a)
-	    src="-a $OPTARG"
-	    archive=$OPTARG
-	    host=""
-	    ;;
-	h)
-	    src="-h $OPTARG"
-	    archive=""
-	    host=$OPTARG
-	    ;;
-	v)
-	    $verbose && very_verbose=true
-	    verbose=true
-	    ;;
-	*)
-	    _usage
-	    # NOTREACHED
-	    ;;
-    esac
+case "$c"
+in
+a)
+    src="-a $OPTARG"
+    archive=$OPTARG
+    host=""
+    ;;
+h)
+    src="-h $OPTARG"
+    archive=""
+    host=$OPTARG
+    ;;
+v)
+    $verbose && very_verbose=true
+    verbose=true
+    ;;
+*)
+    _usage
+    # NOTREACHED
+    ;;
+esac
 done
 shift `expr $OPTIND - 1`
 
 if [ $# -lt 1 ]
 then
-    _usage
-    # NOTREACHHED
+_usage
+# NOTREACHHED
 fi
 
 for arg
 do
-    case "$arg"
-    in
-	*[*)
-	    echo "$arg" >>$tmp.all
-	    ;;
-	*)
-	    pmprobe -I $src $arg \
-	    | sed  \
-		-e 's/ "/ /' \
-		-e 's/" "/ /g' \
-		-e 's/"$//' \
-		-e 's/ /\
+case "$arg"
+in
+*[*)
+    echo "$arg" >>$tmp.all
+    ;;
+*)
+    pmprobe -I $src $arg \
+    | sed  \
+	-e 's/ "/ /' \
+	-e 's/" "/ /g' \
+	-e 's/"$//' \
+	-e 's/ /\
 /g' \
-	    | sed -e '1,2d' \
-	    | while read inst
-	    do
-		echo "$arg[$inst]" >>$tmp.all
-	    done
-	    ;;
-    esac
+    | sed -e '1,2d' \
+    | while read inst
+    do
+	echo "$arg[$inst]" >>$tmp.all
+    done
+    ;;
+esac
 done
 
 sed <$tmp.all -e 's/\[.*//' \
@@ -90,84 +90,84 @@ sed <$tmp.all -e 's/\[.*//' \
 # pmie
 #
 sed <$tmp.all >$tmp.config \
-    -e "s/\[/ #'/" \
-    -e "s/]/'/" \
-    -e 's/$/+/' \
-    -e '$s/$/1;/'
+-e "s/\[/ #'/" \
+-e "s/]/'/" \
+-e 's/$/+/' \
+-e '$s/$/1;/'
 $very_verbose && echo "pmie config ..." && cat $tmp.config
 if pmie $src -c $tmp.config -C
 then
-    $verbose && echo "pmie OK"
+$verbose && echo "pmie OK"
 else
-    echo "pmie FAILED"
-    echo "pmie config:"
-    cat $tmp.config
-    status=1
+echo "pmie FAILED"
+echo "pmie config:"
+cat $tmp.config
+status=1
 fi
 
 # pmval
 #
 sed -e 's/]//' -e 's/\[/ /' <$tmp.all \
-    | $PCP_AWK_PROG '
+| $PCP_AWK_PROG '
 BEGIN		{ printf "pmval -s 2 -t 1sec '"$src"' -i " }
 $1 != metric	{ if (NR > 1) {
-		    print " " metric
-		    printf "pmval -s 2 -t 1sec '"$src"' -i "
-		  }
-		  metric = $1
-		}
+	    print " " metric
+	    printf "pmval -s 2 -t 1sec '"$src"' -i "
+	  }
+	  metric = $1
+	}
 NR > 1		{ printf "," }
-		{ printf $2 }
+	{ printf $2 }
 END		{ print " " metric
-		}' \
+	}' \
 | sed -e "s/-i /-i '/" -e "s/ [^ ]*\$/'&/" >$tmp.config
 $very_verbose && echo "pmval cmd ..." && cat $tmp.config
 cat $tmp.config | sh >$tmp.out 2>&1
 if grep '^samples: *2$' $tmp.out >/dev/null
 then
-    $verbose && echo "pmval OK"
+$verbose && echo "pmval OK"
 else
-    echo "pmval FAILED"
-    echo "pmval cmd:"
-    cat $tmp.config
-    cat $tmp.out
-    status=1
+echo "pmval FAILED"
+echo "pmval cmd:"
+cat $tmp.config
+cat $tmp.out
+status=1
 fi
 
 # pmdumptext - simple with -a or -h
 #
 sed -e 's/]//' -e 's/\[/ /' <$tmp.all \
-    | $PCP_AWK_PROG '
+| $PCP_AWK_PROG '
 BEGIN		{ printf "pmdumptext -s 2 -t 1sec '"$src"'" }
 $1 != metric	{ if (NR > 1) {
-		    print "]"
-		    printf "pmdumptext -s 2 -t 1sec '"$src"'"
-		  }
-		  metric = $1
-		  printf " %s[",metric
-		  first = 1
-		}
-		{ if (first) {
-		    printf "%s",$2
-		    first = 0
-		  }
-		  else
-		    printf ",%s",$2
-		}
+	    print "]"
+	    printf "pmdumptext -s 2 -t 1sec '"$src"'"
+	  }
+	  metric = $1
+	  printf " %s[",metric
+	  first = 1
+	}
+	{ if (first) {
+	    printf "%s",$2
+	    first = 0
+	  }
+	  else
+	    printf ",%s",$2
+	}
 END		{ print "]"
-		}' >$tmp.config
+	}' >$tmp.config
 $very_verbose && echo "pmdumptext cmd ..." && cat $tmp.config
 cat $tmp.config | sh >$tmp.out 2>&1
 ok=`grep '^[A-Z][a-z][a-z] [A-Z][a-z][a-z]' $tmp.out | wc -l | sed -e 's/ //g'`
 if [ "$ok" -eq 2 ]
 then
-    $verbose && echo "pmdumptext (simple) OK"
+$verbose && echo "pmdumptext (simple) OK"
 else
-    echo "pmdumptext (simple) FAILED"
-    echo "pmdumptext cmd:"
-    cat $tmp.config
-    cat $tmp.out
-    status=1
+echo "pmdumptext (simple) FAILED"
+echo "pmdumptext cmd:"
+cat $tmp.config
+cat $tmp.out
+status=1
 fi
 
 # pmdumptext - extended notation ...
@@ -176,52 +176,52 @@ fi
 #
 if [ -n "$host" ]
 then
-    pfx="$host:"
+pfx="$host:"
 else
-    pfx="$archive/"
+pfx="$archive/"
 fi
 sed -e 's/]//' -e 's/\[/ /' <$tmp.all \
-    | $PCP_AWK_PROG '
+| $PCP_AWK_PROG '
 BEGIN		{ printf "pmdumptext -s 2 -t 1sec" }
 $1 != metric	{ metric = $1
-		  first = 1
-		  if (NR > 1) printf "]"
-		}
-		{ if (first) {
-		    printf " %s%s[%s","'"$pfx"'",metric,$2
-		    first = 0
-		  }
-		  else
-		    printf ",%s",$2
-		}
+	  first = 1
+	  if (NR > 1) printf "]"
+	}
+	{ if (first) {
+	    printf " %s%s[%s","'"$pfx"'",metric,$2
+	    first = 0
+	  }
+	  else
+	    printf ",%s",$2
+	}
 END		{ print "]" }' >$tmp.config
 $very_verbose && echo "pmdumptext cmd ..." && cat $tmp.config
 cat $tmp.config | sh >$tmp.out 2>&1
 ok=`grep '^[A-Z][a-z][a-z] [A-Z][a-z][a-z]' $tmp.out | wc -l | sed -e 's/ //g'`
 if [ "$ok" -eq 2 ]
 then
-    $verbose && echo "pmdumptext (extended) OK"
+$verbose && echo "pmdumptext (extended) OK"
 else
-    echo "pmdumptext (extended) FAILED"
-    echo "pmdumptext cmd:"
-    cat $tmp.config
-    cat $tmp.out
-    status=1
+echo "pmdumptext (extended) FAILED"
+echo "pmdumptext cmd:"
+cat $tmp.config
+cat $tmp.out
+status=1
 fi
 
 # pmchart
 #
 if which pmchart >/dev/null 2>&1
 then
-    echo "#pmchart" >$tmp.config
-    echo "Version 2.0 host dynamic" >>$tmp.config
-    echo "Chart Title "test" Style line" >>$tmp.config
-    sed <$tmp.all >>$tmp.config \
-	-e 's/]//' \
-	-e 's/\[/ Instance /' \
-	-e 's/^/  Plot Color #-cycle Host * Metric /'
-    $very_verbose && echo "pmchart config ..." && cat $tmp.config
-    if pmchart -C -c $tmp.config $src
+echo "#pmchart" >$tmp.config
+echo "Version 2.0 host dynamic" >>$tmp.config
+echo "Chart Title "test" Style line" >>$tmp.config
+sed <$tmp.all >>$tmp.config \
+-e 's/]//' \
+-e 's/\[/ Instance /' \
+-e 's/^/  Plot Color #-cycle Host * Metric /'
+$very_verbose && echo "pmchart config ..." && cat $tmp.config
+if pmchart -C -c $tmp.config $src
     then
 	$verbose && echo "pmchart OK"
     else
@@ -313,12 +313,12 @@ fi
 
 # pmgadgets
 #
-if which pmgadgets >/dev/null 2>&1
+if [ -z "$host" ]
 then
-    if [ -z "$host" ]
+    echo "pmgadgets skipped, source is an archive"
+else
+    if which pmgadgets >/dev/null 2>&1
     then
-	echo "pmgadgets skipped, source is an archive"
-    else
 	cat <<End-of-File >$tmp.config
 pmgadgets 1 "foo" "bar"
 _legend l (
@@ -344,9 +344,9 @@ End-of-File
 	    cat $tmp.config
 	    status=1
 	fi
+    else
+	echo "pmgadgets skipped, no binary installed"
     fi
-else
-    echo "pmgadgets skipped, no binary installed"
 fi
 
 # pmlogger
