Makepkgs: fix for Debian build (and Qt packaging failure in CI)
We run configure twice for a Debian build.  This change involves the
first invocation where we were not correctly picking the environment
variables from debian/rules that need to be set to make the first
configure behave like the second one (that is run inside the Debian
package building ecosystem).  The commit fixes that.

After the first configure and before the second configure we run
debian/GNUmakefile create debian/control that is used in the real
build.

The specific problem was that
	configure_tools = export DEBUG=-DNDEBUG QT_SELECT=5;
was not in play for the first configure, critically QT_SELECT=5 was
not set.  We now roll the dice ... and depending on what Qt version(s)
you have installed, we may or may not set ENABLE_QT that drives the
whole packaging of pmchart, pmtime, pmdumptext, et al.

In the QA Farm I have Qt4 and Qt5 on my Debian 10 system (vm11)
... I win.

In CI, the Debian 10 system has only Qt5 installed ... we
all lose.

diff --git a/Makepkgs b/Makepkgs
--- a/Makepkgs
+++ b/Makepkgs
@@ -218,6 +218,7 @@ then
     exit 1
 fi
 
+configenv=''
 if $dodeb
 then
     # On Debian-based platforms, the debian/rules file already captures 
@@ -558,13 +559,25 @@ debian_build()
 	echo "Botch: cannot find debian/rules"
 	exit 1
     fi
-    debian_opts=`sed -n <debian/rules -e '/^configure_paths/s/^[^=]*= *//p'`
-    if [ -z "$debian_opts" ]
+    debian_paths=`sed -n <debian/rules -e '/^configure_paths/s/^[^=]*= *//p'`
+    if [ -z "$debian_paths" ]
     then
 	echo "Botch: cannot get config options from configure_paths in debian/rules"
 	exit 1
     fi
-    configopts="$debian_opts $configopts"
+    configopts="$debian_paths $configopts"
+    debian_env=`sed -n <debian/rules -e '/^configure_tools/{
+s/^[^=]*= *//
+s/export *//
+s/;//
+p
+}'`
+    if [ -z "$debian_env" ]
+    then
+	echo "Botch: cannot get env settings from configure_tools in debian/rules"
+	exit 1
+    fi
+    configenv="$debian_env"
     configure_pcp
     prepare_debian_control
     sanity_check_settings
@@ -595,7 +608,8 @@ prepare_build()
 configure_pcp()
 {
     echo
-    echo "== Configuring pcp, log is in $LOGDIR/pcp ($configopts)"
+    echo "== Configuring pcp, log is in $LOGDIR/pcp $configenv ($configopts)"
+    [ -n "$configenv" ] && export $configenv
 
     rm -f $tmp/failed
     if $verbose
