Makepkgs and debian/control: redo the generation of debian control
The (new) debian/pre-build script knows how to construct the correct
control file for a pure Debian build (no Makepkgs) from control.master
and any other control.foo files that are expected to be in a pure
Debian build.

Makepkgs uses debian/pre-build before adding debian/control to the
tarball manifest.

debian/control is no longer in the git tree ... changes should be
made to the control.foo files used to recreate debian/control.

Note that for a Makepkgs build things have not changed, namely the
debian/GNUmakefile creates debian/control based on guidance from
configure and friends.

diff --git a/Makepkgs b/Makepkgs
--- a/Makepkgs
+++ b/Makepkgs
@@ -410,7 +410,23 @@ src_tar_build()
 	git archive --format=tar --prefix=$source/ HEAD | $ZIP > $SRCTAR
     else
 	# build git file list and make tarball by hand to pick up any changes
+	#
 	git ls-files > .gitcensus
+
+	# but first ensure a "build everything" debian/control has been
+	# recreated
+	#
+	cd debian
+	if ./pre-build
+	then
+	    :
+	else
+	    echo "Error: debian/pre-build failed when creating debian/control"
+	    exit 1
+	fi
+	cd ..
+	echo "debian/control" >> .gitcensus
+
 	$TAR -cz --transform="s,^,$source/," --files-from=.gitcensus \
 		--file=$SRCTAR 
 	rm .gitcensus
