qa: changes for CI when run in a container
qa/admin/allow-pmlc-access
    in _getnetworkaddr() host `hostname` may report
    Host 2fc9e9e9c5db not found: 3(NXDOMAIN)
    instead of
    bozo.localdomain has address 192.168.20.100
    so use ip(1) to try and get the ip addr and netmask if there is
    one ethernet interface

qa/admin/check-vm
    _getnetworkaddr() here is a copy of the one in allow-pmlc-access

qa/043
    Run admin/allow-pmlc-access to make sure the primary pmlogger
    config file allows all pmlc access from our ip addr.  Also replace
    "pcp restart" with component "pmcd restart" then "pmlogger restart"
    (may not be necessary but is not a bad practice given that "pcp"
    is a pseudo service wrapper).

diff --git a/qa/admin/allow-pmlc-access b/qa/admin/allow-pmlc-access
--- a/qa/admin/allow-pmlc-access
+++ b/qa/admin/allow-pmlc-access
@@ -78,6 +78,36 @@ _getnetworkaddr()
 		else
 		    echo >&2 "Neither ifconfig(1) nor ip(1)? Not sure how to get primary ip addr and netmask"
 		fi
+	    elif echo "$host_out" | grep ' not found: ' >/dev/null
+	    then
+		# container or dodgey network configuration ... see if
+		# ip(1) can help out with a line like
+		# 3: eth0    inet 10.88.0.2/16 ...
+		#
+		if `which ip >/dev/null 2>&1`
+		then
+		    ip -f inet -o addr | grep -v ': lo ' >$tmp.ip 2>&1
+		    num_if=`wc -l <$tmp.ip | sed -e 's/ //g'`
+		    if [ "$num_if" = 1 ]
+		    then
+			addr=`sed  <$tmp.ip -e 's/.* inet //' -e 's@/.*@@'`
+			$__verbose && echo "_getnetworkaddr: ip -> addr=$addr" >&2
+			echo "$addr"
+			mask=`sed <$tmp.ip -e 's/.*inet //' -e 's/[0-9.][0-9.]*\/\([^ ][^ ]*\) .*/\1/'`
+			if [ "$mask" != 24 ]
+			then
+			    echo >&2 "_getnetworkaddr: Warning: cannot handle network mask: $mask"
+			fi
+			# /24 netmask
+			mask=255.255.255.0
+			$__verbose && echo "_getnetworkaddr: ip -> mask=$mask" >&2
+		    else
+			echo >&2 "Unexpected ip(1) output: more than one line ..."
+			cat >&2 $tmp.ip
+		    fi
+		else
+		    echo >&2 "host(1) failed and ip(1) not installed ... cannot get ip_addr and netmask"
+		fi
 	    else
 		echo >&2 "Unexpected host(1) output: $host_out ... cannot get ip addr and netmask"
 	    fi
