qa/admin/check-vm: Add note to ignore networking warnings if not running QA

diff --git a/qa/admin/check-vm b/qa/admin/check-vm
--- a/qa/admin/check-vm
+++ b/qa/admin/check-vm
@@ -73,20 +73,20 @@ p
 			echo "$addr" | sed -e 's/\.[0-9]*$/.*/'
 			;;
 		    *)
-			echo >&2 "_getnetworkaddr: cannot handle network mask: $mask"
+			echo >&2 "_getnetworkaddr: Warning: cannot handle network mask: $mask"
 			;;
 		esac
 		;;
 	    0)	# none?
-		echo >&2 "_getnetworkaddr: cannot get network address"
+		echo >&2 "_getnetworkaddr: Warning: cannot get network address"
 		;;
 	    *)	# multiple?
-		echo >&2 "_getnetworkaddr: cannot handle multiple network addresses:"
+		echo >&2 "_getnetworkaddr: Warning: cannot handle multiple network addresses:"
 		cat >&2 $tmp.addr
 		;;
 	esac
     else
-	echo >&2 '_getnetworkaddr: no ifconfig?'
+	echo >&2 '_getnetworkaddr: Warning: no ifconfig?'
     fi
 }
 
@@ -583,6 +583,9 @@ then
 	else
 	    echo "Warning: \"$PCP_VAR_DIR/config/pcp/pmlogger/config.default\" is missing"
 	fi
+    else
+	echo "Please ignore Warnings from _getnetworkaddr unless you wish to run the"
+	echo "full PCP QA suite."
     fi
 else
     echo "Warning: \"/etc/pcp.conf\" is missing"
