qa: fix some typos in qa/admin docs/scripts

diff --git a/qa/admin/check-vm b/qa/admin/check-vm
--- a/qa/admin/check-vm
+++ b/qa/admin/check-vm
@@ -81,7 +81,7 @@ p
 		echo >&2 "_getnetworkaddr: cannot get network address"
 		;;
 	    *)	# multiple?
-		echo >&2 "_getnetworkaddr: cannot handle multiple network addresss:"
+		echo >&2 "_getnetworkaddr: cannot handle multiple network addresses:"
 		cat >&2 $tmp.addr
 		;;
 	esac
