qa/admin/check-vm: more changes
- refactor how unavailable packages are handled, especially in the
  handoff from check-vm to check-manifest
- properly handle alternate packages in the [...] part of the
  manifest, and in particular check-vm -p lists all of them, except
  the unavailable ones
- openSUSE and zypper changes
- vm02 changes

diff --git a/qa/admin/check-manifest b/qa/admin/check-manifest
--- a/qa/admin/check-manifest
+++ b/qa/admin/check-manifest
@@ -74,6 +74,11 @@ then
     echo "$0: Hand off botch: $tmp.manifest not found"
     exit 1
 fi
+if [ ! -f $tmp.unavail ]
+then
+    echo "$0: Hand off botch: $tmp.unavail not found"
+    exit 1
+fi
 
 _cleanup()
 {
@@ -93,8 +98,10 @@ then
     # clean up stuff left over from any previous runs
     #
     mv $tmp.manifest $tmp-manifest
+    mv $tmp.unavail $tmp-unavail
     rm -f $tmp.*
     mv $tmp-manifest $tmp.manifest
+    mv $tmp-unavail $tmp.unavail
 fi
 
 # $pkgtool tells us what family of packaging tools we need
@@ -744,207 +751,166 @@ do
 
 done
 
-# check the N/A packages list for this host
+# check the N/A packages list for this platform
 #
-sed -n <$tmp.manifest \
-    -e '/^[^#]*\[N\/A/{
-p
-}' \
-| sed -e 's/.*:\([0-9][0-9]*\)$/\1/' >$tmp.tmp
-if [ -s $tmp.tmp ]
+if [ -s $tmp.unavail ]
 then
     rm -f $tmp.botch $tmp.allpkgs
-    $PCP_ECHO_PROG $PCP_ECHO_N "Checking the `wc -l <$tmp.tmp | sed -e 's/ //g'` N/A packages for `hostname -s` ""$PCP_ECHO_C"
+    $PCP_ECHO_PROG $PCP_ECHO_N "Checking the `wc -l <$tmp.unavail | sed -e 's/ //g'` N/A packages for `hostname -s` ""$PCP_ECHO_C"
     if $verbose
     then
 	$PCP_ECHO_PROG "..."
     else
 	touch $tmp.dots
     fi
-    cat $tmp.tmp \
-    | while read lineno
+    cat $tmp.unavail \
+    | while read pkg 
     do
-	eval `sed <$home/other-packages/manifest -n -e "$lineno{"'
-s/^!//
-s/^[a-z][a-z]*[?][ 	][ 	]*//
-s/[ 	][ 	]*/ /g
-s/^/_target="/
-s/ .*/"/
-p
-q
-}'`
-	eval `sed <$home/other-packages/manifest -n -e "$lineno{"'
-s/^!//
-s/^[a-z][a-z]*[?][ 	][ 	]*//
-s/[ 	][ 	]*/ /g
-s/\[//
-s/]//
-s/^[^ ]* /_extra="/
-s/$/"/
-p
-q
-}'`
-	$very_verbose && echo >&2 "line=\"$lineno\" _target=\"$_target\" _extra=\"$_extra\""
-	# if package list is N/A, use the target as a best guess
-	# alias
-	#
-	_extra=`echo "$_extra" \
-	        | sed \
-		    -e 's/#.*//' \
-		    -e 's/ ([^)]*)//' \
-		    -e 's/ or / /g' \
-		    -e 's/^  *//' \
-		    -e 's/  *$//'`
-	[ "$_extra" = "N/A" ] && _extra="$_target"
-	$very_verbose && echo >&2 "after cull _extra=\"$_extra\""
-	for pkg in $_extra
-	do
-	    if $verbose
-	    then
-		echo >&2 "$lineno: check N/A for \"$pkg\""
-	    else
-		# may be slow, so emit dots for progress ...
+	if $verbose
+	then
+	    echo >&2 "check N/A for \"$pkg\""
+	else
+	    # may be slow, so emit dots for progress ...
+	    #
+	    $PCP_ECHO_PROG >&2 $PCP_ECHO_N ."$PCP_ECHO_C"
+	    touch $tmp.dots
+	fi
+	rm -f $tmp.avail
+	case "$searchtool"
+	in
+	    dpkg-query)
+		if dpkg-query -l "$pkg" >$tmp.out 2>&1
+		then
+		    if grep "^un *$pkg " $tmp.out >/dev/null
+		    then
+			:
+		    else
+			touch $tmp.avail
+			$verbose && cat >&2 $tmp.out
+		    fi
+		fi
+		;;
+
+	    yum)
+		# For example: search bash ->
+		# bash.x86_64 : The GNU Bourne Again shell
+		# make package name match up to the .
 		#
-		$PCP_ECHO_PROG >&2 $PCP_ECHO_N ."$PCP_ECHO_C"
-		touch $tmp.dots
-	    fi
-	    rm -f $tmp.avail
-	    case "$searchtool"
-	    in
-		dpkg-query)
-		    if dpkg-query -l "$pkg" >$tmp.out 2>&1
-		    then
-			if grep "^un *$pkg " $tmp.out >/dev/null
-			then
-			    :
-			else
-			    touch $tmp.avail
-			    $verbose && cat >&2 $tmp.out
-			fi
-		    fi
-		    ;;
+		prefix=`echo "$pkg" | sed -e 's/[. ].*//'`
+		if yum search "$pkg" 2>&1 | grep "^$prefix" >$tmp.out 2>&1
+		then
+		    touch $tmp.avail
+		    $verbose && cat >&2 $tmp.out
+		fi
+		;;
 
-		yum)
-		    # For example: search bash ->
-		    # bash.x86_64 : The GNU Bourne Again shell
-		    # make package name match up to the .
-		    #
-		    prefix=`echo "$pkg" | sed -e 's/[. ].*//'`
-		    if yum search "$pkg" 2>&1 | grep "^$prefix" >$tmp.out 2>&1
-		    then
-			touch $tmp.avail
-			$verbose && cat >&2 $tmp.out
-		    fi
-		    ;;
+	    dnf)
+		# For example: search bash ->
+		# bash.x86_64 : The GNU Bourne Again shell
+		# make package name match up to the .
+		#
+		prefix=`echo "$pkg" | sed -e 's/[. ].*//'`
+		if dnf search "$pkg" 2>&1 | grep "^$prefix" >$tmp.out 2>&1
+		then
+		    touch $tmp.avail
+		    $verbose && cat >&2 $tmp.out
+		fi
+		;;
 
-		dnf)
-		    # For example: search bash ->
-		    # bash.x86_64 : The GNU Bourne Again shell
-		    # make package name match up to the .
-		    #
-		    prefix=`echo "$pkg" | sed -e 's/[. ].*//'`
-		    if dnf search "$pkg" 2>&1 | grep "^$prefix" >$tmp.out 2>&1
-		    then
-			touch $tmp.avail
-			$verbose && cat >&2 $tmp.out
-		    fi
-		    ;;
+	    zypper)
+		# make package name match up to the first digit or hypen
+		#
+		prefix=`echo "$pkg" | sed -e 's/^\([^0-9-]*\).*/\1/'`
+		if zypper search -t package "$pkg" | grep "| $prefix" >$tmp.out 2>&1
+		then
+		    touch $tmp.avail
+		    $verbose && cat >&2 $tmp.out
+		fi
+		;;
 
-		zypper)
-		    # make package name match up to the first digit or hypen
-		    #
-		    prefix=`echo "$pkg" | sed -e 's/^\([^0-9-]*\).*/\1/'`
-		    if zypper search -t package "$pkg" | grep "| $prefix" >$tmp.out 2>&1
-		    then
-			touch $tmp.avail
-			$verbose && cat >&2 $tmp.out
-		    fi
-		    ;;
+	    pkgin)
+		[ ! -f $tmp.allpkgs ] && pkgin avail >$tmp.allpkgs
+		if grep "^$pkg-" $tmp.allpkgs >$tmp.out 2>&1
+		then
+		    touch $tmp.avail
+		    $verbose && cat >&2 $tmp.out
+		fi
+		;;
 
-		pkgin)
-		    [ ! -f $tmp.allpkgs ] && pkgin avail >$tmp.allpkgs
-		    if grep "^$pkg-" $tmp.allpkgs >$tmp.out 2>&1
-		    then
-			touch $tmp.avail
-			$verbose && cat >&2 $tmp.out
-		    fi
-		    ;;
+	    F_pkg)
+		# For example: search bash ->
+		# bash-4.4.23                    GNU Project's Bourne Again SHell
+		# make package name match up to the -<digit>
+		#
+		prefix=`echo "$pkg" | sed -e 's/-[0-9].*//'`
+		if pkg search "$pkg" 2>&1 | grep "^$prefix" >$tmp.out 2>&1
+		then
+		    touch $tmp.avail
+		    $verbose && cat >&2 $tmp.out
+		fi
+		;;
 
-		F_pkg)
-		    # For example: search bash ->
-		    # bash-4.4.23                    GNU Project's Bourne Again SHell
-		    # make package name match up to the -<digit>
-		    #
-		    prefix=`echo "$pkg" | sed -e 's/-[0-9].*//'`
-		    if pkg search "$pkg" 2>&1 | grep "^$prefix" >$tmp.out 2>&1
-		    then
-			touch $tmp.avail
-			$verbose && cat >&2 $tmp.out
-		    fi
-		    ;;
+	    pkg_locate)
+		# For example: search bash (installed) ->
+		# Information for inst:bash-4.4.23
+		# 		   search GraphicsMagic (not installed) ->
+		# Information for https://mirror.aarnet.edu.au/pub/OpenBSD/6.4/packages/amd64/GraphicsMagick-1.3.30.tgz
+		#
+		# Really using pkg_info becasuse pkg_locate matches on
+		# path, not package name
+		#
+		if pkg_info "$pkg" 2>&1 | grep '^Information ' >$tmp.out
+		then
+		    touch $tmp.avail
+		    $verbose && cat >&2 $tmp.out
+		fi
+		;;
 
-		pkg_locate)
-		    # For example: search bash (installed) ->
-		    # Information for inst:bash-4.4.23
-		    # 		   search GraphicsMagic (not installed) ->
-		    # Information for https://mirror.aarnet.edu.au/pub/OpenBSD/6.4/packages/amd64/GraphicsMagick-1.3.30.tgz
-		    #
-		    # Really using pkg_info becasuse pkg_locate matches on
-		    # path, not package name
-		    #
-		    if pkg_info "$pkg" 2>&1 | grep '^Information ' >$tmp.out
-		    then
-			touch $tmp.avail
-			$verbose && cat >&2 $tmp.out
-		    fi
-		    ;;
+	    equery)
+		# For example: equery meta bash ->
+		# ...
+		# Location:    /usr/portage/app-shells/bash
+		#
+		if equery meta "$pkg" 2>&1 | grep '^Location:' >$tmp.out
+		then
+		    touch $tmp.avail
+		    $verbose && cat >&2 $tmp.out
+		fi
+		;;
 
-		equery)
-		    # For example: equery meta bash ->
-		    # ...
-		    # Location:    /usr/portage/app-shells/bash
-		    #
-		    if equery meta "$pkg" 2>&1 | grep '^Location:' >$tmp.out
-		    then
-			touch $tmp.avail
-			$verbose && cat >&2 $tmp.out
-		    fi
-		    ;;
+	    brew)
+		# For example: brew info bash ->
+		# ...
+		# bash: stable 4.4.23 (bottled), HEAD
+		#
+		if brew info "$pkg" 2>&1 | grep "^$pkg:" >$tmp.out
+		then
+		    touch $tmp.avail
+		    $verbose && cat >&2 $tmp.out
+		fi
+		;;
 
-		brew)
-		    # For example: brew info bash ->
-		    # ...
-		    # bash: stable 4.4.23 (bottled), HEAD
-		    #
-		    if brew info "$pkg" 2>&1 | grep "^$pkg:" >$tmp.out
-		    then
-			touch $tmp.avail
-			$verbose && cat >&2 $tmp.out
-		    fi
-		    ;;
-
-		*)
-		    if [ -f $tmp.dots ]
-		    then
-			echo
-			rm -f $tmp.dots
-		    fi
-		    echo "_hunt: Botch: no rule for searchtool=$searchtool"
-		    touch $tmp.botch
-		    break
-		    ;;
-	    esac
-	    if [ -f $tmp.avail ]
-	    then
+	    *)
 		if [ -f $tmp.dots ]
 		then
 		    echo
 		    rm -f $tmp.dots
 		fi
-		$verbose && cat >&2 $tmp.out
-		echo "$lineno: looks like package $pkg may be available"
+		echo "_hunt: Botch: no rule for searchtool=$searchtool"
+		touch $tmp.botch
+		break
+		;;
+	esac
+	if [ -f $tmp.avail ]
+	then
+	    if [ -f $tmp.dots ]
+	    then
+		echo
+		rm -f $tmp.dots
 	    fi
-	done
+	    $verbose && cat >&2 $tmp.out
+	    echo "looks like package $pkg may be available"
+	fi
 	[ -f $tmp.botch ] && break
     done
 
