qa/admin/check-vm - check $HOME is searchable by others
Needed for some QA tests so user pcp (aka pmcd) can find QA
PMDAs.

diff --git a/qa/admin/check-vm b/qa/admin/check-vm
--- a/qa/admin/check-vm
+++ b/qa/admin/check-vm
@@ -430,3 +430,5 @@ then
 else
     echo "Warning: \"/etc/pcp.conf\" is missing"
 fi
+
+sudo -u pcp [ -x $HOME ] || echo "Error: $HOME is not searchable by user \"pcp\""
