qa/admin/check-vm: refactoring for Arch Linux
In addition to manifest and unavailable changes some rework of
check-vm for better diagnostics and integrity checks.

diff --git a/qa/admin/check-vm b/qa/admin/check-vm
--- a/qa/admin/check-vm
+++ b/qa/admin/check-vm
@@ -279,7 +279,7 @@ _parse_file()
 	-e 's/ \[.*//' \
 	-e 's/ ([^)]*)//' \
 	-e 's/RHEL Server/RHEL/' \
-	-e 's/Arch Linux/ArchLinux/' \
+	-e 's/Arch Linux/ArchLinux /' \
 	-e '/CentOS/{
 s/CentOS Linux/CentOS/
 s/CentOS\([0-9]\)/CentOS \1/
@@ -293,8 +293,8 @@ s/CentOS\([0-9]\)/CentOS \1/
 	-e 's/+_/ _/' \
 	-e 's/$/"/' \
     | tr ' ' '\012' >$tmp.eval
+    $very_verbose && echo >&2 "_parse_file: vars: `tr '\012' ' ' <$tmp.eval`"
     eval `cat $tmp.eval`
-    $very_verbose && echo >&2 "_parse_file: vars: `cat $tmp.eval`"
     sed <$1 \
 	-e 's/#.*//' \
 	-e '/^[ 	]*$/d' \
@@ -408,14 +408,9 @@ then
 fi
 $home/whatami >$tmp.whatami
 
-if $check_manifest
-then
-    # append original line numbers
-    #
-    $PCP_AWK_PROG '{ print $0 " :" NR }' <$manifest >$tmp.manifest
-else
-    cat <$manifest >$tmp.manifest
-fi
+# append original line numbers for non-blank lines
+#
+$PCP_AWK_PROG 'NF > 0 { print $0 " :" NR }' <$manifest >$tmp.manifest
 
 if which python >/dev/null 2>&1
 then
@@ -545,6 +540,10 @@ do
 		    ls /var/log/packages | sed -e 's/-[0-9].*//'
 		    ;;
 
+		pacman)
+		    pacman -Q -i | sed -n -e '/^Name /s/.* : //p'
+		    ;;
+
 		brew)
 		    echo >&2 "TODO: no list all packages method for brew"
 		    ;;
@@ -608,29 +607,15 @@ do
     fi
 done
 
-# Modify the package inventory for some particular hosts where we've
-# explored and _know_ certain packages are not available
-#
-unavail_pkg=''
-case `hostname -s`
-in
-    vm34)
-	unavail_pkg='umad libpapi libpfm gfs2 python-prometheus-client python2-prometheus-client python2-openpyxl dtrace boost'
-	;;
-esac
-
 # the "unavailable" file records packages that are not available for a
 # particular distribution and version and archtecture ... 
 #
-if [ -z "$unavail_pkg" ]
+_parse_file $unavailable >$tmp.pkgs
+if [ -s $tmp.pkgs ]
 then
-    _parse_file $unavailable >$tmp.pkgs
-    if [ -s $tmp.pkgs ]
-    then
-	unavail_pkg="`cat $tmp.pkgs`"
-    fi
-    $very_verbose && echo >&2 "unavailable: $unavail_pkg"
+    unavail_pkg="`cat $tmp.pkgs`"
 fi
+$very_verbose && echo >&2 "unavailable: $unavail_pkg"
 
 # the "require" file records packages that are must be installed for a
 # particular distribution and version and archtecture ... 
@@ -702,10 +687,10 @@ then
 	for _pkg in $skip_pkg
 	do
 	    sed <$tmp.manifest >$tmp.tmp -e "/[[ ]$_pkg[] ]/"'{
-s;\[[^]]*];[skip on host '"$_hostname"'];
+s;\[[^]]*];[SKIP on host '"$_hostname"'];
 }'
 	    mv $tmp.tmp $tmp.manifest
-	    $very_verbose && echo >&2 "skip for host: $_pkg"
+	    $very_verbose && echo >&2 "skip on host: $_pkg"
 	done
     fi
 fi
@@ -720,7 +705,7 @@ then
     for _pkg in `cat $tmp.pkgs`
     do
 	sed <$tmp.manifest >$tmp.tmp -e "/[[ ]$_pkg[] ]/"'{
-s;\[[^]]*];[skip];
+s;\[[^]]*];[SKIP];
 }'
 	mv $tmp.tmp $tmp.manifest
 	$very_verbose && echo >&2 "skip: $_pkg"
@@ -795,8 +780,10 @@ fi
 #
 cat $tmp.manifest \
 | sed -e 's/#.*//' -e '/^[ 	]*$/d' \
-| while read apps
+| while read line
 do
+    apps=`echo "$line" | sed -e 's/:[0-9][0-9]*$//' -e 's/ $//'`
+    lineno=`echo "$line" | sed -e 's/.* :\([0-9][0-9]*\)$/\\1/'`
     rm -f $tmp.ok
     rm -f $tmp.echo
     for app in $apps
@@ -893,7 +880,11 @@ do
 	then
 	    if $optional
 	    then
-		[ -f $tmp.echo ] && echo >&2
+		if [ -f $tmp.echo ]
+		then
+		    echo >&2
+		    rm -f $tmp.echo
+		fi
 		continue
 	    fi
 	    touch $tmp.ok
@@ -907,19 +898,16 @@ do
 	    fi
 	fi
     done
-    [ -f $tmp.echo ] && echo >&2
     if [ ! -f $tmp.ok ]
     then
 	if $pkglist
 	then
 	    echo "$apps" \
 	    | sed -n \
-		-e '/\[skip]/d' \
-		-e '/\[skip on host/d' \
+		-e '/\[SKIP on host/s/on host.*/]/' \
 		-e 's/.*\[//' \
 		-e 's/]//' \
 		-e 's/ ([^)]*)//' \
-		-e 's/N\/A//' \
 		-e 's/base [^ ]* install//' \
 		-e 's/^or //' \
 		-e 's/ or$//' \
@@ -935,15 +923,40 @@ do
 		#
 		for _need in $_missing
 		do
+		    if [ "$_need" = "N/A" ]
+		    then
+			if $verbose
+			then
+			    $PCP_ECHO_PROG >&2 $PCP_ECHO_N "[unavailable] "$PCP_ECHO_C
+			    touch $tmp.echo
+			fi
+			continue
+		    fi
+		    if [ "$_need" = "SKIP" ]
+		    then
+			if $verbose
+			then
+			    $PCP_ECHO_PROG >&2 $PCP_ECHO_N "[skip] "$PCP_ECHO_C
+			    touch $tmp.echo
+			fi
+			continue
+		    fi
 		    if grep "^$_need\$" $tmp.installed >/dev/null
 		    then
-			:
+			[ -f $tmp.echo ] && echo >&2
+			echo >&2 "Warning: manifest:$lineno botch? target: \"`echo "$apps" | sed -e 's/[ 	].*//'`\" not found, but package \"$_need\" already installed"
+			rm -f $tmp.echo
 		    else
 			rm -f $tmp.match
 			for _pkg in $unavail_pkg
 			do
 			    if echo " $_need " | grep " $_pkg " >/dev/null
 			    then
+				if $verbose
+				then
+				    $PCP_ECHO_PROG >&2 $PCP_ECHO_N "[unavailable] "$PCP_ECHO_C
+				    touch $tmp.echo
+				fi
 				touch $tmp.match
 				break
 			    fi
@@ -970,8 +983,18 @@ t loop2
 s/@/ /g
 }'`"
 	fi
+    else
+	if echo "$apps" | grep 'N/A' >/dev/null
+	then
+	    [ -f $tmp.echo ] && echo >&2
+	    echo >&2 "Warning: manifest:$lineno botch? target: \"`echo "$apps" | sed -e 's/[ 	].*//'`\" found, but marked N/A"
+	    rm -f $tmp.echo
+	fi
     fi
+    [ -f $tmp.echo ] && echo >&2
+
 done >$tmp.out
+
 
 if $pkglist
 then
