qa/check-vm: change oil filters and spark plugs, rotate tyres
Fix Nathan's problem ... when a "packaging" command exists on a
strange platform, don't get confused.  In this case it was brew(1)
(not the Mac OS X one) on Fedora 32 where we need to focus on manifest
lines beginning rpm? and not get confused by those starting brew?

Refactor involved shuffling some code around and also cleaning up
the logic a bit.

diff --git a/qa/admin/check-vm b/qa/admin/check-vm
--- a/qa/admin/check-vm
+++ b/qa/admin/check-vm
@@ -4,29 +4,6 @@
 # and packages
 #
 
-export LC_COLLATE=POSIX
-
-if [ -f /etc/pcp.conf ]
-then
-    . /etc/pcp.conf
-else
-    # punt
-    #
-    case `uname`
-    in
-	Darwin|*BSD)
-	    PCP_ECHO_PROG=echo
-	    PCP_ECHO_N=
-	    PCP_ECHO_C='\c'
-	    ;;
-	*)
-	    PCP_ECHO_PROG=echo
-	    PCP_ECHO_N=-n
-	    PCP_ECHO_C=
-	    ;;
-    esac
-fi
-
 # same function is in allow-pmlc-access ... need to track changes
 #
 _getnetworkaddr()
@@ -128,125 +105,6 @@ _usage()
     echo "  -v           verbose (debugging)"
     exit 1
 }
-
-# Need directory where check-vm script is located so we can find
-# the default other-packages/manifest and other-packages/unavailable
-# files and the whatami script
-#
-home=`echo $0 | sed -e 's/\/*check-vm$//'`
-if [ -z "$home" -o ! -d "$home" ]
-then
-    echo "Botch: \$0=$0 -> bad \$home=$home ?"
-    exit 1
-fi
-
-basic=false
-force=false
-pkglist=false
-pkgcmd=false
-verbose=false
-very_verbose=false
-check_manifest=false
-check_manifest_args=''
-manifest="$home"/other-packages/manifest		# default, see -m
-otherdir=other-packages					# default, see -o
-require="$home"/other-packages/require			# default, see -r
-skip="$home"/other-packages/skip			# default, see -s
-skipbase="$home"/other-packages/skip			# default, see -S
-unavailable="$home"/other-packages/unavailable		# default, see -u
-include_meta=true
-while getopts 'bcfm:Mo:pPr:s:S:u:v?' p
-do
-    case "$p"
-    in
-	b)
-		basic=true
-		;;
-
-	c)	# exec check-manifest when manifest has been build
-		# ... expert only, so not even mentioned in Usage
-		#
-		check_manifest=true
-		;;
-
-	f)
-		force=true
-		;;
-
-	M)	include_meta=false
-		;;
-
-	m)	# alternate manifest
-		manifest="$OPTARG"
-		;;
-
-	o)	# alternate other-packages directory
-		otherdir="$OPTARG"
-		;;
-
-	p)	# just list most likely package for yum, dnf, apt-get, ...
-		pkglist=true
-		;;
-
-	P)	# same as -P but emit shell commands for installer
-		pkgcmd=true
-		pkglist=true
-		;;
-
-	r)	# alternate require
-		require="$OPTARG"
-		;;
-
-	s)	# alternate skip
-		skip="$OPTARG"
-		;;
-
-	S)	# alternate skip basename
-		skipbase="$OPTARG"
-		;;
-
-	u)	# alternate unavailable
-		unavailable="$OPTARG"
-		;;
-
-	v)	if $verbose
-		then
-		    very_verbose=true
-		else
-		    verbose=true
-		fi
-		check_manifest_args="$check_manifest_args -v"
-		;;
-
-	?)	_usage
-		# NOTREACHED
-    esac
-done
-shift `expr $OPTIND - 1`
-[ $# -eq 0 ] || _usage
-
-if $very_verbose
-then
-    tmp=tmp
-else
-    tmp=/var/tmp/$$
-    trap "rm -f $tmp.*; exit 0" 0 1 2 3 15
-fi
-rm -f $tmp.*
-
-if [ -f /etc/pcp.conf ]
-then
-    . /etc/pcp.conf
-else
-    # punt!
-    #
-    if which gawk >/dev/null 2>&1
-    then
-	PCP_AWK_PROG=gawk
-    else
-	PCP_AWK_PROG=awk
-    fi
-fi
 
 # version1 is on line 1
 # version2 is on line 2
@@ -380,66 +238,6 @@ s/CentOS\([0-9]\)/CentOS \1/
     fi
 }
 
-_find_installer_cmd()
-{
-    installcmd=''
-    case "`sed <$tmp.whatami -e 's/  */ /g' -e 's/ \[.*//' | cut -d ' ' -f 4-`"
-    in
-	*Ubuntu*|*Debian*|*LinuxMint*)
-	    installcmd="apt install"
-	    ;;
-	*RHEL*|*Fedora*|*CentOS*|*openSUSE*|*SUSE\ SLES*)
-	    if which zypper >/dev/null 2>&1
-	    then
-		installcmd="zypper install"
-	    elif which dnf >/dev/null 2>&1
-	    then
-		installcmd="dnf install"
-	    elif which yum >/dev/null 2>&1
-	    then
-		installcmd="yum install"
-	    fi
-	    ;;
-
-	*NetBSD*)
-	    installcmd="pkgin -y install"
-	    ;;
-
-	*FreeBSD*)
-	    installcmd="pkg install"
-	    ;;
-
-	*OpenBSD*)
-	    installcmd="pkg_add"
-	    ;;
-
-	*Gentoo*)
-	    installcmd="emerge --ask"
-	    ;;
-
-	*Darwin*)
-	    installcmd="brew install"
-	    ;;
-
-	*OpenIndiana*)
-	    installcmd="pkg install"
-	    ;;
-
-	*Slackware*)
-	    installcmd="slackpkg install"
-	    ;;
-
-	*Arch\ Linux*)
-	    installcmd="pacman -S"
-	    ;;
-    esac
-    if [ -z "$installcmd" ]
-    then
-	echo "$0: Botch: don't recognize installcmd for: `cat $tmp.whatami`"
-	exit
-    fi
-}
-
 # create $tmp.allpkgs if we know how to do that ...
 #
 _build_allpkgs()
@@ -531,7 +329,7 @@ p
 	# TODO
 	;;
 
-esac
+    esac
 }
 
 # need to be careful ... $1 uses an extended regexp notation where
@@ -617,11 +415,218 @@ s/\[([^)]*)]/['"$_msg"']/
 	then
 	    : no diffs
 	else
-	    echo "Diffs applying manifest cull for package \"$_pkg\" ..."
 	    diff $tmp.manifest $tmp.culled
 	fi
     fi
 }
+
+# Networking goo
+#
+_check_host()
+{
+    ipaddr=`sed -n </etc/hosts -e '/^#/d' -e '/::/d' -e 's/$/ /' -e "/[ 	]$1[ 	]/"'{
+s/[ 	].*//
+p
+}'`
+    if [ -z "$ipaddr" ]
+    then
+	echo "No /etc/hosts entry for $1"
+	return
+    fi
+
+    if [ `echo "$ipaddr" | wc -l | sed -e 's/  *//g'` -gt 1 ]
+    then
+	echo "Multiple /etc/hosts entries for $1"
+	return
+    fi
+
+    rm -f $tmp.tmp
+    if `which ifconfig >/dev/null 2>&1`
+    then
+	# ifconfig lines of interest look like
+	# br0: flags=4163<UP,BROADCAST,RUNNING,MULTICAST>  mtu 1500
+        #	inet 192.168.1.100  netmask 255.255.255.0  broadcast 192.168.1.255
+        # ...
+	# lo: flags=73<UP,LOOPBACK,RUNNING>  mtu 65536
+	#	inet 127.0.0.1  netmask 255.0.0.0
+	#
+	ifconfig >$tmp.tmp
+    elif `which ip >/dev/null 2>&1`
+    then
+	ip -f inet address >$tmp.tmp
+	# ip lines of interest look like
+	# 1: lo: <LOOPBACK,UP,LOWER_UP> mtu 65536 qdisc ...
+	#     inet 127.0.0.1/8 scope host lo
+	#     ...
+	# 4: br0: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc ...
+	#     inet 192.168.1.100/24 brd 192.168.1.255 scope global br0
+	#     ...
+    else
+	echo >&2 "Neither ifconfig(1) nor ip(1)? Not sure how to get primary ip addr"
+	return
+    fi
+    sed <$tmp.tmp \
+	-e 's/^[0-9][0-9]*: //' \
+	-e 's/: / /g' \
+	-e '/ inet /s/\/.*/ /' \
+    | awk >&2 '
+/^[^ 	]/	{ iface = $1; next }
+/inet addr:'$ipaddr' / || /inet '$ipaddr'[ \/]/ {
+			  if (iface == "lo")
+			    print "Warning: '$1' associated with loopback network interface"
+			  found = 1
+			  exit
+			}
+END		{ if (found != 1)
+		    print "Warning: '$1' ('$ipaddr') not associated with a network interface"
+		}'
+}
+
+#
+# --- MAINLINE ---
+#
+
+export LC_COLLATE=POSIX
+
+if [ -f /etc/pcp.conf ]
+then
+    . /etc/pcp.conf
+else
+    # punt
+    #
+    case `uname`
+    in
+	Darwin|*BSD)
+	    PCP_ECHO_PROG=echo
+	    PCP_ECHO_N=
+	    PCP_ECHO_C='\c'
+	    ;;
+	*)
+	    PCP_ECHO_PROG=echo
+	    PCP_ECHO_N=-n
+	    PCP_ECHO_C=
+	    ;;
+    esac
+fi
+
+# Need directory where check-vm script is located so we can find
+# the default other-packages/manifest and other-packages/unavailable
+# files and the whatami script
+#
+home=`echo $0 | sed -e 's/\/*check-vm$//'`
+if [ -z "$home" -o ! -d "$home" ]
+then
+    echo "Botch: \$0=$0 -> bad \$home=$home ?"
+    exit 1
+fi
+
+basic=false
+force=false
+pkglist=false
+pkgcmd=false
+verbose=false
+very_verbose=false
+check_manifest=false
+check_manifest_args=''
+manifest="$home"/other-packages/manifest		# default, see -m
+otherdir=other-packages					# default, see -o
+require="$home"/other-packages/require			# default, see -r
+skip="$home"/other-packages/skip			# default, see -s
+skipbase="$home"/other-packages/skip			# default, see -S
+unavailable="$home"/other-packages/unavailable		# default, see -u
+include_meta=true
+while getopts 'bcfm:Mo:pPr:s:S:u:v?' p
+do
+    case "$p"
+    in
+	b)
+		basic=true
+		;;
+
+	c)	# exec check-manifest when manifest has been build
+		# ... expert only, so not even mentioned in Usage
+		#
+		check_manifest=true
+		;;
+
+	f)
+		force=true
+		;;
+
+	M)	include_meta=false
+		;;
+
+	m)	# alternate manifest
+		manifest="$OPTARG"
+		;;
+
+	o)	# alternate other-packages directory
+		otherdir="$OPTARG"
+		;;
+
+	p)	# just list most likely package for yum, dnf, apt-get, ...
+		pkglist=true
+		;;
+
+	P)	# same as -P but emit shell commands for installer
+		pkgcmd=true
+		pkglist=true
+		;;
+
+	r)	# alternate require
+		require="$OPTARG"
+		;;
+
+	s)	# alternate skip
+		skip="$OPTARG"
+		;;
+
+	S)	# alternate skip basename
+		skipbase="$OPTARG"
+		;;
+
+	u)	# alternate unavailable
+		unavailable="$OPTARG"
+		;;
+
+	v)	if $verbose
+		then
+		    very_verbose=true
+		else
+		    verbose=true
+		fi
+		check_manifest_args="$check_manifest_args -v"
+		;;
+
+	?)	_usage
+		# NOTREACHED
+    esac
+done
+shift `expr $OPTIND - 1`
+[ $# -eq 0 ] || _usage
+
+if $very_verbose
+then
+    tmp=tmp
+else
+    tmp=/var/tmp/$$
+    trap "rm -f $tmp.*; exit 0" 0 1 2 3 15
+fi
+rm -f $tmp.*
+
+if [ -f /etc/pcp.conf ]
+then
+    . /etc/pcp.conf
+else
+    # punt!
+    #
+    if which gawk >/dev/null 2>&1
+    then
+	PCP_AWK_PROG=gawk
+    else
+	PCP_AWK_PROG=awk
+    fi
+fi
 
 # add additional and optional directories
 for dir in /sbin /usr/sbin
@@ -637,36 +642,6 @@ do
 	fi
     fi
 done
-
-# Packaging types we know about.
-#	dpkg - Debian-based
-#	rpm - RPM-based, e.g. RHEL, CentOS, SuSE, Fedora
-#	urpmi - OpenMandriva (also RPM based)
-#	emerge - Gentoo
-#	pkgin - NetBSD
-#	pkg_add - OpenBSD
-#	F_pkg - pkg(1) on FreeBSD
-#	S_pkg - pkg(1) on OpenIndiana
-#	slackpkg - Slackware
-#	pacman - Arch Linux
-#	brew - Mac OS X
-#
-pkgtypes="dpkg rpm urpmi emerge pkgin pkg_add F_pkg S_pkg slackpkg pacman brew"
-
-# Distros we know about (or more specifically ones with the same 
-# packaging tools but different package names).
-#
-#	debian		Debian, Ubuntu, LinuxMint, ...
-#	redhat		RedHat or Fedora
-#	centos		CentOS
-#	suse		SLES or OpenSuSE
-#	arch		Arch Linux
-#	mandriva	OpenMandriva
-#	freebsd		FreeBSD
-#	netbsd		NetBSD
-#	openbsd		OpenBSD
-#
-distros="debian redhat centos suse arch mandriva freebsd netbsd openbsd"
 
 if [ ! -f "$manifest" ]
 then
@@ -695,6 +670,143 @@ then
 fi
 $home/whatami >$tmp.whatami
 
+# Packaging types we know about.
+#	dpkg - Debian-based
+#	rpm - RPM-based, e.g. RHEL, CentOS, SuSE, Fedora
+#	emerge - Gentoo
+#	pkgin - NetBSD
+#	pkg_add - OpenBSD
+#	F_pkg - pkg(1) on FreeBSD
+#	S_pkg - pkg(1) on OpenIndiana
+#	slackpkg - Slackware
+#	pacman - Arch Linux
+#	brew - Mac OS X
+#	urpmi - OpenMandriva (also RPM based)
+#
+# later on we will select EXACTLY one of the $pkgtypes to be $mytype
+#
+pkgtypes="dpkg rpm urpmi emerge pkgin pkg_add F_pkg S_pkg slackpkg pacman brew"
+
+# Base on platform info, select the packaging type that applies and generate the
+# list of currently installed packages in $tmp.installed
+#
+mytype=''
+installcmd=''
+rm -f $tmp.installed
+case "`sed <$tmp.whatami -e 's/  */ /g' -e 's/ \[.*//' | cut -d ' ' -f 4-`"
+in
+    *Ubuntu*|*Debian*|*LinuxMint*)
+	mytype=dpkg
+	installcmd="apt install"
+	# just ones like
+	# xterm install ok installed
+	# and skip ones like
+	# zfsutils-linux deinstall ok config-files
+	#
+	dpkg-query -W -f '${package} ${status}\n' \
+	| sed -n -e '/ installed$/s/ .*//p' >$tmp.installed
+	;;
+
+    *RHEL*|*Fedora*|*CentOS*|*openSUSE*|*SUSE\ SLES*)
+	mytype=rpm
+	if which zypper >/dev/null 2>&1
+	then
+	    installcmd="zypper install"
+	elif which dnf >/dev/null 2>&1
+	then
+	    installcmd="dnf install"
+	elif which yum >/dev/null 2>&1
+	then
+	    installcmd="yum install"
+	fi
+	rpm -qa --qf '%{NAME}\n' >$tmp.installed
+	;;
+
+    *Gentoo*)
+	mytype=emerge
+	installcmd="emerge --ask"
+	equery list '*' | sed -e 's/.*].*] //' -e 's/-[0-9].*//' >$tmp.installed
+	;;
+
+    *NetBSD*)
+	mytype=pkgin
+	installcmd="pkgin -y install"
+	pkgin list | sed -e 's/-[0-9].*//' >$tmp.installed
+	;;
+
+    *OpenBSD*)
+	mytype=pkg_add
+	installcmd="pkg_add"
+	pkg_info -a | sed -e 's/-[0-9].*//' >$tmp.installed
+	;;
+
+    *FreeBSD*)
+	mytype=F_pkg
+	installcmd="pkg install"
+	pkg info -a | sed -e 's/-[0-9].*//' >$tmp.installed
+	;;
+
+    *OpenIndiana*)
+	mytype=S_pkg
+	installcmd="pkg install"
+	pkg list -H | sed -e 's/ .*//' >$tmp.installed
+	;;
+
+    *Slackware*)
+	mytype=slackpkg
+	installcmd="slackpkg install"
+	ls /var/log/packages | sed -e 's/-[0-9].*//' >$tmp.installed
+	;;
+
+    *Arch\ Linux*)
+	mytype=pacman
+	installcmd="pacman -S"
+	pacman -Q -i | sed -n -e '/^Name /s/.* : //p' >$tmp.installed
+	;;
+
+    *Darwin*)
+	mytype=brew
+	installcmd="brew install"
+	echo >&2 "TODO: no list all packages method for brew"
+	;;
+
+    *OpenMandriva*)
+	mytype=urpmi
+	installcmd="urpmi install"
+	urpmi -qa --qf '%{NAME}\n' >$tmp.installed
+	;;
+esac
+if [ -z "$mytype" ]
+then
+    echo "$0: Botch: don't recognize mytype for: `cat $tmp.whatami`"
+    exit
+fi
+if [ -z "$installcmd" ]
+then
+    echo "$0: Botch: don't recognize installcmd for: `cat $tmp.whatami`"
+    exit
+fi
+if [ ! -f $tmp.installed ]
+then
+    echo "$0: Botch: can't generate tmp.installed for: `cat $tmp.whatami`"
+    exit
+fi
+
+# Distros we know about (or more specifically ones with the same 
+# packaging tools but different package names).
+#
+#	debian		Debian, Ubuntu, LinuxMint, ...
+#	redhat		RedHat or Fedora
+#	centos		CentOS
+#	suse		SLES or OpenSuSE
+#	arch		Arch Linux
+#	mandriva	OpenMandriva
+#	freebsd		FreeBSD
+#	netbsd		NetBSD
+#	openbsd		OpenBSD
+#
+distros="debian redhat centos suse arch mandriva freebsd netbsd openbsd"
+
 # Append original line numbers for non-blank lines in the manifest.
 # Also rewrite [? ...] (package unknown) to [?:<original line number> ...]
 # for easier mapping back to the manifest file.
@@ -721,133 +833,20 @@ then
     fi
 fi
 
-# Handle some aliased packaging commands, e.g. pkg(1) is present but
-# different on both FreeBSD and OpenIndiana (nee Open Solaris).
-# In the package control lines we use F_pkg and S_pkg to differentatiate
-# but sort out if we have one or the other here to avoid repeated tests
-# in the loop below
-#
-have_F_pkg=false
-have_S_pkg=false
-if which pkg >/dev/null 2>&1
-then
-    if pkg help 2>&1 | grep 'jail(8)' >/dev/null
-    then
-	# FreeBSD is the only one to have jail(8) in the help text
-	#
-	have_F_pkg=true
-	$verbose && echo >&2 "F_pkg -> pkg for FreeBSD"
-    else
-	have_S_pkg=true
-	$verbose && echo >&2 "S_pkg -> pkg for OpenIndiana"
-    fi
-fi
-
 # Strip the packaging-dependent lines that do not apply ...
 # this is an optimization remove checks from the main loop below
 #
 rm -f $tmp.ok
 for pkgtype in $pkgtypes
 do
-    want=true
-    tool=$pkgtype
-    case $pkgtype
-    in
-	rpm)
-	    # Madriva really uses urpmi, but the rpm binary also is installed
-	    # so don't include the rpm? lines
-	    #
-	    which urpmi >/dev/null 2>&1 && want=false
-	    # similarly for Slackware where slackpkg is the real packing
-	    # tool
-	    #
-	    which slackpkg >/dev/null 2>&1 && want=false
-	    ;;
-	pkg_add)
-	    # NetBSD really uses pkgin
-	    which pkgin >/dev/null 2>&1 && want=false
-	    ;;
-	S_pkg)
-	    if $have_S_pkg
-	    then
-		tool=pkg
-	    else
-		want=false
-	    fi
-	    ;;
-	F_pkg)
-	    if $have_F_pkg
-	    then
-		tool=pkg
-	    else
-		want=false
-	    fi
-	    ;;
-    esac
-
-    if which $tool >/dev/null 2>&1 && $want
+    want=false
+    [ "$pkgtype" = "$mytype" ] && want=true
+    if $want
     then
 	$very_verbose && echo >&2 "include ${pkgtype}? lines"
 	sed -e "s/^${pkgtype}?[ 	]//" <$tmp.manifest >$tmp.tmp
 	mv $tmp.tmp $tmp.manifest
 	touch $tmp.ok
-	# one-trip list all currently installed packages for -p
-	#
-	if [ ! -f $tmp.installed ]
-	then
-	    case "$pkgtype"
-	    in
-		dpkg)
-		    # just ones like
-		    # xterm install ok installed
-		    # and skip ones like
-		    # zfsutils-linux deinstall ok config-files
-		    #
-		    dpkg-query -W -f '${package} ${status}\n' \
-		    | sed -n -e '/ installed$/s/ .*//p'
-		    ;;
-
-		rpm)
-		    rpm -qa --qf '%{NAME}\n'
-		    ;;
-
-		pkgin)
-		    pkgin list | sed -e 's/-[0-9].*//'
-		    ;;
-
-		F_pkg)
-		    pkg info -a | sed -e 's/-[0-9].*//'
-		    ;;
-
-		S_pkg)
-		    pkg list -H | sed -e 's/ .*//'
-		    ;;
-
-		pkg_add)
-		    pkg_info -a | sed -e 's/-[0-9].*//'
-		    ;;
-
-		emerge)
-		    equery list '*' | sed -e 's/.*].*] //' -e 's/-[0-9].*//'
-		    ;;
-
-		slackpkg)
-		    ls /var/log/packages | sed -e 's/-[0-9].*//'
-		    ;;
-
-		pacman)
-		    pacman -Q -i | sed -n -e '/^Name /s/.* : //p'
-		    ;;
-
-		brew)
-		    echo >&2 "TODO: no list all packages method for brew"
-		    ;;
-
-		*)
-		    echo >&2 "Botch: no list all packages method for $pkgtype"
-		    ;;
-	    esac >$tmp.installed
-	fi
     else
 	$very_verbose && echo >&2 "exclude ${pkgtype}? lines"
 	grep -v "^${pkgtype}?[ 	]" <$tmp.manifest >$tmp.tmp
@@ -1165,7 +1164,6 @@ then
     else
 	if $very_verbose
 	then
-	    echo "Diffs applying package pattern matching ..."
 	    diff $tmp.manifest $tmp.tmp
 	fi
 	mv $tmp.tmp $tmp.manifest
@@ -1461,7 +1459,6 @@ then
 	| uniq >$tmp.tmp
 	if $pkgcmd
 	then
-	    _find_installer_cmd
 	    grep -v 'cpan(' <$tmp.tmp | grep -v 'pip3(' >$tmp.pkg
 	    if [ -s $tmp.pkg ]
 	    then
@@ -1675,68 +1672,6 @@ End-of-File
 	fi
     done
 fi
-
-# Networking goo
-#
-_check_host()
-{
-    ipaddr=`sed -n </etc/hosts -e '/^#/d' -e '/::/d' -e 's/$/ /' -e "/[ 	]$1[ 	]/"'{
-s/[ 	].*//
-p
-}'`
-    if [ -z "$ipaddr" ]
-    then
-	echo "No /etc/hosts entry for $1"
-	return
-    fi
-
-    if [ `echo "$ipaddr" | wc -l | sed -e 's/  *//g'` -gt 1 ]
-    then
-	echo "Multiple /etc/hosts entries for $1"
-	return
-    fi
-
-    rm -f $tmp.tmp
-    if `which ifconfig >/dev/null 2>&1`
-    then
-	# ifconfig lines of interest look like
-	# br0: flags=4163<UP,BROADCAST,RUNNING,MULTICAST>  mtu 1500
-        #	inet 192.168.1.100  netmask 255.255.255.0  broadcast 192.168.1.255
-        # ...
-	# lo: flags=73<UP,LOOPBACK,RUNNING>  mtu 65536
-	#	inet 127.0.0.1  netmask 255.0.0.0
-	#
-	ifconfig >$tmp.tmp
-    elif `which ip >/dev/null 2>&1`
-    then
-	ip -f inet address >$tmp.tmp
-	# ip lines of interest look like
-	# 1: lo: <LOOPBACK,UP,LOWER_UP> mtu 65536 qdisc ...
-	#     inet 127.0.0.1/8 scope host lo
-	#     ...
-	# 4: br0: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc ...
-	#     inet 192.168.1.100/24 brd 192.168.1.255 scope global br0
-	#     ...
-    else
-	echo >&2 "Neither ifconfig(1) nor ip(1)? Not sure how to get primary ip addr"
-	return
-    fi
-    sed <$tmp.tmp \
-	-e 's/^[0-9][0-9]*: //' \
-	-e 's/: / /g' \
-	-e '/ inet /s/\/.*/ /' \
-    | awk >&2 '
-/^[^ 	]/	{ iface = $1; next }
-/inet addr:'$ipaddr' / || /inet '$ipaddr'[ \/]/ {
-			  if (iface == "lo")
-			    print "Warning: '$1' associated with loopback network interface"
-			  found = 1
-			  exit
-			}
-END		{ if (found != 1)
-		    print "Warning: '$1' ('$ipaddr') not associated with a network interface"
-		}'
-}
 
 host=`hostname`
 _check_host $host
