qa/admin: next round of upgrade-test scripts
This is now complete and working for (at least) RHEL 8,
and previous version worked for .deb distros (but will need to
be revisited after the rpm changes).

Use (the new) upgrade-setup to get going (rpm only at the moment),
this will call get-distro-packages if needed).

Then upgrade-test will do the job, as in ...
 - if <distro> packages are available locally below $home/build
   + remove all PCP packages
   + install the <distro> packages
   + upgrade to the <latest> developer packages
   + run qa/check -g sanity
 - if <previous> developer packages are available locally below $home/build
   + remove all PCP packages
   + install the <previous> developer packages
   + upgrade to the <latest> developer packages
   + run qa/check -g sanity

diff --git a/qa/admin/get-distro-packages b/qa/admin/get-distro-packages
--- a/qa/admin/get-distro-packages
+++ b/qa/admin/get-distro-packages
@@ -72,11 +72,11 @@ fi
 #                                          $4-$5
 #
 distro=`$home/qa/admin/whatami | awk '{ print $4 "-" $5 }'`
-$very_verbose && echo >&2 distro=$distro
+$verbose && echo >&2 distro=$distro
 
 case $distro
 in
-    Ubuntu-*)
+    Debian-*|Ubuntu-*|MX-*)
 	    if [ ! -d $home/build/$distro ]
 	    then
 		if mkdir $home/build/$distro
@@ -102,12 +102,16 @@ in
 		echo >&2 "Botch: apt failed to list all available packages"
 		exit
 	    fi
+	    rm -f $tmp.pkgs
 	    grep -E '^(libpcp|pcp-|pcp/|python3-pcp)' <$tmp.all \
 	    | grep -v '/now ' \
 	    | awk '{ print $1,$2 }' \
 	    | sed -e 's@/[^ ]*@@' \
+	    | sort \
+	    | uniq \
 	    | while read pkg vers
 	    do
+		echo "$pkk" >>$tmp.pkgs
 		here=`echo "${pkg}_${vers}_"*.deb`
 		case "$here"
 		in
@@ -133,9 +137,15 @@ in
 			;;
 		esac
 	    done
+	    if [ -s $tmp.pkgs ]
+	    then
+		$verbose && echo >&2 "`wc -l <$tmp.pkgs | sed -e 's/ //g'` PCP packages from distro $distro"
+	    else
+		echo >&2 "Warning: no PCP packages known to apt-get"
+	    fi
 	    ;;
 
-    Fedora-*)
+    Fedora-*|RHEL-8.*|CentOS-Linux7.*)
 	    if [ ! -d $home/build/$distro ]
 	    then
 		if mkdir $home/build/$distro
@@ -153,7 +163,7 @@ in
 		echo >&2 "Botch: cd failed"
 		exit
 	    fi
-	    if dnf --cacheonly --quiet repoquery --latest-limit=1 >$tmp.all 2>$tmp.err
+	    if sudo dnf --cacheonly --quiet --latest-limit=1 repoquery >$tmp.all 2>$tmp.err
 	    then
 		:
 	    else
@@ -161,28 +171,117 @@ in
 		echo >&2 "Botch: dnf failed to list all available packages"
 		exit
 	    fi
-	    grep -E '^(pcp-|python3-pcp)' <$tmp.all \
+	    distrover=`sed -n <$tmp.all -e '/^pcp-[0-9]/{
+s/-[0-9][0-9]*:/-/
+s/^pcp-//
+s/-.*//
+p
+}'`
+	    $verbose && echo >&2 "distrover=$distrover"
+
+	    rm -f $tmp.pkgs
+	    grep -E '^(pcp-|python.-pcp-|perl-PCP-)' <$tmp.all \
 	    | while read line
 	    do
-		if [ -f "$line" ]
+		# remove <digit>: before real version number,
+		# e.g. pcp-0:5.3.7-22.el8_10.x86_64
+		#
+		line=`echo "$line" | sed -e 's/-[0-9][0-9]*:/-/'`
+		# only get ones that match our architecture
+		#
+		arch=`echo "$line" | awk -F. '{print $NF}'`
+		case "$arch"
+		in
+		    noarch)	;;
+		    `uname -m`)	;;
+		    *)		$verbose && echo >&2 "$line skip, wrong arch"
+				continue
+		    		;;
+		esac
+		# if it is not $distrover, we're not interested
+		# (RHEL keep older versions for some reason, e.g. when
+		# distrover=5.3.7, dnf reports the that pcp-manager-5.1.1
+		# is available for RHEL-8
+		#
+		if echo "$line" | grep -q ".-$distrover-"
+		then
+		    :
+		else
+		    $verbose && echo >&2 "$line skip, not latest distro version of PCP"
+		    continue
+		fi
+		# and pcp-testsuite from the distro is never interesting,
+		# plus it may drag in dependencies that defeat the blacklisting
+		# described below
+		#
+		if echo "$line" | grep -q "^pcp-testsuite-"
+		then
+		    :
+		else
+		    $verbose && echo >&2 "$line skip, pcp-testsuite package"
+		    continue
+		fi
+		
+		# blacklisted packages ... there are some packages (rarely)
+		# that are created in the distro build, but cannot be upgraded
+		# from a developer build, probably because we can't satisfy
+		# some pre-condition for our build, e.g. a required package
+		# cannot be installed from the distro's "upgrade" repo 
+		#
+		case "$distro"
+		in
+		    RHEL-8.*)
+			case "$line"
+			in
+			    pcp-pmda-statsd-*)
+				# chan-devel and HdrHistogram_c-devel rpms are
+				# not availabe for RHEL-8
+				$verbose && echo >&2 "$line skip, upgrade blacklisted for $distro"
+				continue
+				;;
+			esac
+			;;
+		esac
+		echo "$line" >>$tmp.pkgs
+		if [ -f "$line.rpm" ]
 		then
 		    $verbose && echo >&2 "$line already downloaded"
-		else
-		    pkg=`echo "$line" | sed -e 's/-[0-9][0-9]*:.*//'`
+		    continue
+		fi
+		# handle upgrades, e.g.
+		# pcp-5.3.7-20.el8_10.x86_64.rpm -> pcp-5.3.7-22.el8_10.x86_64.rpm
+		#           ^^                                ^^
+		pat=`echo "$line.rpm" | sed -e 's/-[0-9][0-9]*\(.[^-]*\)$/-*\1/'`
+		if [ -f "`echo $pat`" ]
+		then
+		    $verbose && echo >&2 "remove old `echo $pat`"
 		    if $showme
 		    then
-			echo "+ dnf download $pkg"
+			echo "+ sudo rm `echo $pat`"
 		    else
-			if dnf download "$pkg"
-			then
-			    :
-			else
-			    echo >&2 "Botch: dnf failed to download $pkg"
-			    exit
-			fi
+			sudo rm `echo $pat`
+		    fi
+		fi
+		pkg=`echo "$line" | sed -e 's/-[0-9][0-9]*:.*//'`
+		if $showme
+		then
+		    echo "+ sudo dnf download $pkg"
+		else
+		    if sudo dnf download "$pkg"
+		    then
+			sudo chown $USER "$pkg.rpm"
+		    else
+		    echo >&2 "Botch: dnf failed to download $pkg"
+			exit
 		    fi
 		fi
 	    done
+	    if [ -s $tmp.pkgs ]
+	    then
+		$verbose && echo >&2 "`wc -l <$tmp.pkgs | sed -e 's/ //g'` PCP packages from distro $distro"
+	    else
+		echo >&2 "Warning: no PCP packages known to dnf"
+	    fi
 	    ;;
 
     *)
diff --git a/qa/admin/upgrade-test b/qa/admin/upgrade-test
--- a/qa/admin/upgrade-test
+++ b/qa/admin/upgrade-test
@@ -157,7 +157,7 @@ _uninstall_deb()
 	    else
 		if sudo apt-get --yes --quiet purge `cat $tmp.list` >$tmp.out 2>&1
 		then
-		    $showme || echo "Info: PCP uninstalled"
+		    $showme || echo "Info: uninstalled PCP"
 		else
 		    cat $tmp.out
 		    return 1
@@ -170,6 +170,11 @@ _uninstall_deb()
 	cat $tmp.out
 	return 1
     fi
+
+    # cull any left-over bits that will mess with QA after
+    # an install
+    #
+    sudo rm -rf /etc/pcp /var/lib/pcp
 
     return 0
 }
@@ -220,32 +225,99 @@ _upgrade_deb()
 
 _have_latest_rpm()
 {
-    nrpm=`( [ -d $home/pcp-$thisver/build/rpm ] && ls $home/pcp-$thisver/build/rpm/*.rpm 2>/dev/null ) | wc -l | sed -e 's/ //g'`
-    if [ -n "$nrpm" -a "$nrpm" -ge 150 ]
+    nrpm=`( [ -d $home/pcp-$thisver/build/rpm ] && ls $home/pcp-$thisver/build/rpm/*.rpm 2>/dev/null ) | grep -v '.-debuginfo-' | wc -l | sed -e 's/ //g'`
+    if [ -n "$nrpm" -a "$nrpm" -ge 100 ]
     then
 	return 0
     else
-	echo "Error: expecting at least 40 .rpms, found $nrpm"
+	echo "Error: expecting at least 100 .rpms, found $nrpm"
 	return 1
     fi
 }
 
 _uninstall_rpm()
 {
-    echo "rpm NYI"
-    return 1
+    if $interactive
+    then
+	_ask "_uninstall_rpm" || return 0
+    fi
+    if rpm -qa >$tmp.out 2>&1
+    then
+	grep -E '^(pcp-|python.-pcp-|perl-PCP-)' <$tmp.out \
+	| sed -e 's/-[0-9].*//' \
+	| tr '\012' ' ' >$tmp.list
+	if [ -s $tmp.list ]
+	then
+	    if $showme
+	    then
+		echo "+ sudo rpm -e `cat $tmp.list`"
+	    else
+		if sudo rpm -e `cat $tmp.list` >$tmp.out 2>&1
+		then
+		    $showme || echo "Info: uninstalled PCP"
+		else
+		    cat $tmp.out
+		    return 1
+		fi
+	    fi
+	else
+	    echo "Warning: no PCP packages installed?"
+	fi
+    else
+	cat $tmp.out
+	return 1
+    fi
+
+    # cull any left-over bits that will mess with QA after
+    # an install
+    #
+    sudo rm -rf /etc/pcp /var/lib/pcp
+
+    return 0
 }
 
 _install_rpm()
 {
-    echo "rpm NYI"
-    return 1
+    if $interactive
+    then
+	_ask "_install_rpm from `pwd`" || return 0
+    fi
+    if $showme
+    then
+	echo "+ sudo dnf -y install *.rpm"
+    else
+	if sudo dnf -y install *.rpm >$tmp.out 2>&1
+	then
+	    $very_verbose && cat $tmp.out
+	else
+	    cat $tmp.out
+	    return 1
+	fi
+    fi
+
+    return 0
 }
 
 _upgrade_rpm()
 {
-    echo "rpm NYI"
-    return 1
+    if $interactive
+    then
+	_ask "_upgrade_rpm from `pwd`" || return 0
+    fi
+    if $showme
+    then
+	echo "+ sudo rpm -U *.rpm"
+    else
+	if sudo rpm -U `ls *.rpm | sed -e '/\.src\.rpm\\$/d'` >$tmp.out 2>&1
+	then
+	    $very_verbose && cat $tmp.out
+	else
+	    cat $tmp.out
+	    return 1
+	fi
+    fi
+
+    return 0
 }
 
 _qa()
@@ -302,11 +374,11 @@ $verbose && echo >&2 lastver=$lastver
 
 case $distro
 in
-    Ubuntu-*)
+    Debian-*|Ubuntu-*|MX-*)
 	    type=deb
 	    ;;
 
-    Fedora-*)
+    Fedora-*|RHEL-*)
 	    type=rpm
 	    ;;
 
@@ -324,20 +396,36 @@ else
     exit
 fi
 
+case "$type"
+in
+    deb)
+	thispkgdir=build/$type
+	lastpkgdir=build/$type-$lastver
+	;;
+    rpm)
+	thispkgdir=pcp-$thisver/build/$type
+	lastpkgdir=build/$type-$lastver
+	;;
+    *)
+	echo >&2 "Botch: don't know where to find current $type packages"
+	exit
+	;;
+esac
+
 if [ -d $home/build/$distro ]
 then
     if _uninstall_$type
     then
-	$showme && echo "+ cd build/$distro"
+	$showme && echo "+ cd $home/build/$distro"
 	cd $home/build/$distro
 	if _install_$type
 	then
-	    $showme || echo "Info: PCP `_pcp_version` installed"
-	    $showme && echo "+ cd build/$type"
-	    cd $home/build/$type
+	    $showme || echo "Info: installed distro PCP `_pcp_version`"
+	    $showme && echo "+ cd $home/$thispkgdir"
+	    cd $home/$thispkgdir
 	    if _upgrade_$type
 	    then
-		$showme || echo "Info: PCP `_pcp_version` installed"
+		$showme || echo "Info: upgraded to PCP `_pcp_version`"
 		if _qa
 		then
 		    $showme || echo "Info: sanity QA passes"
@@ -351,28 +439,28 @@ then
 	    $showme || echo "Error: installation of $distro distro version failed"
 	fi
     else
-	$showme || echo "Error: uninstallation of all PCP failed"
+	$showme || echo "Error: uninstallation of PCP failed"
     fi
 else
-    echo "Info: build/$distro missing, skip this test"
+    echo "Info: $home/build/$distro missing, skip this test"
 fi
 
 if [ -n "$lastver" ]
 then
-    if [ -d $home/build/$type-$lastver ]
+    if [ -d $home/$lastpkgdir ]
     then
 	if _uninstall_$type
 	then
-	    $showme && echo "+ cd build/$type-$lastver"
-	    cd $home/build/$type-$lastver
+	    $showme && echo "+ cd $home/$lastpkgdir"
+	    cd $home/$lastpkgdir
 	    if _install_$type
 	    then
-		$showme || echo "Info: PCP `_pcp_version` installed"
-		$showme && echo "+ cd build/$type"
-		cd $home/build/$type
+		$showme || echo "Info: installed previous PCP `_pcp_version`"
+		$showme && echo "+ cd $home/$thispkgdir"
+		cd $home/$thispkgdir
 		if _upgrade_$type
 		then
-		    $showme || echo "Info: PCP `_pcp_version` installed"
+		    $showme || echo "Info: upgraded to PCP `_pcp_version`"
 		    if _qa
 		    then
 			$showme || echo "Info: sanity QA passes"
@@ -386,13 +474,15 @@ then
 		$showme || echo "Error: installation of previous version failed"
 	    fi
 	else
-	    $showme || echo "Error: uninstallation of all PCP failed"
+	    $showme || echo "Error: uninstallation of PCP failed"
 	fi
     else
-	echo "Info: build/$type-$lastver missing, skip this test"
+	echo "Info: $home/$lastpkgdir missing, skip this test"
     fi
 else
     echo "Info: cannot get previous version from debian/changelog, skip this test"
 fi
+
+status=0
 
 exit
