qa/admin/list-packages: implement pip logic for -m option
pip3 was a recognized tag in package list files, but there was no
logic to check if a "pip3" package was actually installed, so they
were always reported with -m.

Not an issue for CI because list-packages -m there always uses -x pip3.

Add pyarrow pip3 package for Ubuntu+24.04+x86_64 package list.

I did consider changing "pip3" to "pip", but the former name is welded
into all sorts of workflows and scripts, so I decided against this.

diff --git a/qa/admin/list-packages b/qa/admin/list-packages
--- a/qa/admin/list-packages
+++ b/qa/admin/list-packages
@@ -663,7 +663,7 @@ fi
 
 if $missing
 then
-    # special handling for cpan() packages
+    # special handling for cpan() and pip3() packages
     #
     $very_verbose && cp $tmp.list $tmp.list.before
     rm -f $tmp.sed
@@ -676,13 +676,35 @@ then
 	    echo "/cpan($module)/d" >>$tmp.sed
 	fi
     done
+    grep '^pip3(' $tmp.list \
+    | sed -e 's/pip3(//' -e 's/)//' \
+    | while read module
+    do
+	if which python3 >/dev/null 2>&1
+	then
+	    python=python3
+	elif which pmpython >/dev/null 2>&1
+	then
+	    python=pmpython
+	else
+	    python=''
+	    $very_verbose && echo >&2 "Warning cannot file python"
+	fi
+	if [ -n "$python" ]
+	then
+	    if $python -c "import $module" >/dev/null 2>&1
+	    then
+		echo "/pip3($module)/d" >>$tmp.sed
+	    fi
+	fi
+    done
     if [ -f $tmp.sed ]
     then
 	sed -f $tmp.sed <$tmp.list >$tmp.tmp
 	mv $tmp.tmp $tmp.list
 	if $very_verbose
 	then
-	    echo >&2 "Diffs after cpan() mangling ..."
+	    echo >&2 "Diffs after cpan() and pip3() mangling ..."
 	    diff $tmp.list.before $tmp.list
 	fi
     fi
