package-lists: updates
- CentOS+Stream10 (new)
- Fedora+41
- manifest tweask for stap in QA
- list-packages, changes for dnf

diff --git a/qa/admin/list-packages b/qa/admin/list-packages
--- a/qa/admin/list-packages
+++ b/qa/admin/list-packages
@@ -467,9 +467,9 @@ then
 	    then
 		# note using dnf's system cache, so no metadata refresh
 		#
-		( sudo dnf -C list available; dnf -C list installed ) 2>&1 \
+		sudo dnf -C list 2>&1 \
 		| sed >$tmp.allpkgs \
-		    -e '1,/^[^ ]* Packages/d' \
+		    -e '1,/^[^ ]* [pP]ackages/d' \
 		    -e 's/ .*//' \
 		    -e 's/\.[^.]*$//' \
 		# end
@@ -560,16 +560,14 @@ p
 	echo >&2 "Botch: can't generate tmp.installed for $distro"
 	exit
     fi
-    if [ -f $tmp.allpkgs ]
+    if [ -s $tmp.allpkgs ]
     then
 	sort <$tmp.allpkgs | uniq >$tmp.tmp
 	mv $tmp.tmp $tmp.allpkgs
     else
-	if $check
-	then
-	    echo >&2 "Botch: can't generate tmp.installed for $distro"
-	    exit
-	fi
+	ls -l $tmp.allpkgs
+	echo >&2 "Botch: can't generate tmp.allpkgs for $distro"
+	exit
     fi
 fi
 
