qa/admin/list-packages+package-lists: add support for alternates
CentOS Stream9 has thrown up a case we'd not previously handled.

curl and curl-minimal are alternates ... for CI we're expecting
curl-minimal to already be installed, for my VMs curl may already
be installed and so curl-minimal cannot be installed (without using
yum --allowerasing to replace curl with curl-minimal, which is not
what I want to do).

This is now captured in the packing-list file as:

curl-minimal | curl

so that list-packages will only report curl-minimal (the primary
package) if NEITHER curl-minimal NOR curl are installed.

More than one alternate is possible.

Tags remain at the end of the line, with whitespace separation and
no preceding  "|", as in:

larry | curly | moe not4ci

diff --git a/qa/admin/list-packages b/qa/admin/list-packages
--- a/qa/admin/list-packages
+++ b/qa/admin/list-packages
@@ -108,10 +108,16 @@ End-of-File
 	do
 	    [ "$pkg" = "N/A" ] && continue
 	    pkg_re=`echo "$pkg" | sed -e 's;/;\\\\/;g'`
-	    if awk <$tmp.list '
-BEGIN						{ sts=1 }
-$1 == "'"$pkg"'" || $1 ~ /^'"$pkg_re"'$/	{ sts=0; exit }
-END						{ exit sts }'
+	    if awk -F '|' <$tmp.list '
+BEGIN		{ sts=1 }
+		{ for (i = 1; i <= NF; i++) {
+		    if ($i == "'"$pkg"'" || $i ~ /^'"$pkg_re"'$/) {
+			sts=0
+			exit
+		    }
+		  }
+		}
+END		{ exit sts }'
 	    then
 		# included in list, is it available?
 		#
@@ -141,9 +147,15 @@ END						{ exit sts }'
 		do
 		    skip_pkg_re=`echo "$skip_pkg" | sed -e 's;/;\\\\/;g'`
 		    if echo "$pkg" | awk '
-BEGIN							{ sts=1 }
-$1 == "'"$skip_pkg"'" || $1 ~ /^'"$skip_pkg_re"'$/	{ sts=0; exit }
-END							{ exit sts }'
+BEGIN		{ sts=1 }
+		{ for (i = 1; i <= NF; i++) {
+		    if ($i == "'"$skip_pkg"'" || $i ~ /^'"$skip_pkg_re"'$/) {
+			sts=0
+			exit
+		    }
+		  }
+		}
+END		{ exit sts }'
 		    then
 			$very_verbose && echo >&2 "$pkg ($skip_pkg): skipped"
 			touch $tmp.skipme
@@ -185,6 +197,7 @@ END							{ exit sts }'
     # and are all the packages in the packing list really available?
     #
     sed <$tmp.list -e '/cpan(/d' -e '/pip3(/d' \
+    | tr '|' '\012' \
     | while read pkg
     do
 	avail="`grep "^$pkg\$" <$tmp.allpkgs`"
@@ -538,6 +551,7 @@ fi
 #
 sed -n <$tmp.list >$tmp.tmp \
     -e 's/#.*//' \
+    -e 's/[ 	]*|[ 	]*/|/g' \
     -e 's/[ 	].*//' \
     -e 's/[ 	][ 	]*//g' \
     -e '/./p' \
@@ -603,7 +617,7 @@ then
 	# strip all packages in both $tmp.list and $tmp.installed and
 	# leave the result in $tmp.list
 	#
-	sort <$tmp.list | uniq >$tmp.1
+	tr '|' '\012' <$tmp.list | sort | uniq >$tmp.1
 	sort <$tmp.installed | uniq >$tmp.2
 	if $very_verbose
 	then
@@ -612,7 +626,44 @@ then
 	    echo >&2 "Installed:"
 	    cat $tmp.2 >&2
 	fi
-	comm -23 $tmp.1 $tmp.2 >$tmp.list
+	comm -23 $tmp.1 $tmp.2 >$tmp.tmp
+	# now we may have alternates installed ...
+	#
+	rm -f $tmp.newlist
+	touch $tmp.newlist
+	cat $tmp.tmp \
+	| while read missing
+	do
+	    if grep "^$missing|" $tmp.list >$tmp.out
+	    then
+		# the primary package is missing ... if any of the
+		# alternates are present (not missing) then we're OK
+		#
+		rm -f $tmp.ok
+		cut -d '|' -f 2- <$tmp.out \
+		| tr '|' '\012' \
+		| sed -e '/^$/d' \
+		| while read alt
+		do
+		    if grep "^$alt$" $tmp.2 >/dev/null
+		    then
+			$verbose && echo >&2 "Info: missing: $missing OK because alternate $alt installed"
+			touch $tmp.ok
+			break
+		    fi
+		done
+		[ -f $tmp.ok ] || echo  "$missing" >>$tmp.newlist
+	    elif grep -E "\|$missing($|\|)" $tmp.list >$tmp.out
+	    then
+		# this is an alternate ... only report the primary
+		# (first on line) package if it is also missing
+		#
+		:
+	    else
+		echo  "$missing" >>$tmp.newlist
+	    fi
+	done
+	mv $tmp.newlist $tmp.list
     fi
 fi
 
