qa/admin/pcp-daily: rework reporting around the QA run step

diff --git a/qa/admin/pcp-daily b/qa/admin/pcp-daily
--- a/qa/admin/pcp-daily
+++ b/qa/admin/pcp-daily
@@ -393,18 +393,24 @@ _script_qa()
     cat <<End-of-File
 rm -f *.out.bad
 ./changeversion >/dev/null 2>&1
-if ./check -l $check_what >>\$HOME/daily.log 2>&1
-then
-    echo "Info: QA $what" | tee -a \$HOME/daily.log
-else
-    echo "Error: QA $what failed!" | tee -a \$HOME/daily.log
-    sed -e '/^    [0-9 ]*\$/d' <check.log \
-    | awk '
+echo "Info: QA $check_what starting"
+./check -l $check_what >>\$HOME/daily.log 2>&1
+sts=\$?
+# get last block from check.log ... then get the summary on
+# stdout (not needed in the daily.log, already there)
+sed -e '/^    [0-9 ]*\$/d' <check.log \
+| awk '
 NF == 0	{ txt = ""; next }
 	{ if (txt == "") txt = \$0
 	  else txt = txt "\n" \$0
 	}
-END	{ print txt }' | tee -a \$HOME/daily.log
+END	{ print txt }' \
+| egrep '^(Failures:|Failed|Passed)'
+if [ "\$sts" = 0 ]
+then
+    echo "Info: QA $check_what done" | tee -a \$HOME/daily.log
+else
+    echo "Error: QA $what failed!" | tee -a \$HOME/daily.log
 fi
 End-of-File
 }
