Nest tmp files under mktemp subdirs
src/chart/views/BusyCPU and src/snap/pmsnap.sh currently manipulate
predictable files in /tmp and /var/tmp, allowing for symlink race
vulnerabilities.

diff --git a/src/chart/views/BusyCPU b/src/chart/views/BusyCPU
--- a/src/chart/views/BusyCPU
+++ b/src/chart/views/BusyCPU
@@ -10,24 +10,24 @@
 # a token attempt to make this general
 . /etc/pcp.env
 
-tmp=/var/tmp/$$
-trap "rm -f $tmp.*; exit" 0 1 2 3 15
+tmp=`mktemp -d /var/tmp/pcp.XXXXXXXXX` || exit 1
+trap "rm -rf $tmp; exit" 0 1 2 3 15
 
 # bad stuff ...
 #
 _err()
 {
-    echo "Failed to fetch user mode CPU cycles metrics" >$tmp.msg
-    echo >>$tmp.msg
-    for f in $tmp.err.*
+    echo "Failed to fetch user mode CPU cycles metrics" >$tmp/msg
+    echo >>$tmp/msg
+    for f in $tmp/err.*
     do
-	cat $f >>$tmp.msg
+	cat $f >>$tmp/msg
     done
-    echo >>$tmp.msg
-    echo "Sorry, there is nothing to display." >>$tmp.msg
+    echo >>$tmp/msg
+    echo "Sorry, there is nothing to display." >>$tmp/msg
     pmconfirm >/dev/null \
 	-header "pmchart view construction failure" \
-	-file $tmp.msg \
+	-file $tmp/msg \
 	-icon error \
 	-B "OK"
     exit
@@ -44,10 +44,10 @@ _err()
 #    5. sort and select top 10 processes
 #
 
-# use $tmp.sed to remove this shell and its children from
+# use $tmp/sed to remove this shell and its children from
 # the list of busy processses
 #
-echo "/\[0*$$ /d" >$tmp.sed
+echo "/\[0*$$ /d" >$tmp/sed
 
 # progress notifier while we do our job
 #
@@ -56,7 +56,7 @@ pmquery >/dev/null 2>&1 \
     -header "kmchart view construction" \
     -t "Finding top CPU burners, please wait 5 seconds ..." &
 query=$!
-echo "/\[0*$query /d" >>$tmp.sed
+echo "/\[0*$query /d" >>$tmp/sed
 
 # deal with alternative metric names ...
 #
@@ -65,7 +65,7 @@ fail=true
 for metric in proc.psinfo.utime proc.psusage.utime
 do
     nval=`pmprobe -if $* $metric 2>&1 \
-          | tee $tmp.err.$i \
+          | tee $tmp/err.$i \
 	  | $PCP_AWK_PROG '{print $2}'`
     if [ "$nval" -gt 0 ]
     then
@@ -82,10 +82,10 @@ fi
 
 # note arguments from pmchart are nothing or -h host or -a archive
 #
-if pminfo -F $* $metric >$tmp.1 2>$tmp.err.a
+if pminfo -F $* $metric >$tmp/1 2>$tmp/err.a
 then
     sleep 5
-    if pminfo -F $* $metric >$tmp.2 2>$tmp.err.b
+    if pminfo -F $* $metric >$tmp/2 2>$tmp/err.b
     then
 	:
     else
@@ -100,39 +100,39 @@ fi
 # get pid and user mode CPU cycles usage from lines like
 #	inst [8072 or "08072 rlogin gonzo.melbourne "] value 28
 # and turn them into this
-# $tmp.1.list
+# $tmp/1.list
 #	8072 28
-# $tmp.2.list
+# $tmp/2.list
 #	8072 28 08072 rlogin gonzo.melbourne
 #
 
-sed -f $tmp.sed $tmp.1 \
+sed -f $tmp/sed $tmp/1 \
 | sed -n -e '/inst \[/{
 s/.*inst \[//
 s/ or .* \([0-9][0-9]*\)$/ \1/p
 }' \
-| sort >$tmp.1.list
+| sort >$tmp/1.list
 
 sed -n -e '/inst \[/{
 s/.*inst \[//
 s/or "\(.*\)".* \([0-9][0-9]*\)$/\2 \1/p
-}' $tmp.2 \
-| sort >$tmp.2.list
+}' $tmp/2 \
+| sort >$tmp/2.list
 
 #DEBUG# echo "First list ..." >/tmp/busy.debug
-#DEBUG# cat $tmp.1.list >>/tmp/busy.debug
+#DEBUG# cat $tmp/1.list >>/tmp/busy.debug
 #DEBUG# echo "Second list ..." >>/tmp/busy.debug
-#DEBUG# cat $tmp.2.list >>/tmp/busy.debug
+#DEBUG# cat $tmp/2.list >>/tmp/busy.debug
 
-join $tmp.1.list $tmp.2.list \
+join $tmp/1.list $tmp/2.list \
 | $PCP_AWK_PROG '
 $3 > $2	{ # this process has consumed some user mode CPU cycles
 	  printf "%d",$3-$2
 	  for (i = 4; i <= NF; i++) printf " %s",$i
 	  print""
-	}' >$tmp.found
+	}' >$tmp/found
 
-if [ ! -s $tmp.found ]
+if [ ! -s $tmp/found ]
 then
     # no processes qualify
     #
@@ -156,7 +156,7 @@ End-of-File
 # plot specifications, one per process
 #
 
-sort -nr +0 -1 $tmp.found \
+sort -nr +0 -1 $tmp/found \
 | sed 10q \
 | while read cpuburn inst
 do
