Further work on the revised pmdaoracle implementation
Makes use of the new PCP::PMDA indom cache (hash-based) code,
allows for multiple oracle SIDs, removes the use of the oracle
shipped perl (no PCP::PMDA, of course), many changes to get the
sql requests working, and finally allows pmdaoracle to run with
the oracle user account.

diff --git a/src/pmdas/oracle/Install b/src/pmdas/oracle/Install
--- a/src/pmdas/oracle/Install
+++ b/src/pmdas/oracle/Install
@@ -19,29 +19,34 @@
 . $PCP_SHARE_DIR/lib/pmdaproc.sh
 
 iam=oracle
+user=$iam
+domain=32
 perl_opt=true
 daemon_opt=false
 
-if test -z "${ORACLE_HOME}"; then
-    echo "ORACLE_HOME environment variable is not set"
-    exit 1
-elif test ! -d "${ORACLE_HOME}"; then
-    echo "ORACLE_HOME is set, but it is not a directory"
-    exit 1
-elif text -x "${ORACLE_HOME}/perl/bin/perl"; then
-    echo "ORACLE_HOME is set, but does not contain perl"
-    exit 1
-fi
-
-# Run under the Oracle-shipped Perl, for DBI.
-export PERL5LIB="${PERL5LIB}:${ORACLE_HOME}/perl/lib:${ORACLE_HOME}/perl/lib/site_perl";
-export LD_LIBRARY_PATH="${LD_LIBRARY_PATH}:${ORACLE_HOME}/lib32:${ORACLE_HOME}/lib";
-
-${ORACLE_HOME}/perl/bin/perl -e "use DBI" 2>/dev/null
+perl -e "use DBI" 2>/dev/null
 if test $? -ne 0; then
     echo "Perl database interface (DBI) is not installed"
     exit 1
 fi
+
+su -c id $user >/dev/null 2>&1
+if test $? -ne 0; then
+    echo "Cannot change user to $user, sorry this is fatal"
+    exit 1
+fi
+
+su -c mkdir -p "$PCP_VAR_DIR/config/pmda" 2>/dev/null
+indoms="0 1 2 3 4 5 6 7 8 9 10"
+for indom in $indoms
+do
+    touch "$PCP_VAR_DIR/config/pmda/$domain.$indom" >/dev/null 2>&1
+    if test $? -ne 0; then
+        echo "Cannot create indom persistance files as user $user"
+        echo "Failed on:  $PCP_VAR_DIR/config/pmda/$domain.$indom"
+        exit 1
+    fi
+done
 
 # TODO: need to ask for user/pass and SIDs, write $PCP_VAR_DIR/config/oracle/oracle.conf
 # (unless it exists)
