Improvements to Infiniband build process on Debian platforms
Adds a --with-infiniband configure option, and correct build
dependencies.  Fix a typo in use of a configure-driven-macro
in the code.

Updates to the Install script to simplify things a little,
and adds an Install-time check that the kernel driver can be
found (uses sysfs paths).

diff --git a/src/pmdas/infiniband/Install b/src/pmdas/infiniband/Install
--- a/src/pmdas/infiniband/Install
+++ b/src/pmdas/infiniband/Install
@@ -1,5 +1,6 @@
 #! /bin/sh
 # 
+# Copyright (C) 2013 Red Hat.
 # Copyright (C) 2007,2008 Silicon Graphics, Inc. All Rights Reserved.
 #
 # This program is free software; you can redistribute it and/or modify it
@@ -16,32 +17,30 @@
 . /etc/pcp.env
 . $PCP_SHARE_DIR/lib/pmdaproc.sh
 
-iam=ib
+iam=infiniband
 pmda_interface=3
 daemon_opt=true
 dso_opt=false
 pipe_opt=true
 socket_opt=false
 
-#
-# override "choose mode"
+path=/sys/class/infiniband_mad
+if ! test -d $path; then
+    echo "Kernel lacks Infiniband support - $path directory not found"
+    exit 1
+fi
+
 __choose_mode()
 {
     do_pmda=true
 }
 
-#
-# override "choose IPC method"
 __choose_ipc()
 {
     ipc_type=pipe
-    type="pipe  binary       $PCP_PMDAS_DIR/infiniband/pmda$iam"
+    type="pipe  binary       $PCP_PMDAS_DIR/infiniband/pmdaib"
 }
 
 pmdaSetup
-cat domain.h pmns >$tmp.pmns
-pmns_source=$tmp.pmns
-pmns_name=infiniband
-
 pmdaInstall
 exit 0
