scripts/rebuild: rework for FreeBSD
- make is not called make
- sed -i is not portable

diff --git a/scripts/rebuild b/scripts/rebuild
--- a/scripts/rebuild
+++ b/scripts/rebuild
@@ -12,16 +12,39 @@
 #   once thos apps are rebuilt
 #
 
+tmp=/var/tmp/$$
+sts=1		# failure is the default until the end
+trap "rm -f $tmp.*; exit \$sts" 0 1 2 3 15
+
 if [ ! -d .git ]
 then
     echo "Error: need to be at the top of the git tree, bozo!"
-    exit 1
+    exit
 fi
 
 qa/admin/myconfigure
+if [ -f src/include/pcp.conf ]
+then
+    . src/include/pcp.conf
+else
+    echo "Error: myconfigure failed to make src/include/pcp.conf"
+    exit
+fi
+if [ -z "$PCP_MAKE_PROG" ]
+then
+    echo "Error: myconfigure failed to set \$PCP_MAKE_PROG"
+    exit
+fi
 
 echo "Disable gcc optimization ..."
-sed -i -e '/CFLAGS_OPT/s/-O2/-O0/' src/include/builddefs
+sed -e '/CFLAGS_OPT/s/-O2/-O0/' src/include/builddefs >$tmp.out
+if diff src/include/builddefs $tmp.out >/dev/null
+then
+    echo "Warning: failed to change CFLAGS_OPTS from -O2 to -O0"
+    grep CFLAGS_OPT src/include/builddefs
+else
+    sudo cp $tmp.out src/include/builddefs
+fi
 
 # others that could be added to the list below ...
 # src/libapp src/libpcp_qed src/libpcp_qwt
@@ -33,13 +56,13 @@ for dir in src/libpcp src/libpcp_pmda src/libpcp_pmcd src/libpcp_gui \
 do
     echo "=== $dir ==="
     cd $dir
-    make clean
-    if make
+    $PCP_MAKE_PROG clean
+    if $PCP_MAKE_PROG
     then
-	sudo make install
+	sudo $PCP_MAKE_PROG install
     else
 	echo "Error: make failed!"
-	exit 1
+	exit
     fi
     cd $here
 done
@@ -47,14 +70,16 @@ done
 echo "=== qa ==="
 cd qa
 cd src
-make clean_exec
+$PCP_MAKE_PROG clean_exec
 cd ..
-if make
+if $PCP_MAKE_PROG
 then
     :
 else
     echo "Error: make failed!"
-    exit 1
+    exit
 fi
 
-exit 0
+# success
+#
+sts=0
