libpcp/check-statics - expr(1) snarfoo fix up
Notices this little gem in Logs/pcp after a build on Centos 5.10

expr: warning: unportable BRE: `^.*\\.o$': using `^' as the first character
of the basic regular expression is not portable; it is being ignored

Strictly "^" is not needed for expr(1), although why warning about
it helps man or beast is beyond me.

Also added a guard for no object files while I was here.

diff --git a/src/libpcp/src/check-statics b/src/libpcp/src/check-statics
--- a/src/libpcp/src/check-statics
+++ b/src/libpcp/src/check-statics
@@ -377,6 +377,14 @@ End-of-File
 
 for file in *.o
 do
+    case "$file"
+    in
+	'*.o')
+	    echo "Error: no object files!! Need some drive-by make action?"
+	    exit 1
+	    ;;
+    esac
+    
     if grep "^?*$file\$" $tmp/ctl >/dev/null 2>&1
     then
 	:
@@ -391,7 +399,7 @@ skip_file=false
 cat $tmp/ctl \
 | while read line
 do
-    if expr $line : "^.*\.o$" >/dev/null  # .o file
+    if expr $line : '.*\.o$' >/dev/null  # .o file
     then
 	if [ -n "$obj" ]
 	then
