ci: run full QA on pull requests, save history
* run full QA on pull requests
* save history in test report
* store build and report URL in test report
* show test summary in GitHub workflow run
* show trend: compare results against baseline (last scheduled QA run)
* only fail workflow if any build fails or regressions were found
* do not run CodeQL on PRs (LGTM runs on PRs and uses CodeQL)

diff --git a/.github/workflows/qa.yml b/.github/workflows/qa.yml
--- a/.github/workflows/qa.yml
+++ b/.github/workflows/qa.yml
@@ -1,6 +1,7 @@
 # Runs the entire testsuite
 name: QA
 on:
+  pull_request:
   schedule:
     - cron:  '0 17 * * *'
   workflow_dispatch:
@@ -9,10 +10,12 @@ on:
         description: '(optional) overwrite ./check args (e.g. "-g pmproxy -g pmseries")'
 
 jobs:
-  qa:
+  run_qa:
     name: ${{ matrix.platform }}
-    if: github.repository == 'performancecopilot/pcp' || github.event_name == 'workflow_dispatch'
+    # do not run this workflow on schedule for forks of the main repository
+    if: github.event_name != 'schedule' || github.repository == 'performancecopilot/pcp'
     runs-on: ${{ matrix.os }}
+    # do not mark the workflow as failed if an experimental distro (e.g. rawhide) fails
     continue-on-error: ${{ matrix.experimental }}
     strategy:
       fail-fast: false
@@ -62,7 +65,7 @@ jobs:
       - name: Copy build artifacts
         run: build/ci/ci-run.py ${{ matrix.platform }} artifacts build --path artifacts/build
 
-      - name: Publish build artifacts
+      - name: Upload build artifacts
         # always() is required here to run this step even if the build fails
         # otherwise the platform will be skipped in the test report (it should be flagged as broken)
         if: always()
@@ -79,105 +82,174 @@ jobs:
         run: build/ci/ci-run.py ${{ matrix.platform }} task init_qa
 
       - name: QA
-        run: build/ci/ci-run.py ${{ matrix.platform }} task qa
-        continue-on-error: true
+        run: build/ci/ci-run.py ${{ matrix.platform }} task qa || true
         env:
           PCP_QA_ARGS: ${{ github.event.inputs.pcp_qa_args }}
 
       - name: Copy test results
-        # always() is required here to run this step even if the QA step fails
+        # always() is required here to run this step even if the QA step fails or times out
         if: always() && steps.init_qa.outcome == 'success'
         run: build/ci/ci-run.py ${{ matrix.platform }} artifacts test --path artifacts/test
 
-      - name: Publish test results
+      - name: Upload test results
         if: always() && steps.init_qa.outcome == 'success'
         uses: actions/upload-artifact@v3
         with:
           name: test-${{ matrix.platform }}
           path: artifacts/test
 
-  report:
-    name: Generate Test Report
+  create_report:
+    name: Create Test Report
     # always() is required here to run this job even if any of the QA jobs fails
-    if: always() && (github.repository == 'performancecopilot/pcp' || github.event_name == 'workflow_dispatch')
-    needs: qa
+    if: always() && (github.event_name != 'schedule' || github.repository == 'performancecopilot/pcp')
+    needs: run_qa
     runs-on: ubuntu-latest
+    outputs:
+      report_id: ${{ steps.parse_test_results.outputs.report_id }}
     steps:
       - name: Checkout sources
         uses: actions/checkout@v3
 
-      - name: Setup Allure2
-        run: |
-          wget -q -O allure-commandline.zip https://repo1.maven.org/maven2/io/qameta/allure/allure-commandline/2.14.0/allure-commandline-2.14.0.zip
-          unzip -d /opt allure-commandline.zip
+      - name: Checkout performancecopilot/qa-reports
+        uses: actions/checkout@v3
+        with:
+          repository: performancecopilot/qa-reports
+          path: qa-reports
 
-      - name: Download all artifacts
+      - name: Download artifacts
         uses: actions/download-artifact@v3
         with:
           path: artifacts
 
-      - name: Generate test report
+      - name: Setup Allure2
         run: |
+          wget -q -O allure-commandline.zip https://repo1.maven.org/maven2/io/qameta/allure/allure-commandline/2.17.3/allure-commandline-2.17.3.zip
+          unzip -q -d /opt allure-commandline.zip
+
+      - name: Parse test results
+        id: parse_test_results
+        run: |
+          REPORT_ID=$(date +'%Y%m%d_%H%M%S')-${GITHUB_SHA::8}
+          echo "::set-output name=report_id::${REPORT_ID}"
+
+          # generate Allure inputs
           build/ci/test-report.py \
             --artifacts artifacts \
-            --commit ${GITHUB_SHA} \
             --allure-results allure-results \
-            --summary
+            --summary summary.txt \
+            --source-url "https://github.com/${{ github.repository }}/tree/${GITHUB_SHA}" \
+            --build-name "GitHub Actions Run #${{ github.run_id }}" \
+            --build-url  "https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}" \
+            --report-url "https://${{ github.repository_owner }}.github.io/qa-reports/reports/${REPORT_ID}/"
+
+          cat summary.txt
+
+      - name: Create interactive test report
+        run: |
           cp build/ci/allure/categories.json allure-results
+          if [[ -f qa-reports/reports/latest/history/history.json.gz ]]; then
+            gunzip qa-reports/reports/latest/history/history.json.gz
+            cp -r qa-reports/reports/latest/history allure-results
+          fi
           /opt/allure-*/bin/allure generate
+
+      - name: Create qareport.zip
+        run: |
           cp build/ci/allure/README.md allure-report
           cp build/ci/allure/open_report.sh allure-report
+          gzip allure-report/history/history.json
           # zip report before uploading, because GitHub uploads files in individual HTTP calls
-          cd allure-report && zip -r ../qareport.zip . && cd ..
+          cd allure-report && zip -q -r ../qareport.zip . && cd ..
 
-      - name: Publish test report
+      - name: Check for regressions
+        run: build/ci/check-trend.py --history-trend allure-report/history/history-trend.json
+        continue-on-error: true
+
+      - name: Upload test report
         uses: actions/upload-artifact@v3
         with:
           name: qareport
           path: qareport.zip
 
-      - name: Checkout qa-reports
-        if: github.repository == 'performancecopilot/pcp'
+      - name: Publish test summary
+        uses: actions/github-script@v6
+        continue-on-error: true
+        with:
+          script: |
+            const fs = require('fs');
+            const head_sha = context.payload.pull_request ? context.payload.pull_request.head.sha : context.sha;
+            const response = await github.rest.checks.create({
+              owner: context.repo.owner,
+              repo: context.repo.repo,
+              head_sha,
+              name: 'Test Summary',
+              conclusion: 'success',
+              output: {
+                title: 'Test Summary',
+                summary: '```\n' + fs.readFileSync('summary.txt', 'utf8') + '\n```',
+              }
+            });
+
+  publish_report:
+    name: Publish Test Report
+    # always() is required here to run this job even if any of the QA jobs fails
+    if: always() && (github.event_name == 'schedule' && github.repository == 'performancecopilot/pcp')
+    needs: create_report
+    runs-on: ubuntu-latest
+    steps:
+      - name: Checkout sources
+        uses: actions/checkout@v3
+
+      - name: Checkout performancecopilot/qa-reports
         uses: actions/checkout@v3
         with:
-          repository: ${{ github.repository_owner }}/qa-reports
+          repository: performancecopilot/qa-reports
           path: qa-reports
           ssh-key: ${{ secrets.QA_REPORT_DEPLOY_KEY }}
 
-      - name: Publish test report on GitHub Pages
-        if: github.repository == 'performancecopilot/pcp'
+      - name: Download artifacts
+        uses: actions/download-artifact@v3
+        with:
+          path: artifacts
+
+      - name: Prepare test report on GitHub Pages
         run: |
           rm -rf qa-reports/test-*
           cp -r artifacts/test-* qa-reports/
-
-          current_report=$(date +'%Y%m%d_%H%M%S')-${GITHUB_SHA::8}
-          cp -r allure-report qa-reports/reports/${current_report}
+          unzip -q -d qa-reports/reports/${REPORT_ID} artifacts/qareport/qareport.zip
 
           pushd qa-reports/reports
           rm latest
           rm README.md
           ls -1r | tail -n +16 | xargs --no-run-if-empty rm -r # keep last 15 reports
-          ln -s ${current_report} latest
+          ln -s ${REPORT_ID} latest
           ls -1r -I README.md | awk 'BEGIN {print "# Recent Reports"} { print "## [" $1 "](" $1 "/)" }' > README.md
           popd
+        env:
+          REPORT_ID: ${{ needs.create_report.outputs.report_id }}
 
+      - name: Publish test report on GitHub Pages
+        run: |
           pushd qa-reports
           git config --local user.name "GitHub Actions"
           git config --local user.email "action@github.com"
           git add .
-          git commit --amend -m "Added QA report of ${{ github.repository_owner }}/pcp@${GITHUB_SHA}"
+          git commit --amend -m "Added QA report of ${{ github.repository }}@${GITHUB_SHA}"
           git push -f
+          popd
 
-          echo "::warning::Complete test report is available at https://${{ github.repository_owner }}.github.io/qa-reports/reports/latest/"
+          echo "::warning::Complete test report is available at https://${{ github.repository_owner }}.github.io/qa-reports/reports/${REPORT_ID}/"
+        env:
+          REPORT_ID: ${{ needs.create_report.outputs.report_id }}
 
-      - name: Send test report to Slack
-        if: github.repository == 'performancecopilot/pcp'
+      - name: Send test results to Slack channel
         run: |
           build/ci/test-report.py \
             --artifacts artifacts \
-            --slack-channel ${SLACK_CHANNEL} \
-            --github-run-url "https://github.com/${{ github.repository_owner }}/pcp/actions/runs/${{ github.run_id }}" \
-            --qa-report-url "https://${{ github.repository_owner }}.github.io/qa-reports/reports/latest/"
+            --slack-channel "${SLACK_CHANNEL}" \
+            --build-url  "https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}" \
+            --report-url "https://${{ github.repository_owner }}.github.io/qa-reports/reports/${REPORT_ID}/"
         env:
           SLACK_CHANNEL: C011ERBFQGN
           SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN }}
+          REPORT_ID: ${{ needs.create_report.outputs.report_id }}
