pmdabpftrace: fix label callback, check if bpftrace supports JSON output on PMDA install

diff --git a/src/pmdas/bpftrace/Install b/src/pmdas/bpftrace/Install
--- a/src/pmdas/bpftrace/Install
+++ b/src/pmdas/bpftrace/Install
@@ -18,6 +18,11 @@
 . $PCP_DIR/etc/pcp.env
 . $PCP_SHARE_DIR/lib/pmdaproc.sh
 
+if ! bpftrace --help 2>&1 | grep '\-f.*json' > /dev/null; then
+    echo "The currently installed version of bpftrace doesn't support JSON output, which is required by this PMDA."
+    exit 1
+fi
+
 iam=bpftrace
 domain=151
 python_opt=true
