qa/019 - more exposed to proc PMDA variants
This test produces different results when the proc PMDA is
installed as a daemon (not a DSO) ... add variant output file and
more complicated logic to select the correct expected output file.

diff --git a/qa/019 b/qa/019
--- a/qa/019
+++ b/qa/019
@@ -20,7 +20,27 @@ then
 	#
 	if pminfo proc.nprocs >/dev/null 2>&1
 	then
-	    ln $seq.linux.2 $seq.out
+	    # available, but if not a DSO agent, then pminfo -L will
+	    # know about the metric, but not find the PMDA
+	    #
+	    type=`pminfo -f pmcd.agent.type | sed -n -e '/"proc"/{
+s/.*value //
+p
+}'`
+	    case "$type"
+	    in
+		0)  # DSO
+		    ln $seq.linux.2 $seq.out
+		    ;;
+		2|4)# daemon
+		    ln $seq.linux.4 $seq.out
+		    ;;
+		*)
+		    echo "Botch ... don't understand proc PMDA type ($type)"
+		    pminfo -f pmcd.agent.type
+		    exit 1
+		    ;;
+	    esac
 	else
 	    ln $seq.linux.3 $seq.out
 	fi
@@ -32,7 +52,8 @@ elif [ $PCP_PLATFORM = solaris ]
 then
     ln $seq.solaris $seq.out
 else
-    echo "Warning: no validated output for $PCP_PLATFORM"
+    echo "Error: no validated output for $PCP_PLATFORM"
+    exit 1
 fi
 
 echo "QA output created by $seq"
