qa: major refactor - part 1
This commit makes fundamental changes to the QA infrastructure.

1. The confusing use of both $seq.full and $here/$seq.full that
   depends on when and if a QA test does a cd(1) is gone and
   replaced by a new global $seq_full.

2. When tests need to access files local to the QA directories these
   files are copied from $here/... to $tmp ... this is important for
   cases where the QA test is running stuff as user $PCP_USER (e.g.
   pmcd or pmlogger scripts), but $here is below the home directory
   of the user running the QA test scripts and this home directory
   is mode 700 (making the files unreadable by user $PCP_USER).

3. Most of the exit(1) calls in the common.* scripts are gone, and
   the associated functions now return 0 for success else 1 for
   failure.  This moves responsibility for what to in the event
   of failure back to the caller, and avoids the mess we had where
   exit(1) was being called sometimes from the QA test mainline and
   sometimes from the exit handler via a trap ...  besides risking
   leaving the PCP components in a bad state on failure this also
   resulting in multiple turds (thousands of 'em on bozo when I looked)
   accumulating in /var/tmp/$seq-$$ because the "$sudo rm -rf $tmp
   $tmp.*" was not being reliably run.

4. Some routines in the common.* scripts that simply returned on
   both error and non-error paths now return 1 and return 0
   respectively, e.g. _wait_for_pmie(), _wait_pmcd_end(),
   _get_word_size(), _get_endian(), _find_free_port(),
   _wait_for_port(), ...

5. A new _exit() method sets $status and calls exit(1) ... this
   is a convenience function that works well with the current
   trap "...; exit \$status" ... usage.

6. A new _path_readable() method that takes a user name and path
   as arguments and returns 0 if that user can read that path,
   else returns 1.

1., 3. and 4. are pervasive, so I've written a new qa/refactor script
to do as much of the work as I can safely automate and warn about
things I cannot safely change automatically.  Some scripts are now
annotated with # refactor-ok or # refactor-all-ok to mean that refactor
should ignore the line or the file, respectively.

In this commit refactor has been run across tests 000-299, and others
will come in follow-up commits.

diff --git a/qa/110 b/qa/110
--- a/qa/110
+++ b/qa/110
@@ -81,33 +81,32 @@ _filter()
 
 _full()
 {
-    echo "--- pmcd.conf ---" >>$here/$seq.full
-    cat $PCP_PMCDCONF_PATH >>$here/$seq.full
-    echo "--- pmcd.log ---" >>$here/$seq.full
-    cat $PCP_PMCDLOG_PATH >>$here/$seq.full
-    echo "--- root.log ---" >>$here/$seq.full
+    echo "--- pmcd.conf ---" >>$seq_full
+    cat $PCP_PMCDCONF_PATH >>$seq_full
+    echo "--- pmcd.log ---" >>$seq_full
+    cat $PCP_PMCDLOG_PATH >>$seq_full
+    echo "--- root.log ---" >>$seq_full
     if [ -f $ROOT_LOG_PATH ]
     then
-	cat $ROOT_LOG_PATH >>$here/$seq.full
+	cat $ROOT_LOG_PATH >>$seq_full
     else
-	echo "$ROOT_LOG_PATH: file not found" >>$here/$seq.full
+	echo "$ROOT_LOG_PATH: file not found" >>$seq_full
     fi
-    echo "--- simple.log ---" >>$here/$seq.full
+    echo "--- simple.log ---" >>$seq_full
     if [ -f $PMDA_LOG_PATH ]
     then
-	cat $PMDA_LOG_PATH >>$here/$seq.full
+	cat $PMDA_LOG_PATH >>$seq_full
     else
-	echo "$PMDA_LOG_PATH: file not found" >>$here/$seq.full
+	echo "$PMDA_LOG_PATH: file not found" >>$seq_full
     fi
-    echo >>$here/$seq.full
+    echo >>$seq_full
 }
 
-rm -f $seq.full
 
 # pmlogger may get confused by pmcd reconfig ... safest to stop it
 # first, and restart it in cleanup()
 #
-_service pmlogger stop >>$here/$seq.full
+if ! _service pmlogger stop >>$seq_full; then _exit 1; fi
 
 # real QA test starts here
 home=$PCP_PMDAS_DIR
@@ -139,7 +138,7 @@ $sudo ./Remove >/dev/null 2>&1
 
 echo
 echo "=== pipe daemon agent ==="
-echo "=== pipe daemon agent ===" >>$here/$seq.full
+echo "=== pipe daemon agent ===" >>$seq_full
 $sudo ./Remove >$tmp.out 2>&1
 $sudo rm -f $PMDA_LOG_PATH
 echo 'daemon
@@ -157,23 +156,23 @@ fi
 
 echo
 echo "=== Unix socket daemon agent ==="
-echo "=== Unix socket daemon agent ===" >>$here/$seq.full
+echo "=== Unix socket daemon agent ===" >>$seq_full
 $sudo ./Remove >$tmp.out 2>&1
 echo 'daemon
 socket
 Unix
 '"$tmp.fifo-1" | $sudo ./Install -e >>$tmp.out 2>&1
-echo "+++ fifo-1 PMDA log +++" >>$here/$seq.full
-cat $PMDA_LOG_PATH >>$here/$seq.full
-ls -ld "$tmp.fifo-1" `dirname "$tmp.fifo-1"` >>$here/$seq.full
+echo "+++ fifo-1 PMDA log +++" >>$seq_full
+cat $PMDA_LOG_PATH >>$seq_full
+ls -ld "$tmp.fifo-1" `dirname "$tmp.fifo-1"` >>$seq_full
 $sudo rm -f $PMDA_LOG_PATH
 echo 'daemon
 socket
 Unix
 '"$tmp.fifo-2" | $sudo ./Install -e >>$tmp.out 2>&1
-echo "+++ fifo-2 PMDA log +++" >>$here/$seq.full
-cat $PMDA_LOG_PATH >>$here/$seq.full
-ls -ld "$tmp.fifo-2" `dirname "$tmp.fifo-2"` >>$here/$seq.full
+echo "+++ fifo-2 PMDA log +++" >>$seq_full
+cat $PMDA_LOG_PATH >>$seq_full
+ls -ld "$tmp.fifo-2" `dirname "$tmp.fifo-2"` >>$seq_full
 _full
 
 _filter <$tmp.out
@@ -187,7 +186,7 @@ fi
 
 echo
 echo "=== Internet socket daemon agent ==="
-echo "=== Internet socket daemon agent ===" >>$here/$seq.full
+echo "=== Internet socket daemon agent ===" >>$seq_full
 $sudo ./Remove >$tmp.out 2>&1
 
 # pick a tcp port that is not in use
@@ -225,7 +224,7 @@ fi
 
 echo
 echo "=== dso agent ==="
-echo "=== dso agent ===" >>$here/$seq.full
+echo "=== dso agent ===" >>$seq_full
 $sudo ./Remove >$tmp.out 2>&1
 echo dso | $sudo ./Install -e >>$tmp.out 2>&1
 $sudo rm -f $PMDA_LOG_PATH
diff --git a/qa/244 b/qa/244
--- a/qa/244
+++ b/qa/244
@@ -24,7 +24,7 @@ fi
 _filter_log()
 {
     sleep 3
-    tee -a $here/$seq.full <./pmcd.log \
+    tee -a $seq_full <./pmcd.log \
     | _filter_pmcd_log \
     | sed \
 	-e '/^DATA: from client/d' \
@@ -84,9 +84,9 @@ $1 == "cisco"		{ $4 = "fd_in"; $5 = "fd_out"
 	-e 's/_o32/_SIZE/' \
 	-e 's/_n32/_SIZE/' \
 	-e 's/_64/_SIZE/' \
-	-e "s;$here/src/;;" \
+	-e "s;$tmp\.;;" \
 	-e '/Cleanup "fake_linux" agent (dom 60): unconfigured/q' \
-	#end
+    #end
 }
 
 CONFIG=$PCP_PMCDCONF_PATH
@@ -100,7 +100,6 @@ status=1
 #
 NAMESPACE="-n $here/src/root_irix"
 
-rm -rf $tmp $tmp.* $seq.full
 mkdir $tmp
 chmod ugo+rwx $tmp
 cd $tmp
@@ -113,8 +112,8 @@ _cleanup()
     cd $here
     if $_needclean
     then
-	echo "--- stderr from tmp.sh ---" >>$seq.full
-	cat $tmp.full >>$seq.full
+	echo "--- stderr from tmp.sh ---" >>$seq_full
+	cat $tmp.full >>$seq_full
 	_needclean=false
 	$signal -s TERM $pmcd
 	sleep 1
@@ -131,12 +130,12 @@ _cleanup()
 	_wait_for_pmcd
 	_wait_for_pmlogger
 	pmprobe pmcd.control.debug
-	sleepers=`$PCP_PS_PROG $PCP_PS_ALL_FLAGS | grep '/[d]umb_pmda' | $PCP_AWK_PROG '$3 == 1 { print $2 }'`
+	sleepers=`$PCP_PS_PROG $PCP_PS_ALL_FLAGS | grep '\.[d]umb_pmda' | $PCP_AWK_PROG '$3 == 1 { print $2 }'`
 	[ ! -z "$sleepers" ] && $sudo $signal -s KILL $sleepers
 	if $pmie_was_running
 	then
 	    _restore_auto_restart pmie
-	    _service pmie start >>$here/$seq.full 2>&1
+	    _service pmie start >>$seq_full 2>&1
 	fi
     fi
     $sudo rm -rf $tmp $tmp.*
@@ -151,15 +150,20 @@ if [ -f $PCP_RUN_DIR/pmie.pid ]
 then
     pmie_was_running=true
     _stop_auto_restart pmie
-    _service pmie stop >>$here/$seq.full 2>&1
+    if ! _service pmie stop >>$seq_full 2>&1; then _exit 1; fi
 fi
 
 # real QA test starts here
 
-_service pcp stop | _filter_pcp_stop
+if ! _service pcp stop; then _exit 1; fi \
+| _filter_pcp_stop
 $sudo $signal -a pmgadgets pmchart pmview >/dev/null 2>&1
-_disable_loggers
+_disable_loggers || _exit 1
 $sudo $signal -a -s TERM pmie >/dev/null 2>&1
+
+# need PMDA executable someplace user $PCP_USER (pmcd) can read it
+#
+cp $here/src/dumb_pmda $tmp.dumb_pmda
 
 # Make our own version of pmcd.conf with dummy agents that will time out.
 # Copy the pmcd PMDA from the original pmcd.conf so that we can check pmcd's
@@ -167,10 +171,10 @@ $sudo $signal -a -s TERM pmie >/dev/null 2>&1
 # NOTE: none of the domains should clash with the pmcd PMDA (domain 2) or the
 # sample agent (domain 254).  These agents will be appended to the file.
 #
-echo "fake_irix 1 pipe binary $here/src/dumb_pmda -d 1 fake_irix" >$NEWCONFIG
-echo "fake_sampledso 30 pipe binary $here/src/dumb_pmda -d 30 fake_sampledso" >>$NEWCONFIG
-echo "fake_cisco 5 pipe binary $here/src/dumb_pmda -d 5 fake_cisco" >>$NEWCONFIG
-echo "fake_linux 60 pipe binary $here/src/dumb_pmda -d 60 fake_linux" >>$NEWCONFIG
+echo "fake_irix 1 pipe binary $tmp.dumb_pmda -d 1 fake_irix" >$NEWCONFIG
+echo "fake_sampledso 30 pipe binary $tmp.dumb_pmda -d 30 fake_sampledso" >>$NEWCONFIG
+echo "fake_cisco 5 pipe binary $tmp.dumb_pmda -d 5 fake_cisco" >>$NEWCONFIG
+echo "fake_linux 60 pipe binary $tmp.dumb_pmda -d 60 fake_linux" >>$NEWCONFIG
 grep pmda_pmcd $CONFIGSAVE | sed -e 's/[ 	][ 	]*/ /g' -e 's/[ 	]*$//' >>$NEWCONFIG
 echo "[access]" >>$NEWCONFIG
 echo "allow localhost : all;" >>$NEWCONFIG
@@ -181,7 +185,8 @@ echo '$PCP_PMCDCONF_PATH contains:'
 echo '<BEGIN>'
 sed <$CONFIG \
     -e '/^pmcd/s; [^ ]*pmda_pmcd.'$DSO_SUFFIX'; ...pmda_pmcd.$DSO_SUFFIX;' \
-    -e "s;$here/src/;;"
+    -e "s;$tmp\.;;" \
+# end
 echo '<END>'
 
 # Use a different port to avoid interference by remote monitors
@@ -197,11 +202,11 @@ username=`id -u -n`
 sudoopts="-u $username"
 id pcp >/dev/null 2>&1 && sudoopts="-u pcp"
 
-echo "sudoopts=$sudoopts" >>$here/$seq.full
-echo "PMCD_PORT=$PMCD_PORT" >>$here/$seq.full
-echo "PMCD_SOCKET=$PMCD_SOCKET" >>$here/$seq.full
-ls -ld $PCP_RUN_DIR >>$here/$seq.full
-ls -l $PCP_RUN_DIR >>$here/$seq.full
+echo "sudoopts=$sudoopts" >>$seq_full
+echo "PMCD_PORT=$PMCD_PORT" >>$seq_full
+echo "PMCD_SOCKET=$PMCD_SOCKET" >>$seq_full
+ls -ld $PCP_RUN_DIR >>$seq_full
+ls -l $PCP_RUN_DIR >>$seq_full
 
 cat >$tmp.sh <<END
 #!/bin/sh
@@ -212,13 +217,13 @@ $PCP_PMCD_PROG -f -t 2 2>>$tmp.full &
 echo \$!
 END
 pmcd=`$sudo $sudoopts sh $tmp.sh`
-echo "pmcd=$pmcd" >>$here/$seq.full
-ls -l $PCP_RUN_DIR >>$here/$seq.full
+echo "pmcd=$pmcd" >>$seq_full
+ls -l $PCP_RUN_DIR >>$seq_full
 
 # complete V1 PMDA timeouts, then wait for pmcd
 #
 sleep 12
-_wait_for_pmcd
+_wait_for_pmcd || _exit 1
 
 # If agent not restarted then both messages will be "no agent for domain..."
 #
@@ -243,11 +248,12 @@ echo '<BEGIN>'
 sed <$CONFIG \
     -e '/^pmcd/s; [^ ]*pmda_pmcd.'$DSO_SUFFIX'; ...pmda_pmcd.$DSO_SUFFIX;' \
     -e '/^sample/s; [^ ]*pmdasample; ...pmdasample;' \
-    -e "s;$here/src/;;"
+    -e "s;$tmp\.;;" \
+# end
 echo '<END>'
 
 $signal -s HUP $pmcd
-_wait_for_pmcd
+_wait_for_pmcd || _exit 1
 
 echo "Expect \"Unknown or illegal metric identifier\" ..."
 pminfo $NAMESPACE -d sampledso.control
@@ -260,7 +266,7 @@ pmprobe $NAMESPACE -v sample.bin
 # restart PMCD (the sample agent's config line will be unchanged) and check
 # that the sample agent has the same PID.
 # The bogus fake_sampledso agent should have been terminated because it is
-# no longer in the config file. 
+# no longer in the config file.
 # That isn't enough to terminate the sleep agent.
 #
 echo
@@ -269,14 +275,14 @@ sample=`pminfo $NAMESPACE -f sample.daemon_pid | $PCP_AWK_PROG '
 $1 == "value"	{ print $2 }
 '`
 sleep 1
-$PCP_PS_PROG $PCP_PS_ALL_FLAGS | grep '/[d]umb_pmda' | grep fake_cisco >/dev/null || echo "Error: phony fake_cisco agent died prematurely"
+$PCP_PS_PROG $PCP_PS_ALL_FLAGS | grep '\.[d]umb_pmda' | grep fake_cisco >/dev/null || echo "Error: phony fake_cisco agent died prematurely"
 
 $sudo cp $CONFIGSAVE $CONFIG
 
 $signal -s HUP $pmcd
-_wait_for_pmcd
+_wait_for_pmcd || _exit 1
 
-$PCP_PS_PROG $PCP_PS_ALL_FLAGS | grep '/[d]umb_pmda' | grep fake_cisco >/dev/null && echo "Error: phony fake_cisco agent still lives!"
+$PCP_PS_PROG $PCP_PS_ALL_FLAGS | grep '\.[d]umb_pmda' | grep fake_cisco >/dev/null && echo "Error: phony fake_cisco agent still lives!"
 
 # Generate a PDU into the domain where the fake_sampledso agent used to be (#30 is
 # assumed to be the sampledso PMDA)
