pmdaopenmetrics: rename prometheus agent to openmetrics
Following upstream efforts (openmetrics.io) on standardising the
prometheus output format - change the name of the PMDA and these
metrics for PCP v5 following extensive discussions.

Also tweak the pmproxy openmetrics format providing instance IDs
and names for future work in this space.

diff --git a/qa/1120 b/qa/1120
--- a/qa/1120
+++ b/qa/1120
@@ -1,6 +1,6 @@
 #!/bin/sh
 # PCP QA Test No. 1120
-# pmdaprometheus scalability testing
+# pmdaopenmetrics scalability testing
 # specifically scaling amount of turnover between nodes
 #
 # Copyright (c) 2017 Red Hat.  All Rights Reserved.
@@ -9,15 +9,15 @@
 seq=`basename $0`
 echo "QA output created by $seq"
 
-. ./common.prometheus
+. ./common.openmetrics
 
-_pmdaprometheus_check || _notrun "prometheus pmda and/or load generator not installed"
+_pmdaopenmetrics_check || _notrun "openmetrics pmda and/or load generator not installed"
 _have_python266 && _notrun "python load generator does not currently work with python 2.6.6"
 
 status=1	# failure is the default!
 $sudo rm -rf $tmp $tmp.* $seq.full
 totalendpoints=100 #total queue to work through
-endpoints=10 #prometheus endpoints
+endpoints=10 #openmetrics endpoints
 iterations=2
 metrics=10
 instances=10
@@ -31,10 +31,10 @@ _cleanup()
 	pid=""
     fi
 
-    echo "=== prometheus PMDA log ===" >>$here/$seq.full
-    if [ -f $PCP_LOG_DIR/pmcd/prometheus.log ]
+    echo "=== openmetrics PMDA log ===" >>$here/$seq.full
+    if [ -f $PCP_LOG_DIR/pmcd/openmetrics.log ]
     then
-	cat $PCP_LOG_DIR/pmcd/prometheus.log >>$here/$seq.full
+	cat $PCP_LOG_DIR/pmcd/openmetrics.log >>$here/$seq.full
     else
 	echo "Error: PMDA log file is missing" >>$here/$seq.full
     fi
@@ -52,17 +52,17 @@ _cleanup()
     return 0
 }
 
-trap "_cleanup; _pmdaprometheus_restore_config >>$here/$seq.full; exit \$status" 0 1 2 3 15
+trap "_cleanup; _pmdaopenmetrics_restore_config >>$here/$seq.full; exit \$status" 0 1 2 3 15
 
-_pmdaprometheus_save_config
-_pmdaprometheus_install
+_pmdaopenmetrics_save_config
+_pmdaopenmetrics_install
 
 port=`_find_free_port 10000`
 echo "port=$port" >>$here/$seq.full
 
-$python $here/prometheus/prometheus_endpoint.python \
+$python $here/openmetrics/openmetrics_endpoint.python \
 	--port=$port \
-	--output=$PCP_PMDAS_DIR/prometheus/config.d/ \
+	--output=$PCP_PMDAS_DIR/openmetrics/config.d/ \
 	--total $totalendpoints \
 	--endpoints $endpoints \
 	--metrics $metrics \
@@ -70,13 +70,13 @@ $python $here/prometheus/prometheus_endpoint.python \
 	--limit $iterations >$tmp.endpoint 2>&1 &
 pid=$!
 
-if ! _pmdaprometheus_wait_for_metric prometheus.source2
+if ! _pmdaopenmetrics_wait_for_metric openmetrics.source2
 then
     status=1
     exit
 fi
 
-if pminfo -v `pminfo prometheus.source0 | LC_COLLATE=POSIX sort` > $tmp.info 2> $tmp.err
+if pminfo -v `pminfo openmetrics.source0 | LC_COLLATE=POSIX sort` > $tmp.info 2> $tmp.err
 then
     :
 else
@@ -85,21 +85,21 @@ else
 fi
 cat $tmp.info $tmp.err
 
-if pminfo -fd `pminfo prometheus.source1 | LC_COLLATE=POSIX sort` > $tmp.info 2>$tmp.err
+if pminfo -fd `pminfo openmetrics.source1 | LC_COLLATE=POSIX sort` > $tmp.info 2>$tmp.err
    then
-    echo "Fetch and desc prometheus metrics: success"
+    echo "Fetch and desc openmetrics metrics: success"
     cat $tmp.info
 else
-    echo "Fetch and desc prometheus metrics: failed"
+    echo "Fetch and desc openmetrics metrics: failed"
     cat $tmp.err
 fi
 for i in `seq 2 1 99`
 do
-    pminfo -f `pminfo prometheus.source$i | LC_COLLATE=POSIX sort`
+    pminfo -f `pminfo openmetrics.source$i | LC_COLLATE=POSIX sort`
     sleep 0.5
 done
 
-_pmdaprometheus_remove
+_pmdaopenmetrics_remove
 
 # success, all done
 status=0
