qa: major refactor - part 4
As fate would have it, part 3 was not the last ... it missed a bunch
of $seq.full and $home/$seq.full tokens that need to be converted
to $seq_full.

diff --git a/qa/115 b/qa/115
--- a/qa/115
+++ b/qa/115
@@ -32,9 +32,9 @@ _cleanup()
     $sudo rm -rf $tmp.nogo $tmp.locker
     for file in $tmp.*
     do
-	echo >>$here/$seq.full
-	echo "=== $file ===" >>$here/$seq.full
-	cat $file >>$here/$seq.full
+	echo >>$seq_full
+	echo "=== $file ===" >>$seq_full
+	cat $file >>$seq_full
     done
     _restore_auto_restart pmcd
     [ "$pmie_state" = on ] && _change_config pmie on
@@ -44,11 +44,11 @@ _cleanup()
 	#
 	sleep 2
 	_restore_auto_restart pmie
-	_service pmie start >>$here/$seq.full 2>&1
+	_service pmie start >>$seq_full 2>&1
 	_wait_for_pmie
     else
-	_service pmie stop >>$here/$seq.full 2>&1
-	$sudo $PCP_BINADM_DIR/pmsignal -a -s TERM pmie >>$here/$seq.full 2>&1
+	_service pmie stop >>$seq_full 2>&1
+	$sudo $PCP_BINADM_DIR/pmsignal -a -s TERM pmie >>$seq_full 2>&1
 	_wait_pmie_end
     fi
     $sudo rm -f $tmp.*
@@ -92,7 +92,7 @@ tmpdir=`dirname $tmp`
 #
 _filter()
 {
-    tee -a $here/$seq.full \
+    tee -a $seq_full \
     | sed \
 	-e "s;$tmp;TMP;g" \
 	-e "s;$tmpdir;TMPDIR;g" \
@@ -223,11 +223,11 @@ _change_config pmie off || _exit 1
 $sudo rm -f $PCP_TMP_DIR/pmie/*
 
 _count_pmies
-echo "pmie count at start of QA testing: $?" | tee -a $here/$seq.full
+echo "pmie count at start of QA testing: $?" | tee -a $seq_full
 echo
 
-echo === check default install operation === | tee -a $here/$seq.full
-if ! _service pmie restart 2>&1; then _exit 1; fi | tee -a $here/$seq.full | _filter_pmie_start
+echo === check default install operation === | tee -a $seq_full
+if ! _service pmie restart 2>&1; then _exit 1; fi | tee -a $seq_full | _filter_pmie_start
 _wait_for_pmie || _exit 1
 _count_pmies
 # chkconfig no longer controls start-ability, expect non-zero
@@ -237,11 +237,11 @@ echo
 #
 sleep 2
 
-echo === check for missing control file === | tee -a $here/$seq.full
+echo === check for missing control file === | tee -a $seq_full
 _change_config pmie off || _exit 1
 $sudo rm -f $PCP_PMIECONTROL_PATH
 _change_config pmie on || _exit 1
-if ! _service pmie restart 2>&1; then _exit 1; fi | tee -a $here/$seq.full | _filter_pmie_start | _filter
+if ! _service pmie restart 2>&1; then _exit 1; fi | tee -a $seq_full | _filter_pmie_start | _filter
 _count_pmies
 echo "pmie count after attempt without control file: $?"
 echo
@@ -249,15 +249,15 @@ echo
 #
 sleep 2
 
-echo === check pmie_check and custom configs === | tee -a $here/$seq.full
-echo "--- v1.0 ---" | tee -a $here/$seq.full
+echo === check pmie_check and custom configs === | tee -a $seq_full
+echo "--- v1.0 ---" | tee -a $seq_full
 pmie_check -V -V -N -c $tmp.control.v1.0 >$tmp.log 2>&1
 cat $tmp.log | _filter
 rm -f $tmp.log
 # don't bother counting pmie processes, as -N is used above!
 #
 echo
-echo "--- v1.1 ---" | tee -a $here/$seq.full
+echo "--- v1.1 ---" | tee -a $seq_full
 pmie_check -V -V -N -c $tmp.control.v1.1 >$tmp.log 2>&1
 cat $tmp.log | _filter
 rm -f $tmp.log
@@ -265,8 +265,8 @@ rm -f $tmp.log
 #
 echo
 
-echo "=== warnings ... ===" | tee -a $here/$seq.full
-echo "--- stale lock file ---" | tee -a $here/$seq.full
+echo "=== warnings ... ===" | tee -a $seq_full
+echo "--- stale lock file ---" | tee -a $seq_full
 case=1
 cat >$tmp.warning.$case << EOF
 \$version=1.1
@@ -278,7 +278,7 @@ pmie_check -V -V -N -c $tmp.warning.$case >$tmp.warning.$case.log 2>&1
 cat $tmp.warning.$case.log | _filter
 rm -f $tmp.warning.$case.log
 echo
-echo "--- existing lock file ---" | tee -a $here/$seq.full
+echo "--- existing lock file ---" | tee -a $seq_full
 case=`expr $case + 1`
 cat >$tmp.warning.$case << EOF
 \$version=1.1
@@ -292,7 +292,7 @@ $PCP_PS_PROG $PCP_PS_ALL_FLAGS | grep -E '[P]PID|/[p]mie( |$)' >>$seq_full
 cat $tmp.warning.$case.log | _filter
 rm -f $tmp.warning.$case.log
 echo
-echo "--- can't create lock file ---" | tee -a $here/$seq.full
+echo "--- can't create lock file ---" | tee -a $seq_full
 case=`expr $case + 1`
 cat >$tmp.warning.$case << EOF
 \$version=1.1
@@ -304,7 +304,7 @@ cat $tmp.warning.$case.log | _filter
 rm -f $tmp.warning.$case.log
 $sudo rm -rf $tmp.locker
 echo
-echo "--- bad in-line shell commands ---" | tee -a $here/$seq.full
+echo "--- bad in-line shell commands ---" | tee -a $seq_full
 case=`expr $case + 1`
 cat >$tmp.warning.$case << EOF
 \$version=1.1
@@ -317,7 +317,7 @@ pmie_check -V -V -N -c $tmp.warning.$case >$tmp.warning.$case.log 2>&1
 cat $tmp.warning.$case.log | _filter
 rm -f $tmp.warning.$case.log
 echo
-echo "--- missing \$version but really v1.1 ... original control.local issue ---" | tee -a $here/$seq.full
+echo "--- missing \$version but really v1.1 ... original control.local issue ---" | tee -a $seq_full
 case=`expr $case + 1`
 cat >$tmp.warning.$case << EOF
 LOCALHOSTNAME   n n $tmp.ok.$case -c $tmp.conf
@@ -327,8 +327,8 @@ cat $tmp.warning.$case.log | _filter
 rm -f $tmp.warning.$case.log
 echo
 
-echo "=== errors ... ===" | tee -a $here/$seq.full
-echo "--- bad version ---" | tee -a $here/$seq.full
+echo "=== errors ... ===" | tee -a $seq_full
+echo "--- bad version ---" | tee -a $seq_full
 case=1
 cat >$tmp.error.$case << EOF
 \$version=0.0
@@ -339,7 +339,7 @@ cat $tmp.bad.$case.log | _filter
 rm -f $tmp.bad.$case.log
 echo
 case=`expr $case + 1`
-echo "--- v1.0 socks != y|n ---" | tee -a $here/$seq.full
+echo "--- v1.0 socks != y|n ---" | tee -a $seq_full
 cat >$tmp.error.$case << EOF
 \$version=1.0
 LOCALHOSTNAME   x $tmp.bad.$case -c $tmp.conf
@@ -349,7 +349,7 @@ cat $tmp.bad.$case.log | _filter
 rm -f $tmp.bad.$case.log
 echo
 case=`expr $case + 1`
-echo "--- v1.1 socks != y|n ---" | tee -a $here/$seq.full
+echo "--- v1.1 socks != y|n ---" | tee -a $seq_full
 cat >$tmp.error.$case << EOF
 \$version=1.1
 LOCALHOSTNAME   n x $tmp.bad.$case -c $tmp.conf
@@ -359,7 +359,7 @@ cat $tmp.bad.$case.log | _filter
 rm -f $tmp.bad.$case.log
 echo
 case=`expr $case + 1`
-echo "--- v1.1 primary != y|n ---" | tee -a $here/$seq.full
+echo "--- v1.1 primary != y|n ---" | tee -a $seq_full
 cat >$tmp.error.$case << EOF
 \$version=1.1
 LOCALHOSTNAME   x n $tmp.bad.$case -c $tmp.conf
@@ -369,7 +369,7 @@ cat $tmp.bad.$case.log | _filter
 rm -f $tmp.bad.$case.log
 echo
 case=`expr $case + 1`
-echo "--- v1.0 insufficient fields ---" | tee -a $here/$seq.full
+echo "--- v1.0 insufficient fields ---" | tee -a $seq_full
 cat >$tmp.error.$case << EOF
 \$version=1.0
 LOCALHOSTNAME   n $tmp.bad.$case
@@ -379,7 +379,7 @@ cat $tmp.bad.$case.log | _filter
 rm -f $tmp.bad.$case.log
 echo
 case=`expr $case + 1`
-echo "--- v1.1 insufficient fields ---" | tee -a $here/$seq.full
+echo "--- v1.1 insufficient fields ---" | tee -a $seq_full
 cat >$tmp.error.$case << EOF
 \$version=1.1
 LOCALHOSTNAME   n n $tmp.bad.$case
@@ -391,7 +391,7 @@ echo
 mkdir $tmp.nogo
 chmod 000 $tmp.nogo
 case=`expr $case + 1`
-echo "--- can't create dir for logfile ---" | tee -a $here/$seq.full
+echo "--- can't create dir for logfile ---" | tee -a $seq_full
 cat >$tmp.error.$case << EOF
 \$version=1.1
 LOCALHOSTNAME   n n $tmp.nogo/subdir/bad.$case -c $tmp.conf
@@ -401,7 +401,7 @@ cat $tmp.bad.$case.log | _filter
 rm -f $tmp.bad.$case.log
 echo
 case=`expr $case + 1`
-echo "--- can't chdir to dir for logfile ---" | tee -a $here/$seq.full
+echo "--- can't chdir to dir for logfile ---" | tee -a $seq_full
 cat >$tmp.error.$case << EOF
 \$version=1.1
 LOCALHOSTNAME   n n $tmp.nogo/bad.$case -c $tmp.conf
diff --git a/qa/1672 b/qa/1672
--- a/qa/1672
+++ b/qa/1672
@@ -100,34 +100,34 @@ $sudo chown pcp:pcp $PCP_SASLCONF_DIR/pmcd.conf
 ls -l $PCP_SASLCONF_DIR/pmcd.conf >>$seq_full
 $sudo -u pcp cat $PCP_SASLCONF_DIR/pmcd.conf >>$seq_full
 
-echo "Creating temporary sasldb, add user running QA to it" | tee -a $seq.full
+echo "Creating temporary sasldb, add user running QA to it" | tee -a $seq_full
 echo y | saslpasswd2 -p -a pmcd -f $tmp.passwd.db $username
 
-echo "Verify saslpasswd2 has successfully added a new user" | tee -a $seq.full
+echo "Verify saslpasswd2 has successfully added a new user" | tee -a $seq_full
 sasldblistusers2 -f $tmp.passwd.db \
-| tee -a $seq.full \
+| tee -a $seq_full \
 | _filter_listusers2
 
-echo "Ensure pmcd can read the password file" | tee -a $seq.full
+echo "Ensure pmcd can read the password file" | tee -a $seq_full
 $sudo chown pcp:pcp $tmp.passwd.db
 ls -l $tmp.passwd.db >>$seq_full
 $sudo -u pcp od -c $tmp.passwd.db >>$seq_full
 
 echo "Start pmcd with this shiny new sasldb"
-if ! _service pcp restart 2>&1; then _exit 1; fi | tee -a $seq.full >$tmp.out
+if ! _service pcp restart 2>&1; then _exit 1; fi | tee -a $seq_full >$tmp.out
 _wait_for_pmcd || _exit 1
 _wait_for_pmlogger || _exit 1
 
 for method in $mechanisms
 do
     echo
-    echo "=== method: ${method}, authentication with invalid password ===" | tee -a $seq.full
-    pminfo -f -h "pcp://localhost?method=${method}&username=${username}&password=n" pmcd.feature.authentication 2>&1 | tee -a $seq.full \
+    echo "=== method: ${method}, authentication with invalid password ===" | tee -a $seq_full
+    pminfo -f -h "pcp://localhost?method=${method}&username=${username}&password=n" pmcd.feature.authentication 2>&1 | tee -a $seq_full \
     | grep 'Authentication - ' | grep -E -q "authentication failure|Cannot connect"
     test $? -eq 0 && echo "authentication failure"
 
     echo
-    echo "=== method: ${method}, authentication with correct password ===" | tee -a $seq.full
+    echo "=== method: ${method}, authentication with correct password ===" | tee -a $seq_full
     pminfo -f -h "pcp://localhost?method=${method}&username=${username}&password=y" pmcd.feature.authentication
 done
 
diff --git a/qa/170 b/qa/170
--- a/qa/170
+++ b/qa/170
@@ -31,10 +31,10 @@ _stop_auto_restart pmcd
 
 # real QA test starts here
 
-echo "First, the standard logfile:" | tee -a $seq.full
+echo "First, the standard logfile:" | tee -a $seq_full
 if ! _service pcp stop >/dev/null; then _exit 1; fi
 $sudo rm -f $PCP_LOG_DIR/pmcd/pmcd.log*
-if ! _service pcp start 2>&1; then _exit 1; fi | tee -a $seq.full >$tmp.out
+if ! _service pcp start 2>&1; then _exit 1; fi | tee -a $seq_full >$tmp.out
 _wait_for_pmcd || _exit 1
 _wait_for_pmlogger || _exit 1
 grep -i 'starting pmcd' $tmp.out | _filter_pcp_start
@@ -42,7 +42,7 @@ if [ -f $PCP_LOG_DIR/pmcd/pmcd.log ]
 then
     echo '$PCP_LOG_DIR/pmcd/pmcd.log created'
 else
-    echo 'Error: $PCP_LOG_DIR/pmcd/pmcd.log not created' | tee -a $here/$seq.full
+    echo 'Error: $PCP_LOG_DIR/pmcd/pmcd.log not created' | tee -a $seq_full
     date >>$seq_full
     ls -l $PCP_LOG_DIR/pmcd >>$seq_full
     $PCP_PS_PROG $PCP_PS_ALL_FLAGS | grep -E '[P]PID|/[p]mcd( |$)' >>$seq_full
@@ -61,8 +61,8 @@ cat <<End-Of-File >>$tmp.options
 End-Of-File
 $sudo cp $tmp.options $PCP_PMCDOPTIONS_PATH
 
-echo "The logfile from the hacked \$PCP_PMCDOPTIONS_PATH (pmcd.options):" | tee -a $seq.full
-if ! _service pcp restart 2>&1; then _exit 1; fi | tee -a $seq.full >$tmp.out
+echo "The logfile from the hacked \$PCP_PMCDOPTIONS_PATH (pmcd.options):" | tee -a $seq_full
+if ! _service pcp restart 2>&1; then _exit 1; fi | tee -a $seq_full >$tmp.out
 _wait_for_pmcd || _exit 1
 _wait_for_pmlogger || _exit 1
 grep -i 'starting pmcd' $tmp.out | sed -e "s/$$/MYPID/" | _filter_pcp_start
diff --git a/qa/823 b/qa/823
--- a/qa/823
+++ b/qa/823
@@ -59,40 +59,40 @@ $sudo chown pcp:pcp $PCP_SASLCONF_DIR/pmcd.conf
 ls -l $PCP_SASLCONF_DIR/pmcd.conf >>$seq_full
 $sudo -u pcp cat $PCP_SASLCONF_DIR/pmcd.conf >>$seq_full
 
-echo "Creating temporary sasldb, add user running QA to it" | tee -a $seq.full
+echo "Creating temporary sasldb, add user running QA to it" | tee -a $seq_full
 echo y | saslpasswd2 -p -a pmcd -f $tmp.passwd.db $username
 
-echo "Verify saslpasswd2 has successfully added a new user" | tee -a $seq.full
+echo "Verify saslpasswd2 has successfully added a new user" | tee -a $seq_full
 sasldblistusers2 -f $tmp.passwd.db \
-| tee -a $seq.full \
+| tee -a $seq_full \
 | _filter_listusers2
 
-echo "Ensure pmcd can read the password file" | tee -a $seq.full
+echo "Ensure pmcd can read the password file" | tee -a $seq_full
 $sudo chown pcp:pcp $tmp.passwd.db
 ls -l $tmp.passwd.db >>$seq_full
 $sudo -u pcp od -c $tmp.passwd.db >>$seq_full
 
 echo "Start pmcd with this shiny new sasldb"
-if ! _service pcp restart 2>&1; then _exit 1; fi | tee -a $seq.full >$tmp.out
+if ! _service pcp restart 2>&1; then _exit 1; fi | tee -a $seq_full >$tmp.out
 _wait_for_pmcd || _exit 1
 _wait_for_pmlogger || _exit 1
 
-echo "Enabling sample PMDA tracing" | tee -a $seq.full
+echo "Enabling sample PMDA tracing" | tee -a $seq_full
 authdbg=`pmdbg -l -o | grep DBG_TRACE_AUTH | awk '{ print $2 }'`
 echo "authdbg=$authdbg" >>$seq_full
 echo "username=$username" >>$seq_full
 pmstore sample.control "$authdbg"
 
-echo "Verifying SASL authentication for new client (FAIL)" | tee -a $seq.full
+echo "Verifying SASL authentication for new client (FAIL)" | tee -a $seq_full
 pmprobe -v -h "pcp://localhost?username=${username}&password=n" sample.control 2>&1\
 | tee -a $tmp.out
 grep -q 'user not found' $tmp.out && _notrun "sasldb user-not-found libsasl bug"
 cat $PCP_LOG_DIR/pmcd/sample.log >>$seq_full
 filter_sample_log_credentials
-echo "pmcd.log (from expected FAIL)" >>$seq_full | tee -a $seq.full
+echo "pmcd.log (from expected FAIL)" >>$seq_full | tee -a $seq_full
 cat $PCP_LOG_DIR/pmcd/pmcd.log >>$seq_full
 
-echo "Verifying SASL authentication for new client (PASS)" | tee -a $seq.full
+echo "Verifying SASL authentication for new client (PASS)" | tee -a $seq_full
 pmprobe -v -h "pcp://localhost?username=${username}&password=y" sample.control
 cat $PCP_LOG_DIR/pmcd/sample.log >>$seq_full
 filter_sample_log_credentials
