qa: additional diagnostics for travis CI 1158 failures

diff --git a/qa/1158 b/qa/1158
--- a/qa/1158
+++ b/qa/1158
@@ -25,14 +25,22 @@ _value_filter_bytes()
     echo === input to _value_filter >>$here/$seq.full
     cat $tmp.value >> $here/$seq.full
 
+    _found=false
     _values=`awk '/inst.*value/ {print $NF}' $tmp.value`
     for value in $_values
     do
-        if _within_tolerance "Expecting ${write_size} +- 10%" $value ${write_size} 10%; then
+        if _within_tolerance "Expecting ${write_size} +- 10%" $value ${write_size} 10%
+	then
             echo "found value ${write_size} +- 10%"
+	    _found=true
             break
         fi
     done
+    if ! $_found
+    then
+	echo "Failed to find writer process in:"
+	cat $tmp.value
+    fi
 }
 
 _prepare_pmda bcc
