qa/1441, qa/common.check: small tweaks

diff --git a/qa/1441 b/qa/1441
--- a/qa/1441
+++ b/qa/1441
@@ -25,6 +25,8 @@ fi
 . ./common.filter
 . ./common.check
 
+$sudo rm -rf $tmp $tmp.* $seq.full
+
 oldhostname=`hostname`
 newhostname="boofa-$seq"
 
@@ -51,7 +53,7 @@ _wait_for_new_pmlogger()
 {
     echo "_wait_for_new_pmlogger previous PID $1 ..." >>$seq.full
     $PCP_PS_PROG $PCP_PS_ALL_FLAGS | grep -E '[P]PID|/[p]mlogger' >>$seq.full
-    max_delay=12
+    max_delay=15
     i=0
     while [ $i -lt $max_delay ]
     do
@@ -67,6 +69,7 @@ _wait_for_new_pmlogger()
     else
 	echo "Failed!" >>$seq.full
 	echo "Arrgh: failed to see new pmlogger after $max_delay seconds"
+	date
 	ls -l $PCP_RUN_DIR/pmlogger.pid
 	ls -l $PCP_TMP_DIR/pmlogger
 	$PCP_PS_PROG $PCP_PS_ALL_FLAGS | grep -E '[P]PID|/[p]mlogger'
@@ -103,6 +106,7 @@ _wait_for_new_pmie()
     else
 	echo "Failed!" >>$seq.full
 	echo "Arrgh: failed to see new pmie after $max_delay seconds"
+	date
 	ls -l $PCP_RUN_DIR/pmie.pid
 	ls -l $PCP_TMP_DIR/pmie
 	$PCP_PS_PROG $PCP_PS_ALL_FLAGS | grep -E '[P]PID|/[p]mie'
@@ -142,7 +146,7 @@ else
 fi
 config=`sed -n <$tmp.pminfo -e '/0 or "primary"/{
 s/"$//
-s/.*/"/
+s/.*"//
 p
 }'`
 if [ -z "$config" ]
@@ -162,18 +166,36 @@ some_host (
     // especially for small systems
     kernel.all.load  #'1 minute' > hinv.ncpu  * 3
     && kernel.all.load  #'1 minute' > 4
-) -> pring 10 min "High 1-minute load average" " %vload@%h";
+) -> print 10 min "High 1-minute load average" " %vload@%h";
 End-of-File
 $sudo cp $tmp.config $config
 _service pmie restart >>$seq.full 2>&1
+_wait_for_pmie
 
 if [ -f $PCP_RUN_DIR/pmie.pid ]
 then
     oldpmie=`cat $PCP_RUN_DIR/pmie.pid`
     echo "old pmie pid: $oldpmie" >>$seq.full
 else
-    _notrun "$PCP_RUN_DIR/pmie.pid not found for old primary pmie"
-    # NOTREACHED
+    echo "Botch: $PCP_RUN_DIR/pmie.pid not found for (restarted) old primary pmie"
+    _cleanup
+    exit 1
+fi
+
+# need mmap control file for new pmie as well ... wait up to 2 secs
+#
+try=0
+while [ $try -lt 20 ]
+do
+    [ -f $PCP_TMP_DIR/pmie/$oldpmie ] && break
+    pmsleep 0.1
+    try=`expr $try + 1`
+done
+if [ ! -f $PCP_TMP_DIR/pmie/$oldpmie ]
+then
+    echo "Botch: $PCP_TMP_DIR/pmies/$oldpmie not found for (restarted) old primary pmie"
+    _cleanup
+    exit 1
 fi
 
 newlogger=0
@@ -191,13 +213,13 @@ _cleanup()
     fi
     for dir in boofa-$seq
     do
-	$sudo rm -rf "$PCP_ARCHIVE_DIR/$dir"
+	$sudo rm -rf "$PCP_LOG_DIR/pmlogger/$dir"
+	$sudo rm -rf "$PCP_LOG_DIR/pmie/$dir"
     done
     $sudo rm -rf $tmp $tmp.*
 }
 
 status=0	# success is the default!
-$sudo rm -rf $tmp $tmp.* $seq.full
 trap "_cleanup; exit \$status" 0 1 2 3 15
 
 _filter()
@@ -218,6 +240,7 @@ echo "old pmlogger ..."
 if [ ! -f $PCP_TMP_DIR/pmlogger/primary ]
 then
     echo "Arrgh: no tracking file in $PCP_TMP_DIR for primary pmlogger"
+    date
     ls -l $PCP_TMP_DIR/pmlogger
     status=1
     exit
@@ -233,6 +256,7 @@ echo "old pmie ..."
 if [ ! -f $PCP_TMP_DIR/pmie/$oldpmie ]
 then
     echo "Arrgh: no tracking file in $PCP_TMP_DIR for old primary pmie"
+    date
     ls -l $PCP_TMP_DIR/pmie
     status=1
     exit
@@ -250,6 +274,7 @@ echo "new pmlogger ..."
 if [ ! -f $PCP_TMP_DIR/pmlogger/primary ]
 then
     echo "Arrgh: no tracking file in $PCP_TMP_DIR for primary pmlogger"
+    date
     ls -l $PCP_TMP_DIR/pmlogger
     status=1
     exit
@@ -283,6 +308,7 @@ fi
 if [ ! -f $PCP_TMP_DIR/pmie/$newpmie ]
 then
     echo "Arrgh: no tracking file in $PCP_TMP_DIR for new primary pmie"
+    date
     ls -l $PCP_TMP_DIR/pmie
     status=1
     exit
