pmlock and pmcd state changes: improvements and fixes
qa/1441 has been chronically unstable for a long time, and
attempting to resolve this involved a number of changes (most
of which are not implicated in the qa/1441 fixup, but are being
kept as they constitue a "good thing" (tm)).

- refine pmlock so that the lock file may optionally contain
  text to identify the locker (a new -i command line option);
  the de facto standard is to use a string of the form:
      "<pid> <who>"
  to identify the locker, e.g. pmlock -i "$$ pmlogger_check"
  from pmlogger_check(1)

- using the new -i option to pmlock everywhere

- better diagnostics around the detection and propagation of
  pmcd state changes from PMDAs or pmcd thru to clients like
  pmie and pmlogger (who are the victims in qa/1441); this also
  involved some libpcp refactoring to promote dumping of the
  change flags to the (new) __pmDumpFetchFlags() and removal
  of the similar code that was lurking in multiple places

- tighter checking of status files in qa/1441 to avoid races

- recognition that hostname(1) will not always change the host
  name (!!) when hostnamectl(1) is in play ... when possible
  use hostnamectl set-hostname <name> (or the older variant
  hostnamectl hostname <name>) in qa/1441

diff --git a/qa/1441 b/qa/1441
--- a/qa/1441
+++ b/qa/1441
@@ -49,12 +49,19 @@ _cleanup()
     cd $here
     if [ -n "$config" ]
     then
-	$sudo rm -f $config 2>>$seq.full
-	_restore_config $config 2>>$seq.full
+	$sudo rm -f $config 2>>$seq_full
+	_restore_config $config 2>>$seq_full
     fi
     if [ "`hostname`" != "$oldhostname" ]
     then
-	$sudo hostname "$oldhostname" 2>>$seq.full
+	date >>$seq_full
+	echo "hostname -> $oldhostname" >>$seq_full
+	_set_hostname "$oldhostname"
+	# delay to stop systemctl getting its knickers in a knot with
+	# frequent pmlogger/pmie service restarts
+	#
+	sleep 5	
+	hostname >>$seq_full
 	_wait_for_new_pmlogger "$newlogger"
 	_wait_for_new_pmie "$newpmie"
     fi
@@ -64,7 +71,7 @@ _cleanup()
 	$sudo rm -rf "$PCP_LOG_DIR/pmie/$dir"
     done
     $sudo rm -rf $tmp $tmp.*
-    [ -f /tmp/pmie-hb ] && ( echo "Final heartbeat ..."; cat /tmp/pmie-hb ) >>$seq.full
+    [ -f /tmp/pmie-hb ] && ( echo "Final heartbeat ..."; cat /tmp/pmie-hb ) >>$seq_full
 }
 
 # wait until the primary pmlogger's pid is != $1
@@ -77,9 +84,10 @@ _cleanup()
 #
 _wait_for_new_pmlogger()
 {
+    date >>$seq_full
     echo "_wait_for_new_pmlogger previous PID $1 ..." >>$seq_full
     $PCP_PS_PROG $PCP_PS_ALL_FLAGS | grep -E '[P]PID|/[p]mlogger( |$)' >>$seq_full
-    max_delay=15
+    max_delay=20
     i=0
     while [ $i -lt $max_delay ]
     do
@@ -94,29 +102,90 @@ _wait_for_new_pmlogger()
 	$PCP_PS_PROG $PCP_PS_ALL_FLAGS | grep -E '[P]PID|/[p]mlogger( |$)' >>$seq_full
     else
 	echo "Failed!" >>$seq_full
-	echo "Arrgh: failed to see new pmlogger after $max_delay seconds"
 	date
-	ls -l $PCP_RUN_DIR/pmlogger.pid
+	cat $PCP_LOG_DIR/pmlogger/`hostname`/pmlogger.log >>$seq_full
+	echo "Arrgh: failed to see new pmlogger after $max_delay seconds"
+	echo "oldpid=$1"
+	if [ -f $PCP_RUN_DIR/pmlogger.pid ]
+	then
+	    ls -l $PCP_RUN_DIR/pmlogger.pid
+	    cat $PCP_RUN_DIR/pmlogger.pid
+	else
+	    echo $PCP_RUN_DIR/pmlogger.pid is missing
+	fi
 	ls -l $PCP_TMP_DIR/pmlogger
+	if [ -f $PCP_TMP_DIR/pmlogger/primary ]
+	then
+	    ls -l $PCP_TMP_DIR/pmlogger/primary
+	    cat $PCP_TMP_DIR/pmlogger/primary
+	else
+	    echo $PCP_TMP_DIR/pmlogger/primary is missing
+	fi
 	$PCP_PS_PROG $PCP_PS_ALL_FLAGS | grep -E '[P]PID|/[p]mlogger( |$)'
+	echo "--- start pmcd.log" >>$seq_full
+	cat $PCP_LOG_DIR/pmcd/pmcd.log >>$seq_full
+	echo "--- end pmcd.log" >>$seq_full
 	status=1
     fi
 }
 
+# need control file for primary pmlogger and "old" or "new" ($1)
+# hostname as line 2 of that file
+# wait up to 30 x 0.1 secs
+#
+_really_wait_for_pmlogger()
+{
+    if [ "$1" = old ]
+    then
+	want=$oldhostname
+    else
+	want=$newhostname
+    fi
+    try=0
+    rm -f $tmp.ok
+    while [ $try -lt 30 ]
+    do
+	if [ -f $PCP_TMP_DIR/pmlogger/primary ]
+	then
+	    host=`sed -n -e 2p <$PCP_TMP_DIR/pmlogger/primary`
+	    if [ X"$host" = X"$want" ]
+	    then
+		touch $tmp.ok
+		break
+	    fi
+	fi
+	pmsleep 0.1
+	try=`expr $try + 1`
+    done
+    if [ ! -f $tmp.ok ]
+    then
+	if [ ! -f $PCP_TMP_DIR/pmlogger/primary ]
+	then
+	    echo "Arrgh: no tracking file in $PCP_TMP_DIR for $1 primary pmlogger"
+	    date
+	    ls -l $PCP_TMP_DIR/pmlogger
+	else
+	    echo "Botch: hostname not $want in $PCP_TMP_DIR/pmlogger/primary"
+	    ls -l $PCP_TMP_DIR/pmlogger/primary
+	    ls -lL $PCP_TMP_DIR/pmlogger/primary
+	    cat $PCP_TMP_DIR/pmlogger/primary
+	fi
+	return 1
+    fi
+    return 0
+}
+
 # wait until the primary pmie's pid is != $1
 #
-# In pmie's config.default, the most frequent rule evaluation is once
-# every 2 mins (sigh) ... pmie only sees PMCD_HOSTNAME_CHANGE from the
-# pmFetch(), so it could be up to 120 seconds before the old pmie notices
-# it has to exit, then systemd needs time to notice and restart pmie, but
-# in addition, pmie's scheduler is sometimes a bit slow so add another
-# 10 secs for all of that
+# Special (for this QA test) pmie config fires once every 2 seconds.
+# wait up to 30 x 0.1 secs
 #
 _wait_for_new_pmie()
 {
+    date >>$seq_full
     echo "_wait_for_new_pmie previous PID $1" >>$seq_full
     $PCP_PS_PROG $PCP_PS_ALL_FLAGS | grep -E '[P]PID|/[p]mie( |$)' >>$seq_full
-    max_delay=130
+    max_delay=30
     i=0
     while [ $i -lt $max_delay ]
     do
@@ -142,8 +211,53 @@ _wait_for_new_pmie()
 	cat $PCP_LOG_DIR/pmie/$oldhostname/pmie.log >>$seq_full
 	echo "=== $newhostname log ===" >>$seq_full
 	cat $PCP_LOG_DIR/pmie/$newhostname/pmie.log >>$seq_full
+	echo "--- start pmcd.log" >>$seq_full
+	cat $PCP_LOG_DIR/pmcd/pmcd.log >>$seq_full
+	echo "--- end pmcd.log" >>$seq_full
 	status=1
     fi
+}
+
+# need mmap control file for pmie as well and the FQDN in the control
+# control file ($1) that is not (uninitialized) ... $2 is "which one"
+# for diagnostics
+# wait up to 20 x 0.1 secs
+#
+_really_wait_for_pmie()
+{
+    try=0
+    rm -f $tmp.ok
+    while [ $try -lt 20 ]
+    do
+	if [ -f $1 ]
+	then
+	    fqdn=`$PCP_BINADM_DIR/pmiestatus $1 2>/dev/null | sed -n -e 3p`
+	    if [ -z "$fqdn" -o "$fqdn" = "(uninitialized)" ]
+	    then
+		:
+	    else
+		touch $tmp.ok
+		break
+	    fi
+	fi
+	pmsleep 0.1
+	try=`expr $try + 1`
+    done
+    if [ ! -f $tmp.ok ]
+    then
+	if [ ! -f $1 ]
+	then
+	    echo "Botch: $1 not found for $2 pmie"
+	    date
+	    ls -l $PCP_TMP_DIR/pmie
+	else
+	    echo "Botch: pmcd FQDN not set in $1 for $2 pmie"
+	    $PCP_BINADM_DIR/pmiestatus $1
+	    ls -l $1
+	fi
+	return 1
+    fi
+    return 0
 }
 
 # need primary pmlogger running
@@ -222,21 +336,9 @@ else
     exit 1
 fi
 
-# need mmap control file for new pmie as well ... wait up to 2 secs
-#
-try=0
-while [ $try -lt 20 ]
-do
-    [ -f $PCP_TMP_DIR/pmie/$oldpmie ] && break
-    pmsleep 0.1
-    try=`expr $try + 1`
-done
-if [ ! -f $PCP_TMP_DIR/pmie/$oldpmie ]
-then
-    echo "Botch: $PCP_TMP_DIR/pmies/$oldpmie not found for (restarted) old primary pmie"
-    _cleanup
-    exit 1
-fi
+_really_wait_for_pmie $PCP_TMP_DIR/pmie/$oldpmie "(restarted) old primary" || exit
+$PCP_BINADM_DIR/pmiestatus $PCP_TMP_DIR/pmie/$oldpmie >>$seq_full
+
 
 newlogger=0
 newpmie=0
@@ -273,17 +375,43 @@ _filter()
     # end
 }
 
+_set_hostname()
+{
+    if which hostnamectl >/dev/null 2>&1
+    then
+	if $sudo hostnamectl set-hostname "$1" >$tmp.tmp 2>&1
+	then
+	    :
+	else
+	    cat $tmp.tmp
+	    echo "Arrgh: hostnamectl(1) failed"
+	    return 1
+	fi
+    else
+	if $sudo hostname "$newhostname" >$tmp.tmp 2>&1
+	then
+	    :
+	else
+	    cat $tmp.tmp
+	    echo "Arrgh: hostname(1) failed"
+	    return 1
+	fi
+    fi
+    local probe=`hostname`
+    if [ "$1" != "$probe" ]
+    then
+	echo "Arrgh: _set_hostname failed: expected $1, but found $probe"
+	return 1
+    fi
+    echo "_set_hostname success for $1" >>$seq_full
+    return 0
+}
+
 # real QA test starts here
 echo "old pmlogger ..."
-if [ ! -f $PCP_TMP_DIR/pmlogger/primary ]
-then
-    echo "Arrgh: no tracking file in $PCP_TMP_DIR for primary pmlogger"
-    date
-    ls -l $PCP_TMP_DIR/pmlogger
-    status=1
-    exit
-fi
-_filter <$PCP_TMP_DIR/pmlogger/primary \
+_really_wait_for_pmlogger old || exit
+tee -a $seq_full <$PCP_TMP_DIR/pmlogger/primary \
+| _filter \
 | sed \
     -e 's/^reexec$/pmlogger_check|reexec/' \
     -e 's/^pmlogger_check$/pmlogger_check|reexec/' \
@@ -291,33 +419,35 @@ _filter <$PCP_TMP_DIR/pmlogger/primary \
 
 echo
 echo "old pmie ..."
-if [ ! -f $PCP_TMP_DIR/pmie/$oldpmie ]
-then
-    echo "Arrgh: no tracking file in $PCP_TMP_DIR for old primary pmie"
-    date
-    ls -l $PCP_TMP_DIR/pmie
-    status=1
-    exit
-fi
+_really_wait_for_pmie $PCP_TMP_DIR/pmie/$oldpmie "old primary" || exit
 $PCP_BINADM_DIR/pmiestatus $PCP_TMP_DIR/pmie/$oldpmie \
+| tee -a $seq_full \
 | _filter
 
 echo
 echo "Change hostname ..."
-$sudo hostname "$newhostname" 2>>$seq_full
+date >>$seq_full
+_set_hostname "$newhostname" || exit
+# delay to stop systemctl getting its knickers in a knot with
+# frequent pmlogger/pmie service restarts
+#
+sleep 5	
+hostname >>$seq_full
 _wait_for_new_pmlogger "$oldlogger"
 
 echo
-echo "new pmlogger ..."
-if [ ! -f $PCP_TMP_DIR/pmlogger/primary ]
+echo "new pmlogger ..." | tee -a $seq_full
+if _really_wait_for_pmlogger new
 then
-    echo "Arrgh: no tracking file in $PCP_TMP_DIR for primary pmlogger"
-    date
-    ls -l $PCP_TMP_DIR/pmlogger
-    status=1
+    :
+else
+    echo "--- start pmcd.log" >>$seq_full
+    cat $PCP_LOG_DIR/pmcd/pmcd.log >>$seq_full
+    echo "--- end pmcd.log" >>$seq_full
     exit
 fi
-_filter <$PCP_TMP_DIR/pmlogger/primary
+tee -a $seq_full <$PCP_TMP_DIR/pmlogger/primary \
+| _filter
 
 if [ -f $PCP_RUN_DIR/pmlogger.pid ]
 then
@@ -330,9 +460,9 @@ else
 fi
 
 echo
-echo "new pmie ..."
+echo "new pmie ..." | tee -a $seq_full
+hostname >>$seq_full
 _wait_for_new_pmie "$oldpmie"
-
 if [ -f $PCP_RUN_DIR/pmie.pid ]
 then
     newpmie=`cat $PCP_RUN_DIR/pmie.pid`
@@ -342,16 +472,17 @@ else
     status=1
     exit
 fi
-
-if [ ! -f $PCP_TMP_DIR/pmie/$newpmie ]
+if _really_wait_for_pmie $PCP_TMP_DIR/pmie/$newpmie "new primary"
 then
-    echo "Arrgh: no tracking file in $PCP_TMP_DIR for new primary pmie"
-    date
-    ls -l $PCP_TMP_DIR/pmie
-    status=1
+    :
+else
+    echo "--- start pmcd.log" >>$seq_full
+    cat $PCP_LOG_DIR/pmcd/pmcd.log >>$seq_full
+    echo "--- end pmcd.log" >>$seq_full
     exit
 fi
 $PCP_BINADM_DIR/pmiestatus $PCP_TMP_DIR/pmie/$newpmie \
+| tee -a $seq_full \
 | _filter
 
 # success, all done
