pmie and summary PMDA: extra units changes
- pmie propagation of pmUnits in expression trees was seriously broken,
  and had not been noticed because pmie does not check pmUnits for
  compatibility of operands in expressions (another good reason to
  prefer derived metrics over pmie expressions) ... the fixes here address
  the obvious issues and in particular safe handling of extra units and
  correct metadata for the default metrics exported from the summary PMDA
  (which runs pmie in "secret agent" mode)

- revise default expressions for the summary PMDA metrics
  summary.netif.packets and summary.netif.busy to consistently consider
  only active network interfaces, and tweak the help text to better
  match the semantics of the expressions used

- new qa/1665 and qa/1666 to exercise pmUnits handling for pmie
  and the summary PMDA

- fix incorrect pmUnits fiddling for QA's broken PMDA

- fix incorrect pmUnits fiddling in qa/src/pducheck.c

- fix leftover fallout from pminfo -e and sample PMDA pmns changes with
  some QA remakes

- qa/1426: rework to use modern network.tcp "drops" metrics rather than
  _notrun when the Irix metrics are not available

- make _triage_wait_point() look for $here/$seq.wait by default, so it
  works when a QA test has cd'd away from $here ... update COOKBOOK.md
  to match

- assorted extra unit QA remakes and fixups, some from earlier changes
  that had not been exposed to a full QA run with all the pmUnits
  changes to date

diff --git a/qa/1666 b/qa/1666
--- a/qa/1666
+++ b/qa/1666
@@ -1,6 +1,6 @@
 #!/bin/sh
-# PCP QA Test No. 1665
-# pmie for metrics with extra units
+# PCP QA Test No. 1666
+# metadata propagation from pmie to the summary PMDA
 #
 # Copyright (c) 2026 Ken McDonell.  All Rights Reserved.
 #
@@ -22,11 +22,12 @@ fi
 
 _cleanup()
 {
+    _cleanup_pmda summary
     cd $here
     $sudo rm -rf $tmp $tmp.*
 }
 
-status=0	# success is the default!
+status=1	# failure is the default!
 trap "_cleanup; exit \$status" 0 1 2 3 15
 
 _filter()
@@ -36,15 +37,26 @@ _filter()
     # end
 }
 
-# real QA test starts here
+_prepare_pmda summary
 
-pmie -z -t 200msec -a archives/extra -v 2>$tmp.err <<End-of-File
-// similar to pmie(1) page
-sample.temperature.celsius >= (sample.temperature.farenheit - 32) * 5 / 9;
-// expect true
-2 * sample.voltage.volt == sample.voltage.millivolt / 1000 + sample.voltage.microvolt / 1000000;
-End-of-File
-_show_pmie_exit <$tmp.err
+unset ROOT MAKEFLAGS
+
+pmda_home=$PCP_PMDAS_DIR/summary
+if [ ! -d "$pmda_home" ]
+then
+    echo "Where is $pmda_home?"
+    exit
+fi
+cd "$pmda_home" || exit
+$sudo ./Install </dev/null || exit
+
+# real QA test starts here
+echo "metadata ok? (silence is golden) ..."
+pminfo -e summary
+
+echo "actual metadata ..."
+pminfo -dtT summary
 
 # success, all done
+status=0
 exit
