libpcp: redefine __pmLogSetTime()
The problem is that if physical files for the data volumes of an
archive are removed (asynchronously by someone else) while we're
trying to switch volumes then we don't handle this safely.

The previous commit 10763319 was as stop-gap to address Mark's SEGV
issue at https://github.com/performancecopilot/pcp/issues/1338 and
simply handled direct calls to __pmLogChangeVol() and ensured the
return status was checked.

I was aware, then Coverity made a lot more people aware, that this
"fix" was incomplete, specifically the calls to __pmLogChangeVol()
from within __pmLogSetTime() were not checked.

To fix the latter we have to change the type of __pmLogSetTime() from
void to int so we can return status to indicate that __pmLogChangeVol()
has failed.  And then make sure all the callers of __pmLogSetTime()
check the status returned from that function.

    modified:   src/libpcp/src/fetch.c
    modified:   src/libpcp/src/internal.h
    modified:   src/libpcp/src/logutil.c

Because this introduces some new -Dlog diagnostics, qa/251 needed
a bit of a make-over.

diff --git a/qa/251 b/qa/251
--- a/qa/251
+++ b/qa/251
@@ -37,7 +37,7 @@ _filter()
 
 status=1	# failure is the default!
 $sudo rm -rf $tmp.* $seq.full
-trap "cd $here; rm -rf $tmp; exit \$status" 0 1 2 3 15
+trap "cd $here; rm -rf $tmp $tmp.*; exit \$status" 0 1 2 3 15
 
 # real QA test starts here
 mkdir $tmp
@@ -50,56 +50,62 @@ cd $tmp
 for inst in "bin-100" "bin-100,bin-500,bin-900"
 do
     echo
-    echo "All volumes present ... $inst ..."
-    pmval -z -O $offset -D128 -t2 -a ok-mv-bar -i $inst sampledso.bin 2>err >out
-    egrep 'Skip|Change' err
-    _filter <out
+    echo "All volumes present ... $inst ..." | tee -a $here/$seq.full
+    pmval -z -O $offset -Dlog -t2 -a ok-mv-bar -i $inst sampledso.bin 2>$tmp.err >$tmp.out
+    cat $tmp.err >>$here/$seq.full
+    grep '^__pmLogChangeVol:' $tmp.err
+    _filter <$tmp.out
     [ -f die ] && exit
 
     echo
-    echo "First volume missing ... $inst ..."
+    echo "First volume missing ... $inst ..." | tee -a $here/$seq.full
     mv ok-mv-bar.0 foo.0
-    pmval -z -O $offset -D128 -t2 -a ok-mv-bar -i $inst sampledso.bin 2>err >out
-    egrep 'Skip|Change' err
-    _filter <out
+    pmval -z -O $offset -Dlog -t2 -a ok-mv-bar -i $inst sampledso.bin 2>$tmp.err >$tmp.out
+    cat $tmp.err >>$here/$seq.full
+    grep '^__pmLogChangeVol:' $tmp.err
+    _filter <$tmp.out
     [ -f die ] && exit
     mv foo.0 ok-mv-bar.0
 
     echo
-    echo "Last volume missing ... $inst ..."
+    echo "Last volume missing ... $inst ..." | tee -a $here/$seq.full
     mv ok-mv-bar.3 foo.3
-    pmval -z -O $offset -D128 -t2 -a ok-mv-bar -i $inst sampledso.bin 2>err >out
-    egrep 'Skip|Change' err
-    _filter <out
+    pmval -z -O $offset -Dlog -t2 -a ok-mv-bar -i $inst sampledso.bin 2>$tmp.err >$tmp.out
+    cat $tmp.err >>$here/$seq.full
+    grep '^__pmLogChangeVol:' $tmp.err
+    _filter <$tmp.out
     [ -f die ] && exit
     mv foo.3 ok-mv-bar.3
 
     echo
-    echo "Second volume missing ... $inst ..."
+    echo "Second volume missing ... $inst ..." | tee -a $here/$seq.full
     mv ok-mv-bar.1 foo.1
-    pmval -z -O $offset -D128 -t2 -a ok-mv-bar -i $inst sampledso.bin 2>err >out
-    egrep 'Skip|Change' err
-    _filter <out
+    pmval -z -O $offset -Dlog -t2 -a ok-mv-bar -i $inst sampledso.bin 2>$tmp.err >$tmp.out
+    cat $tmp.err >>$here/$seq.full
+    grep '^__pmLogChangeVol:' $tmp.err
+    _filter <$tmp.out
     [ -f die ] && exit
     mv foo.1 ok-mv-bar.1
 
     echo
-    echo "Second last volume missing ... $inst ..."
+    echo "Second last volume missing ... $inst ..." | tee -a $here/$seq.full
     mv ok-mv-bar.2 foo.2
-    pmval -z -O $offset -D128 -t2 -a ok-mv-bar -i $inst sampledso.bin 2>err >out
-    egrep 'Skip|Change' err
-    _filter <out
+    pmval -z -O $offset -Dlog -t2 -a ok-mv-bar -i $inst sampledso.bin 2>$tmp.err >$tmp.out
+    cat $tmp.err >>$here/$seq.full
+    grep '^__pmLogChangeVol:' $tmp.err
+    _filter <$tmp.out
     [ -f die ] && exit
     mv foo.2 ok-mv-bar.2
 
     echo
-    echo "All volumes but second missing ... $inst ..."
+    echo "All volumes but second missing ... $inst ..." | tee -a $here/$seq.full
     mv ok-mv-bar.0 foo.0
     mv ok-mv-bar.2 foo.2
     mv ok-mv-bar.3 foo.3
-    pmval -z -O $offset -D128 -t2 -a ok-mv-bar -i $inst sampledso.bin 2>err >out
-    egrep 'Skip|Change' err
-    _filter <out
+    pmval -z -O $offset -Dlog -t2 -a ok-mv-bar -i $inst sampledso.bin 2>$tmp.err >$tmp.out
+    cat $tmp.err >>$here/$seq.full
+    grep '^__pmLogChangeVol:' $tmp.err
+    _filter <$tmp.out
     [ -f die ] && exit
     mv foo.0 ok-mv-bar.0
     mv foo.2 ok-mv-bar.2
