qa/308 - more broken than I first thought
Needs the proc PMDA installed locally and on 2 remote machines.

Make it so locally, clean up when you're done and harden the test
with better integrity checks for the expected instance in the proc
pid indom.

diff --git a/qa/308 b/qa/308
--- a/qa/308
+++ b/qa/308
@@ -58,6 +58,30 @@ echo "QA output created by $seq"
 rm -f $seq.full
 echo "host1=$host1" >>$seq.full
 echo "host2=$host2" >>$seq.full
+done_clean=false
+
+install_on_cleanup=false
+pminfo proc >/dev/null 2>&1 && install_on_cleanup=true
+
+_cleanup()
+{
+    if $done_clean
+    then
+	:
+    else
+	if $install_on_cleanup
+	then
+	    ( cd $PCP_PMDAS_DIR/proc; $sudo ./Install </dev/null >/dev/null 2>&1 )
+	else
+	    ( cd $PCP_PMDAS_DIR/proc; $sudo ./Remove </dev/null >/dev/null 2>&1 )
+	fi
+	done_clean=true
+    fi
+    $sudo rm -f $tmp.*
+    exit $status
+}
+trap "_cleanup; exit \$status" 0 1 2 3 15
+( cd $PCP_PMDAS_DIR/proc; $sudo ./Install </dev/null >/dev/null 2>&1 )
 
 # real QA test starts here
 
@@ -69,6 +93,13 @@ s/^[^"]*"/"/
 s/] value .*//
 p
 }'`
+
+if [ -z "$inst" ]
+then
+    echo "Arrgh ... cannot find inst for local pid 1" | tee -a $seq.full
+    pminfo -F proc.psinfo.ppid >>$seq.full
+    exit
+fi
 
 echo "inst=$inst" >>$seq.full
 ps $PCP_PS_ALL_FLAGS | egrep "PID|$inst" >>$seq.full
@@ -124,6 +155,12 @@ s/^[^"]*"/"/
 s/] value .*//
 p
 }'`
+if [ -z "$inst" ]
+then
+    echo "Arrgh ... cannot find inst for host $host1 pid 1" | tee -a $seq.full
+    pminfo -F -h $host1 proc.psinfo.ppid >>$seq.full
+    exit
+fi
 cat <<end-of-file >$tmp.conf
 log advisory on once { proc.psinfo.ppid[$inst] }
 end-of-file
@@ -189,6 +226,12 @@ s/^[^"]*"/"/
 s/] value .*//
 p
 }'`
+if [ -z "$inst" ]
+then
+    echo "Arrgh ... cannot find inst for host $host2 pid 1" | tee -a $seq.full
+    pminfo -F -h $host2 proc.psinfo.ppid >>$seq.full
+    exit
+fi
 cat <<end-of-file >$tmp.conf
 log advisory on once { proc.psinfo.ppid[$inst] }
 end-of-file
