Update QA test 511 with more sar data output

diff --git a/qa/511 b/qa/511
--- a/qa/511
+++ b/qa/511
@@ -33,30 +33,42 @@ logcheck()
     pmdumplog -z -l $pcplog >>$seq.full
     [ $? -eq 0 ] && echo "pmdumplog approved of the $safile conversion"
 
-    # this will visit and examine in detail every single result stored
+    # this'll visit and examine in detail every single stored result,
+    # as well as all metadata associates with the generated archive.
     pmlogsummary $pcplog >>$seq.full
     [ $? -eq 0 ] && echo "pmlogsummary approved of the $safile conversion"
 }
 
-# real QA test starts here
-rm -f $seq.full
-for safile in $here/sadist/*.bin
-do
-    echo "Checking $safile" | tee -a $seq.full
-    pcplog=$tmp.pcplog
-    sar2pcp $safile $pcplog
-    [ $? -eq 0 ] && "sar2pcp thinks $safile is going well so far"
-    logcheck $safile $pcplog
-    rm -f $tmp.pcplog.*
-done
+# backwards compatibility route - silence is golden
+silence()
+{
+    safile="$1"
+    echo "sar2pcp thinks $safile is going well so far"
+    echo "pmdumplog approved of the $safile conversion"
+    echo "pmlogsummary approved of the $safile conversion"
+}
 
-for xmlfile in $here/sadist/*.xml
+# real QA test starts here
+cd $here
+rm -f $seq.full
+for safile in `ls -1 sadist/*.bin sadist/*.xml | LC_COLLATE=POSIX sort`
 do
-    echo "Checking $xmlfile" | tee -a $seq.full
+    echo "==> Checking $safile" | tee -a $seq.full
     pcplog=$tmp.pcplog
-    sar2pcp -x $xmlfile $pcplog
-    [ $? -eq 0 ] && "sar2pcp thinks $xmlfile is going well so far"
-    logcheck $xmlfile $pcplog
+    sar2pcp $safile $pcplog > $tmp.out 2>&1
+    sts=$?
+
+    # this seems to be a common sadf fail message;
+    # happens when the installed sysutils is old:
+    grep 'Invalid system activity file' $tmp.out >/dev/null
+    if [ $? -eq 0 ]
+    then
+	echo "$safile is not parsable by the installed sysutils" >>$seq.full
+	silence $safile
+    else
+	[ $sts -eq 0 ] && echo "sar2pcp thinks $safile is going well so far"
+	logcheck $safile $pcplog
+    fi
     rm -f $tmp.pcplog.*
 done
 
