qa/560: CI hooks and _notrun did not work ... more diags

diff --git a/qa/560 b/qa/560
--- a/qa/560
+++ b/qa/560
@@ -15,6 +15,11 @@ echo "QA output created by $seq"
 
 [ -d $PCP_PMDAS_DIR/simple ] || _notrun "simple PMDA directory is not installed"
 
+status=1	# failure is the default!
+trap "rm -f $tmp.*; exit \$status" 0 1 2 3 15
+$sudo rm -f $seq.full
+
+echo "PCPQA_IN_CI=$PCPQA_IN_CI" >>$seq.full
 if [ "$PCPQA_IN_CI" = yes ]
 then
     # in CI
@@ -23,8 +28,10 @@ then
     # persists
     #
     eval `src/sizeof ptr`
+    echo "ptr=$ptr" >>$seq.full
     if [ "$ptr" = 4 ]
     then
+	admin/whatami >>$seq.full
 	# 32-bit platform
 	case `admin/whatami`
 	in
@@ -35,10 +42,6 @@ then
 	esac
     fi
 fi
-
-status=1	# failure is the default!
-trap "rm -f $tmp.*; exit \$status" 0 1 2 3 15
-$sudo rm -f $seq.full
 
 # real QA test starts here
 cd $PCP_PMDAS_DIR/simple
