pmwebapi: omnibus tweaks
- added pmwebd -A option to limit remotely-specified archivefile paths
- added relevant -A documentation
- renamed pmwebd -R -> -N option
- renamed pmwebd -r -> -R option
- pmwebd error document generation for pmresapi (file service) and
  top-level errors, to eradicate MHD_NO empty/500 as much as possible
- let pmwebd notify a little more verbosely about its startup
- more qa/600.py and qa/600 tests
- qa/660 tests appear functional

diff --git a/qa/660 b/qa/660
--- a/qa/660
+++ b/qa/660
@@ -16,12 +16,15 @@ echo "QA output created by $seq"
 # 3702
 [ $PCP_VER -gt 3700 ] || _notrun "Installed pcp is too old"
 
-if which wget >/dev/null 2>&1
+if which curl >/dev/null 2>&1
 then
-    echo Found wget
+    echo curl ok
 else
-    _notrun no wget
+    _notrun no curl
 fi
+# nb: wget dispreferred because of its processing of .. relative links,
+# so it's harder to stress pmwebd's base-directory-escapig logic
+
 
 if python 660.py --version 2>/dev/null
 then
@@ -60,15 +63,22 @@ echo "=== 1. pmwebd default startup  ==="
 pmwebd 2>$tmp.out &
 pid=$!
 sleep 2
-if grep -q IPv4 $tmp.out; then
-    wget -q -O - 'http://localhost:44323/pmapi/context?local=ANYTHING' | awk '{print $2}'
-fi
+curl -s -S 'http://localhost:44323/pmapi/context?local=ANYTHING' | awk '{print $2}'
+
+rm -f $seq.out
 if grep -q IPv6 $tmp.out; then
-    wget -q -O - 'http://localhost6:44323/pmapi/context?local=ANYTHING'  | awk '{print $2}'
+    curl -s -S 'http://localhost6:44323/pmapi/context?local=ANYTHING'  | awk '{print $2}'
+    # ipv6 + ipv4
+    ln $seq.out.46 $seq.out
+else
+    # ipv4 only
+    ln $seq.out.4 $seq.out
 fi
+# NB: we don't anticipate an ipv6-only host
 
 echo
 echo "=== 2. pmwebd exercise via python ==="
+# pmwebd still running in default mode
 if grep -q IPv4 $tmp.out; then
   python 660.py --host localhost | _filter
 fi
@@ -76,6 +86,31 @@ if grep -q IPv6 $tmp.out; then
   python 660.py --host localhost6 | _filter
 fi
 
+echo
+echo "=== 3. pmwebd security constraints, file service ==="
+kill $pid
+sleep 2
+pmwebd -R `pwd` -C 2222 -L -N 2>/dev/null &
+pid=$!
+sleep 2
+
+# should fail due to -N
+curl -s -S 'http://localhost:44323/pmapi/context?local=anything'
+echo
+# should fail due to nonexistent context#
+curl -s -S 'http://localhost:44323/pmapi/2223/_fetch'
+echo
+# should fail with a different error (insufficient elements; ie pmFetch failed) 
+curl -s -S 'http://localhost:44323/pmapi/2222/_fetch'
+echo
+# should fail due to suspicious pmresapi path name
+curl -s -S 'http://localhost:44323/../../etc/passwd'
+echo
+# should pass, feed this very script
+curl -s -S 'http://localhost:44323/660' > $tmp.out
+diff $tmp.out $0 && echo file service ok
+
+# $pid killed automagically via trap
 status=0
 sleep 2
 exit
