qa/771: refine previous fix ... needs to work in git tree and testsuite dir

diff --git a/qa/771 b/qa/771
--- a/qa/771
+++ b/qa/771
@@ -22,13 +22,25 @@ trap "cd $here; rm -rf $tmp.*; exit \$status" 0 1 2 3 15
 
 # real QA test starts here
 cd perl
-if make -f GNUmakefile.install cvalue test.pl 2>&1 >../$seq.full
+if [ -f GNUmakefile.install ]
 then
-    perl test.pl
-    status=$?
+    if make -f GNUmakefile.install cvalue test.pl 2>&1 >../$seq.full
+    then
+	perl test.pl
+	status=$?
+    else
+	echo "Arrgh ... make -f GNUmakefile.install failed in qa/perl directory"
+	cat ../$seq.full
+    fi
 else
-    echo "Arrgh ... make failed in qa/perl directory"
-    cat ../$seq.full
+    if make 2>&1 >../$seq.full
+    then
+	perl test.pl
+	status=$?
+    else
+	echo "Arrgh ... make failed in qa/perl directory"
+	cat ../$seq.full
+    fi
 fi
 
 # all done
