pmdapipe: initial QA testing work - tests 878 and 879
Adds test 878 to exercise PMDA install, remove and event
tracing functionality.  Test 879 is added to exercise all
the corner cases in configuration parsing.

Couple bugs found by tests fixed up, and added support for
expanding a directory of configuration files and expansion
for dollar-zero as well.

diff --git a/qa/878 b/qa/878
--- a/qa/878
+++ b/qa/878
@@ -14,14 +14,77 @@ echo "QA output created by $seq"
 . ./common.check
 
 [ -f $PCP_PMDAS_DIR/pipe/pmdapipe ] || _notrun "pipe PMDA not installed"
+id -u nobody >/dev/null 2>&1 || _notrun "User nobody unavailable"
+
+PIPE_CONF_FILE=$PCP_PMDAS_DIR/pipe/pipe.conf
+PIPE_CONF_DIR=$PCP_SYSCONF_DIR/pipe.conf.d
+PIPE_INDOM_CACHE=$PCP_VAR_DIR/config/pmda/128.0
 
 status=1	# failure is the default!
+username=`id -u -n`
 $sudo rm -rf $tmp $tmp.* $seq.full
 
-_filter_pipe()
+_cleanup()
 {
-    # cull message resulting from no running httpd
-    grep -v 'No value(s) available'
+    [ -d $PIPE_CONF_DIR.$seq ] && _restore_config $PIPE_CONF_DIR
+    [ -f $PIPE_CONF_FILE.$seq ] && _restore_config $PIPE_CONF_FILE
+    [ -f $PIPE_INDOM_CACHE.$seq ] && _restore_config $PIPE_INDOM_CACHE
+    _cleanup_pmda pipe
+}
+
+_prepare_pmda pipe
+trap "_cleanup; exit \$status" 0 1 2 3 15
+
+# move aside pipe configuration state to be restored later.
+[ -d $PIPE_CONF_DIR ] && _save_config $PIPE_CONF_DIR
+[ -f $PIPE_CONF_FILE ] && _save_config $PIPE_CONF_FILE
+[ -f $PIPE_INDOM_CACHE ] && _save_config $PIPE_INDOM_CACHE
+
+cat <<EOF > $tmp.config
+# instance   user        command
+empty-line   $username   echo
+echo-all     $username   echo \$0
+echo-two     $username   echo \$1 \$2
+ls-pipe      root        ls $PCP_PMDAS_DIR/pipe | LC_COLLATE=POSIX sort
+
+[access]
+disallow user $username : empty-line
+EOF
+
+cat << EOF1 > $tmp.confdir
+noop         nobody      exit
+[access]
+disallow user $username : noop
+EOF1
+
+_filter_pmval()
+{
+    sed \
+	-e 's/[0-9][0-9]:[0-9][0-9]:[0-9][0-9].[0-9][0-9][0-9]/HH:MM:SS.MSEC/g' \
+    #end
+}
+
+# pmdapipe is installed with custom configuration, check it
+#
+_exercise_pipe()
+{
+    echo "== basic empty line (ok) =="
+    pmval -x '' -i empty-line -t 0.5 -s 5 pipe.firehose | _filter_pmval
+
+    echo "== basic echo mirror (ok) =="
+    pmval -x 'hello' -i echo-all -t 0.5 -s 5 pipe.firehose | _filter_pmval
+
+    echo "== extra parameters (ok) =="
+    pmval -x '1 two 3' -i echo-two -t 0.5 -s 5 pipe.firehose | _filter_pmval
+
+    echo "== bad parameters (expect failure) =="
+    pmval -x '1;2' -i echo-all -t 0.5 -s 5 pipe.firehose | _filter_pmval
+
+    echo "== insufficient parameters (expect failure) =="
+    pmval -x 'one' -i echo-two -t 0.5 -s 5 pipe.firehose | _filter_pmval
+
+#    echo "== disallowed access (expect failure) =="
+#    pmval -x '' -i noop -s 5 pipe.firehose | _filter_pmval
 }
 
 pmdapipe_remove()
@@ -32,12 +95,20 @@ pmdapipe_remove()
     _filter_pmda_remove <$tmp.out
 }
 
+# install new (deterministic) configuration for pmcd/pmdapipe
+#
 pmdapipe_install()
 {
     # start from known starting points
     cd $PCP_PMDAS_DIR/pipe
     $sudo ./Remove >/dev/null 2>&1
     $sudo $PCP_RC_DIR/pmcd stop 2>&1 | _filter_pcp_stop
+
+    $sudo rm -rf "$PIPE_CONF_DIR" "$PIPE_CONF_FILE" "$PIPE_INDOM_CACHE"
+    $sudo mkdir -m 755 "$PIPE_CONF_DIR"
+
+    $sudo mv $tmp.confdir $PIPE_CONF_DIR/config-$seq
+    $sudo mv $tmp.config $PIPE_CONF_FILE
 
     echo
     echo "=== pipe agent installation ==="
@@ -55,8 +126,11 @@ pmdapipe_install()
                                    { print }'
 }
 
-_prepare_pmda pipe
-trap "_cleanup_pmda pipe; exit \$status" 0 1 2 3 15
+_filter_pipe()
+{
+    # cull message resulting from non-event check access (pminfo/pmprobe)
+    grep -v 'No value(s) available'
+}
 
 # real QA test starts here
 pmdapipe_install
@@ -66,12 +140,14 @@ pmdapipe_install
 # and setup states.
 if pminfo -v pipe > $tmp.info 2> $tmp.err
 then
-    :
+    cat $tmp.info $tmp.err | _filter_pipe
+    _exercise_pipe
 else
     echo "... failed! ... here is the Install log ..."
     cat $tmp.out
+    echo "... pminfo -v pipe ..."
+    cat $tmp.info $tmp.err
 fi
-cat $tmp.info $tmp.err | _filter_pipe
 
 pmdapipe_remove
 status=0
