qa: update test 920 to use common pmlogger job control functions

diff --git a/qa/920 b/qa/920
--- a/qa/920
+++ b/qa/920
@@ -16,16 +16,24 @@ echo "QA output created by $seq"
 . ./common.filter
 . ./common.check
 
+_check_job_scheduler
+
+status=1	# failure is the default!
+needclean=true
+$sudo rm -rf $tmp $tmp.* $seq.full
+trap "_cleanup; exit \$status" 0 1 2 3 15
+
 _cleanup()
 {
     if $needclean
     then
-	$sudo rm -f ${PCP_PMLOGGERCONTROL_PATH}.d/qa-$seq
+	_restore_config $control
 	needclean=false
-	_service pmlogger start >/dev/null 2>&1
+	_restore_primary_logger
 	_service pcp restart 2>&1 | _filter_pcp_start
 	_wait_for_pmcd
 	_wait_for_pmlogger
+	_restore_job_scheduler $tmp.cron $tmp.systemd $sudo
     fi
     cd $here
     $sudo rm -rf $tmp $tmp.*
@@ -71,22 +79,23 @@ _filter_pmlogger_check()
     #end
 }
 
-status=1	# failure is the default!
-needclean=true
-$sudo rm -rf $tmp $tmp.* $seq.full
-trap "_cleanup; exit \$status" 0 1 2 3 15
+control=$PCP_PMLOGGERCONTROL_PATH
+[ -f $PCP_PMLOGGERCONTROL_PATH.d/local ] && \
+control=$PCP_PMLOGGERCONTROL_PATH.d/local
 
 # real QA test starts here
+_remove_job_scheduler $tmp.cron $tmp.systemd $sudo
 _service pmlogger stop 2>&1 | _filter_pcp_stop
 
-cat <<End-of-File >$tmp.tmp
+cat <<End-of-File >$tmp.control
 # dummy file created by qa/$seq on `date`
 # the goal here is to have a non-primary logger that has a deeply
 # nested directory structure for the logs
 \$version=1.1
 LOCALHOSTNAME n n $tmp/pmlogger/myhost/2017/02/12 -c /dev/null -L
 End-of-File
-$sudo cp $tmp.tmp ${PCP_PMLOGGERCONTROL_PATH}.d/qa-$seq
+_save_config $control
+$sudo cp $tmp.control $control
 
 _service pmlogger start | _filter_pcp_start
 
@@ -109,4 +118,3 @@ echo
 # success, all done
 status=0
 exit
-
