qa: small change for PM_CONTEXT_LOCAL tests
On some platforms (but not all), using PM_CONTEXT_LOCAL with the
operating system PMDA may require root privileges, e.g. to open
/dev/kmem or make special system calls.

Introducing $sudo_context_local for qa tests that can be used,
e.g. $sudo_context_local pminfo ... -L ...
and this will allow commands and QA apps using PM_CONTEXT_LOCAL
to run as root if required on the QA platform, else runs without
privilege escalation.

Prompted by OpenIndiana where the solaris PMDA needs to open
/dev/kmem and this was causing lots of QA failures with permission
denied messages.  With this change these tests on OpenIndiana will
run as root, but on Linux (for example) these tests will run with
the uid of the QA tester.

diff --git a/qa/998 b/qa/998
--- a/qa/998
+++ b/qa/998
@@ -16,31 +16,43 @@ echo "QA output created by $seq"
 
 status=1	# failure is the default!
 $sudo rm -rf $tmp $tmp.* $seq.full
-trap "cd $here; rm -rf $tmp.*; exit \$status" 0 1 2 3 15
+trap "cd $here; $sudo rm -rf $tmp.*; exit \$status" 0 1 2 3 15
+
+# Expect this ...
+# Unlock Fail: Operation not permitted
+# may see this on Solaris/OpenIndiana ...
+# Unlock Fail: Not owner
+#
+_filter()
+{
+    sed \
+	-e '/Unlock Fail/s/Not owner/Operation not permitted/' \
+    # end
+}
 
 # real QA test starts here
 echo "=== -x (no context) ==="
-src/github-50 -x
+src/github-50 -x 2>&1 | _filter
 
 echo
 echo "=== no args, default context ==="
-src/github-50
+src/github-50 2>&1 | _filter
 
 echo
 echo "=== -h local: ==="
-src/github-50 -h 'local:'
+src/github-50 -h 'local:' 2>&1 | _filter
 
 echo
 echo '=== -h `hostname` ==='
-src/github-50 -h `hostname`
+src/github-50 -h `hostname` 2>&1 | _filter
 
 echo
 echo '=== -L ==='
-src/github-50 -L
+$sudo_local_ctx src/github-50 -L 2>&1 | _filter
 
 echo
 echo '=== -a archives/ok-foo ==='
-src/github-50 -a archives/ok-foo
+src/github-50 -a archives/ok-foo 2>&1 | _filter
 
 # success, all done
 status=0
