qa/common: smarter arg parsing to detect bogus arguments
Previously this happened ...

kenj@vm01:~/src/pcp/qa$ check -l rubbish
PMDA probe: pminfo -h vm01 -f sample.milliseconds
PMDA probe: pminfo -h vm01 -f sampledso.milliseconds
PMDA probe: pminfo -h vm01 -f simple.numfetch
000 0s ...
Passed all 1 tests

Now this happens ...

kenj@bozo-vm:~/src/pcp/qa$ check -l rubbish
Error: "rubbish" is not a valid QA test number
Aborted! [during setup]

diff --git a/qa/common b/qa/common
--- a/qa/common
+++ b/qa/common
@@ -673,9 +673,15 @@ p
 	    range=true
 	    ;;
 
-	*)
+	[0-9][0-9][0-9]|[0-9][0-9][0-9][0-9])
 	    start=$r
 	    end=$r
+	    ;;
+
+	*)
+	    echo "Error: \"$r\" is not a valid QA test number" >&2
+	    status=1
+	    exit $status
 	    ;;
 
     esac
