qa/new: fix interaction between -r and -R
Based on per @coderabbitai suggestion for PR #2598.

diff --git a/qa/new b/qa/new
--- a/qa/new
+++ b/qa/new
@@ -53,14 +53,19 @@ do
 		;;
 	q)	quick=true
 		;;
-	r)	reserve=true
-		if $unreserve
+	r)	if $unreserve
 		then
 		    echo "Error: cannot have -r after -R $id"
 		    exit 1
 		fi
+		reserve=true
 		;;
-	R)	unreserve=true
+	R)	if $reserve
+		then
+		    echo "Error: cannot have -R $id after -r"
+		    exit 1
+		fi
+		unreserve=true
 		id="$OPTARG"
 		if grep -q "^$id:reserved" group
 		then
@@ -68,17 +73,11 @@ do
 		    do
 			if [ -f $id$suff ]
 			then
-			    echo "Error: $id$suff already exists"
-			    exit 1
+			    echo "Warning: $id$suff already exists"
 			fi
 		    done
 		else
 		    echo "Error: $id not reserved in group file"
-		    exit 1
-		fi
-		if $reserve
-		then
-		    echo "Error: cannot have -R $id after -r"
 		    exit 1
 		fi
 		;;
@@ -253,12 +252,19 @@ fi
 
 if [ -f $id ]
 then
-    echo >&2 "Error: test $id already exists, but not in group file!"
-    _cleanup
-    exit
-fi
-
-cat <<End-of-File >$id
+    if $unreserve
+    then
+	# assume prior -r created the test ...
+	#
+	new_file=false
+    else
+	echo >&2 "Error: test $id already exists, but not in group file!"
+	_cleanup
+	exit
+    fi
+else
+    new_file=true
+    cat <<End-of-File >$id
 #!/bin/sh
 # PCP QA Test No. $id
 End-of-File
@@ -333,7 +339,8 @@ exit
 # success, all done
 exit
 End-of-File
-chmod 755 $id
+    chmod 755 $id
+fi
 
 tag=""
 if $reserve
@@ -342,9 +349,19 @@ then
     tag=":reserved"
 elif $quick
 then
-    echo "Skeletal $id script created"
+    if $new_file
+    then
+	echo "Skeletal $id script created"
+    else
+	echo "Skeletal $id script already existed"
+    fi
 else
-    $PCP_ECHO_PROG $PCP_ECHO_N "Creating skeletal $id script for you to edit ...""$PCP_ECHO_C"
+    if $new_file
+    then
+	$PCP_ECHO_PROG $PCP_ECHO_N "Creating skeletal $id script for you to edit ...""$PCP_ECHO_C"
+    else
+	$PCP_ECHO_PROG $PCP_ECHO_N "Using existing $id script for you to edit ...""$PCP_ECHO_C"
+    fi
     sleep 2		# latency to read messages to this point, before vi(1)
     echo ""
     ${EDITOR-vi} $id
@@ -414,8 +431,10 @@ then
   }
   print ""
 }'`
+    echo "Updating $id entry in group index"
+else
+    echo "Adding $id entry to group index"
 fi
-echo "Adding $id to group index"
 echo "$id$tag $ans" >>group
 
 # sort the tests numerically
